# Round 3 results
After ProteinMPNN redesign from selected backbones

| Metric | Round1 | Round2 | Round2.5 | Round3 |
|---|---|---|---|---|
| Total designs | 2480 | 9520 | 59 | 2701 |
| ipAE < 5 | 2 (0.08%) | 88 (0.92%) | 22 (37.3%) | 98 (3.6%) |
| Pass all filters | 18 (0.73%) | 402 (4.2%) | 50 (87.4%) | 610 (22.6%) |
| Backbones with >=1 pass | 15/310 (4.8%) | 190/1190 (16.0%) | 50/59 (84.7%) | 610/2701 (22.6%) |

**What to do next**
With 610 passing designs:
1. Redo specificity scoring and compute AF3 stats
2. Combining passing designs from round 2, deep MPNN mining on top backbones — Running 32–50 sequences per backbone at T=0.1 and 0.2 on the top ~20–30 backbones (those with ≥3 passing sequences) would be the highest-yield next step.

## Calculate ipSAE

In [1]:
import sys
import glob
from pathlib import Path
from collections import OrderedDict
import pandas as pd
from scipy.stats import spearmanr

import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
matplotlib.rcParams['figure.dpi'] = 120

# Add the directory containing pmhci_ipsae.py and pae_cutoff_analysis.py
# to the path. Edit this if your scripts are elsewhere.
SCRIPT_DIR = Path(".")   # <-- update if needed
sys.path.insert(0, str(SCRIPT_DIR))

from calc_ipsae import (
    load_pae_matrix, build_chain_slices,
    chain_lengths_from_pdb, score_binder_peptide_ipsae, print_summary,
)

print("Imports OK")

Imports OK

In [2]:
PAE_DIR  = Path("/n/groups/marks/users/aaron/pmhc_cp/af_init_guess/outputs/r3/af2_kras/pae")
PDB_DIR  = Path("/n/groups/marks/users/aaron/pmhc_cp/af_init_guess/inputs/r3/threaded_pdbs")

NOMINAL_CUTOFF = 12.0   # Angstroms
DIST_CUTOFF    = 8.0    # Cα distance threshold for crystal contacts (Angstroms)
PEPTIDE_LEN = 9 # VVGADGVGK

In [3]:
# ── Discover design PAE + PDB pairs ─────────────────────────────────────────
npy_files = sorted(PAE_DIR.glob("*_pae.npy"))
pdb_files = []
for npy in npy_files:
    # Corresponding PDB: strip _pae.npy suffix, add .pdb
    stem = npy.stem.replace("_af2pred_pae", "")
    pdb  = PDB_DIR / f"{stem}.pdb"
    pdb_files.append(str(pdb) if pdb.exists() else None)

labels = [Path(n).stem.replace("_pae", "") for n in npy_files]

print(f"Found {len(npy_files)} PAE files")
print(f"  PDB matched: {sum(p is not None for p in pdb_files)} / {len(npy_files)}")
for npy, pdb, label in zip(npy_files, pdb_files, labels):
    pdb_ok = "✓" if pdb else "✗ (no PDB)"
    print(f"  {label:<50s} {pdb_ok}")

Found 2701 PAE files
  PDB matched: 2701 / 2701
  orient_252_pt20__31_pt12__0_a10_t0.1_s7_af2pred    ✓
  orient_252_pt20__31_pt12__0_a14_t0.15_s8_af2pred   ✓
  orient_252_pt20__31_pt12__0_a15_t0.15_s6_af2pred   ✓
  orient_252_pt20__31_pt12__0_a25_t0.2_s8_af2pred    ✓
  orient_252_pt20__31_pt12__0_a3_t0.1_s3_af2pred     ✓
  orient_252_pt20__31_pt12__0_a7_t0.1_s8_af2pred     ✓
  orient_252_pt20__31_pt12__0_a8_t0.1_s4_af2pred     ✓
  orient_252_pt20__31_pt12__0_a8_t0.1_s7_af2pred     ✓
  orient_252_pt20__31_pt12__14_a14_t0.15_s5_af2pred  ✓
  orient_252_pt20__31_pt12__14_a15_t0.15_s1_af2pred  ✓
  orient_252_pt20__31_pt12__14_a15_t0.15_s3_af2pred  ✓
  orient_252_pt20__31_pt12__14_a16_t0.15_s4_af2pred  ✓
  orient_252_pt20__31_pt12__14_a20_t0.15_s5_af2pred  ✓
  orient_252_pt20__31_pt12__14_a22_t0.2_s3_af2pred   ✓
  orient_252_pt20__31_pt12__14_a8_t0.1_s1_af2pred    ✓
  orient_252_pt20__31_pt12__14_a9_t0.1_s8_af2pred    ✓
  orient_252_pt20__31_pt12__16_a1_t0.1_s5_af2pred    ✓
  orient_252_pt20__31_pt12__16_a2_t0.1_s4_af2pred    ✓
  orient_252_pt20__31_pt12__16_a2_t0.1_s5_af2pred    ✓
  orient_252_pt20__31_pt12__16_a2_t0.1_s7_af2pred    ✓
  orient_252_pt20__31_pt12__16_a3_t0.1_s7_af2pred    ✓
  orient_252_pt20__31_pt12__16_a4_t0.1_s3_af2pred    ✓
  orient_252_pt20__31_pt12__16_a5_t0.1_s2_af2pred    ✓
  orient_252_pt20__31_pt12__16_a5_t0.1_s6_af2pred    ✓
  orient_252_pt20__31_pt12__27_a1_t0.1_s2_af2pred    ✓
  orient_252_pt20__31_pt12__27_a2_t0.1_s1_af2pred    ✓
  orient_252_pt20__31_pt12__27_a3_t0.1_s6_af2pred    ✓
  orient_252_pt20__31_pt12__27_a5_t0.1_s2_af2pred    ✓
  orient_252_pt20__31_pt12__27_a7_t0.1_s4_af2pred    ✓
  orient_252_pt20__31_pt12__27_a7_t0.1_s5_af2pred    ✓
  orient_252_pt20__31_pt12__27_a8_t0.1_s1_af2pred    ✓
  orient_252_pt20__31_pt12__27_a8_t0.1_s4_af2pred    ✓
  orient_252_pt20__31_pt12__42_a1_t0.1_s5_af2pred    ✓
  orient_252_pt20__31_pt12__42_a1_t0.1_s6_af2pred    ✓
  orient_252_pt20__31_pt12__42_a1_t0.1_s7_af2pred    ✓
  orient_252_pt20__31_pt12__42_a2_t0.1_s2_af2pred    ✓
  orient_252_pt20__31_pt12__42_a2_t0.1_s5_af2pred    ✓
  orient_252_pt20__31_pt12__42_a2_t0.1_s8_af2pred    ✓
  orient_252_pt20__31_pt12__42_a3_t0.1_s5_af2pred    ✓
  orient_252_pt20__31_pt12__42_a4_t0.1_s2_af2pred    ✓
  orient_252_pt20__31_pt12__52_a1_t0.1_s1_af2pred    ✓
  orient_252_pt20__31_pt12__52_a1_t0.1_s2_af2pred    ✓
  orient_252_pt20__31_pt12__52_a1_t0.1_s4_af2pred    ✓
  orient_252_pt20__31_pt12__52_a1_t0.1_s6_af2pred    ✓
  orient_252_pt20__31_pt12__52_a1_t0.1_s7_af2pred    ✓
  orient_252_pt20__31_pt12__52_a2_t0.1_s1_af2pred    ✓
  orient_252_pt20__31_pt12__52_a2_t0.1_s2_af2pred    ✓
  orient_252_pt20__31_pt12__52_a2_t0.1_s3_af2pred    ✓
  orient_252_pt20__31_pt12__53_a1_t0.1_s2_af2pred    ✓
  orient_252_pt20__31_pt12__53_a1_t0.1_s3_af2pred    ✓
  orient_252_pt20__31_pt12__53_a1_t0.1_s5_af2pred    ✓
  orient_252_pt20__31_pt12__53_a1_t0.1_s6_af2pred    ✓
  orient_252_pt20__31_pt12__53_a1_t0.1_s7_af2pred    ✓
  orient_252_pt20__31_pt12__53_a2_t0.1_s3_af2pred    ✓
  orient_252_pt20__31_pt12__53_a2_t0.1_s4_af2pred    ✓
  orient_252_pt20__31_pt12__53_a2_t0.1_s8_af2pred    ✓
  orient_252_pt20__31_pt12__60_a15_t0.15_s3_af2pred  ✓
  orient_252_pt20__31_pt12__60_a18_t0.15_s4_af2pred  ✓
  orient_252_pt20__31_pt12__60_a2_t0.1_s3_af2pred    ✓
  orient_252_pt20__31_pt12__60_a4_t0.1_s1_af2pred    ✓
  orient_252_pt20__31_pt12__60_a7_t0.1_s2_af2pred    ✓
  orient_252_pt20__31_pt12__60_a7_t0.1_s8_af2pred    ✓
  orient_252_pt20__31_pt12__60_a9_t0.1_s4_af2pred    ✓
  orient_252_pt20__31_pt12__60_a9_t0.1_s8_af2pred    ✓
  orient_252_pt20__31_pt12__66_a10_t0.1_s1_af2pred   ✓
  orient_252_pt20__31_pt12__66_a10_t0.1_s8_af2pred   ✓
  orient_252_pt20__31_pt12__66_a19_t0.15_s2_af2pred  ✓
  orient_252_pt20__31_pt12__66_a1_t0.1_s2_af2pred    ✓
  orient_252_pt20__31_pt12__66_a24_t0.2_s6_af2pred   ✓
  orient_252_pt20__31_pt12__66_a24_t0.2_s7_af2pred   ✓
  orient_252_pt20__31_pt12__66_a3_t0.1_s7_af2pred    ✓
  orient_252_pt20__31_pt12__66_a8_t0.1_s7_af2pred    ✓
  orient_252_pt20__31_pt12__72_a10_t0.1_s2_af2pred   ✓
  orient_252_pt20__31_pt12__72_a11_t0.15_s1_af2pred  ✓
  orient_252_pt20__31_pt12__72_a1_t0.1_s5_af2pred    ✓
  orient_252_pt20__31_pt12__72_a5_t0.1_s3_af2pred    ✓
  orient_252_pt20__31_pt12__72_a7_t0.1_s5_af2pred    ✓
  orient_252_pt20__31_pt12__72_a7_t0.1_s7_af2pred    ✓
  orient_252_pt20__31_pt12__72_a8_t0.1_s6_af2pred    ✓
  orient_252_pt20__31_pt12__72_a9_t0.1_s4_af2pred    ✓
  orient_252_pt20__31_pt12__73_a1_t0.1_s2_af2pred    ✓
  orient_252_pt20__31_pt12__73_a5_t0.1_s3_af2pred    ✓
  orient_252_pt20__31_pt12__73_a5_t0.1_s6_af2pred    ✓
  orient_252_pt20__31_pt12__73_a5_t0.1_s8_af2pred    ✓
  orient_252_pt20__31_pt12__73_a6_t0.1_s3_af2pred    ✓
  orient_252_pt20__31_pt12__73_a7_t0.1_s5_af2pred    ✓
  orient_252_pt20__31_pt12__73_a7_t0.1_s6_af2pred    ✓
  orient_252_pt20__31_pt12__73_a8_t0.1_s1_af2pred    ✓
  orient_252_pt20__31_pt12__91_a13_t0.15_s2_af2pred  ✓
  orient_252_pt20__31_pt12__91_a15_t0.15_s1_af2pred  ✓
  orient_252_pt20__31_pt12__91_a8_t0.1_s7_af2pred    ✓
  orient_252_pt20__31_pt12__97_a1_t0.1_s1_af2pred    ✓
  orient_252_pt20__31_pt12__97_a1_t0.1_s4_af2pred    ✓
  orient_252_pt20__31_pt12__97_a2_t0.1_s2_af2pred    ✓
  orient_252_pt20__31_pt12__97_a2_t0.1_s8_af2pred    ✓
  orient_252_pt20__31_pt12__97_a3_t0.1_s1_af2pred    ✓
  orient_252_pt20__31_pt12__97_a3_t0.1_s5_af2pred    ✓
  orient_252_pt20__31_pt12__97_a6_t0.1_s2_af2pred    ✓
  orient_252_pt20__31_pt12__97_a7_t0.1_s2_af2pred    ✓
  orient_252_pt20__31_pt12__9_a2_t0.1_s4_af2pred     ✓
  orient_252_pt20__31_pt12__9_a2_t0.1_s6_af2pred     ✓
  orient_252_pt20__31_pt12__9_a5_t0.1_s6_af2pred     ✓
  orient_252_pt20__31_pt12__9_a6_t0.1_s2_af2pred     ✓
  orient_252_pt20__31_pt12__9_a7_t0.1_s2_af2pred     ✓
  orient_252_pt20__31_pt12__9_a7_t0.1_s3_af2pred     ✓
  orient_252_pt20__31_pt12__9_a7_t0.1_s5_af2pred     ✓
  orient_252_pt20__31_pt12__9_a7_t0.1_s6_af2pred     ✓
  orient_255_pt12__18_pt12__0_a1_t0.1_s7_af2pred     ✓
  orient_255_pt12__18_pt12__0_a2_t0.1_s7_af2pred     ✓
  orient_255_pt12__18_pt12__0_a2_t0.1_s8_af2pred     ✓
  orient_255_pt12__18_pt12__0_a3_t0.1_s1_af2pred     ✓
  orient_255_pt12__18_pt12__0_a3_t0.1_s3_af2pred     ✓
  orient_255_pt12__18_pt12__0_a5_t0.1_s3_af2pred     ✓
  orient_255_pt12__18_pt12__0_a5_t0.1_s5_af2pred     ✓
  orient_255_pt12__18_pt12__0_a5_t0.1_s6_af2pred     ✓
  orient_255_pt12__18_pt12__10_a1_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__10_a1_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__10_a1_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__10_a1_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__10_a2_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__10_a2_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__10_a2_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__10_a2_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__12_a18_t0.15_s4_af2pred  ✓
  orient_255_pt12__18_pt12__12_a1_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__12_a20_t0.15_s6_af2pred  ✓
  orient_255_pt12__18_pt12__12_a24_t0.2_s6_af2pred   ✓
  orient_255_pt12__18_pt12__12_a26_t0.2_s3_af2pred   ✓
  orient_255_pt12__18_pt12__12_a30_t0.2_s6_af2pred   ✓
  orient_255_pt12__18_pt12__12_a4_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__13_a1_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__13_a1_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__13_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__13_a1_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__13_a2_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__13_a3_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__13_a3_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__13_a3_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__14_a1_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__14_a2_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__14_a2_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__14_a4_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__14_a4_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__14_a5_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__14_a5_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__14_a7_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__1_a1_t0.1_s7_af2pred     ✓
  orient_255_pt12__18_pt12__1_a2_t0.1_s1_af2pred     ✓
  orient_255_pt12__18_pt12__1_a2_t0.1_s4_af2pred     ✓
  orient_255_pt12__18_pt12__1_a2_t0.1_s5_af2pred     ✓
  orient_255_pt12__18_pt12__1_a3_t0.1_s1_af2pred     ✓
  orient_255_pt12__18_pt12__1_a3_t0.1_s2_af2pred     ✓
  orient_255_pt12__18_pt12__1_a3_t0.1_s4_af2pred     ✓
  orient_255_pt12__18_pt12__1_a3_t0.1_s6_af2pred     ✓
  orient_255_pt12__18_pt12__21_a11_t0.15_s3_af2pred  ✓
  orient_255_pt12__18_pt12__21_a13_t0.15_s7_af2pred  ✓
  orient_255_pt12__18_pt12__21_a14_t0.15_s7_af2pred  ✓
  orient_255_pt12__18_pt12__21_a16_t0.15_s5_af2pred  ✓
  orient_255_pt12__18_pt12__21_a3_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__21_a7_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__21_a8_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__21_a9_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__23_a29_t0.2_s4_af2pred   ✓
  orient_255_pt12__18_pt12__24_a1_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__24_a1_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__24_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__24_a1_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__24_a2_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__24_a2_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__24_a2_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__24_a2_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__25_a1_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__25_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__25_a1_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__25_a1_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__25_a2_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__25_a2_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__25_a2_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__25_a2_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__26_a1_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__26_a1_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__26_a2_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__26_a2_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__26_a3_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__26_a3_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__26_a3_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__26_a4_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__29_a11_t0.15_s4_af2pred  ✓
  orient_255_pt12__18_pt12__29_a13_t0.15_s2_af2pred  ✓
  orient_255_pt12__18_pt12__29_a20_t0.15_s3_af2pred  ✓
  orient_255_pt12__18_pt12__29_a22_t0.2_s5_af2pred   ✓
  orient_255_pt12__18_pt12__29_a27_t0.2_s8_af2pred   ✓
  orient_255_pt12__18_pt12__29_a28_t0.2_s3_af2pred   ✓
  orient_255_pt12__18_pt12__29_a28_t0.2_s6_af2pred   ✓
  orient_255_pt12__18_pt12__29_a5_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__30_a1_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__30_a1_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__30_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__30_a1_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__30_a1_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__30_a2_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__30_a2_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__30_a2_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__31_a1_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__31_a1_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__31_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__31_a1_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__31_a1_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__31_a2_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__31_a2_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__31_a2_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__34_a1_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__34_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__34_a2_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__34_a2_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__34_a2_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__34_a2_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__34_a3_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__34_a4_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__39_a10_t0.1_s6_af2pred   ✓
  orient_255_pt12__18_pt12__39_a11_t0.15_s4_af2pred  ✓
  orient_255_pt12__18_pt12__39_a11_t0.15_s7_af2pred  ✓
  orient_255_pt12__18_pt12__39_a11_t0.15_s8_af2pred  ✓
  orient_255_pt12__18_pt12__39_a3_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__39_a3_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__39_a3_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__39_a7_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__40_a1_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__40_a2_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__40_a2_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__40_a3_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__40_a3_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__40_a3_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__40_a4_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__40_a6_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__41_a14_t0.15_s1_af2pred  ✓
  orient_255_pt12__18_pt12__41_a16_t0.15_s4_af2pred  ✓
  orient_255_pt12__18_pt12__41_a16_t0.15_s5_af2pred  ✓
  orient_255_pt12__18_pt12__41_a19_t0.15_s1_af2pred  ✓
  orient_255_pt12__18_pt12__41_a20_t0.15_s8_af2pred  ✓
  orient_255_pt12__18_pt12__41_a2_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__41_a2_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__41_a9_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__42_a1_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__42_a1_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__42_a1_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__42_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__42_a1_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__42_a1_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__42_a1_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__42_a2_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__45_a10_t0.1_s5_af2pred   ✓
  orient_255_pt12__18_pt12__45_a11_t0.15_s8_af2pred  ✓
  orient_255_pt12__18_pt12__45_a13_t0.15_s2_af2pred  ✓
  orient_255_pt12__18_pt12__45_a2_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__45_a3_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__45_a5_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__45_a8_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__45_a9_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__47_a1_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__47_a1_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__47_a2_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__47_a2_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__47_a2_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__47_a3_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__47_a3_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__47_a4_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__52_a10_t0.1_s8_af2pred   ✓
  orient_255_pt12__18_pt12__52_a12_t0.15_s1_af2pred  ✓
  orient_255_pt12__18_pt12__52_a16_t0.15_s3_af2pred  ✓
  orient_255_pt12__18_pt12__52_a17_t0.15_s1_af2pred  ✓
  orient_255_pt12__18_pt12__52_a4_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__52_a5_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__52_a6_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__52_a8_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__53_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__53_a1_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__53_a1_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__53_a1_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__53_a2_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__53_a2_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__53_a2_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__53_a2_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__54_a1_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__54_a1_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__54_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__54_a1_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__54_a2_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__54_a2_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__54_a2_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__54_a2_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__60_a1_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__60_a1_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__60_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__60_a1_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__60_a2_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__60_a2_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__60_a2_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__60_a3_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__63_a11_t0.15_s4_af2pred  ✓
  orient_255_pt12__18_pt12__63_a13_t0.15_s3_af2pred  ✓
  orient_255_pt12__18_pt12__63_a14_t0.15_s5_af2pred  ✓
  orient_255_pt12__18_pt12__63_a14_t0.15_s6_af2pred  ✓
  orient_255_pt12__18_pt12__63_a15_t0.15_s3_af2pred  ✓
  orient_255_pt12__18_pt12__63_a16_t0.15_s2_af2pred  ✓
  orient_255_pt12__18_pt12__63_a16_t0.15_s3_af2pred  ✓
  orient_255_pt12__18_pt12__63_a4_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__65_a1_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__65_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__65_a1_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__65_a1_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__65_a2_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__65_a2_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__65_a2_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__65_a2_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__66_a1_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__66_a1_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__66_a1_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__66_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__66_a1_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__66_a2_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__66_a2_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__66_a2_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__68_a1_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__68_a1_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__68_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__68_a1_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__68_a1_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__68_a1_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__68_a2_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__68_a2_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__69_a10_t0.1_s6_af2pred   ✓
  orient_255_pt12__18_pt12__69_a13_t0.15_s2_af2pred  ✓
  orient_255_pt12__18_pt12__69_a13_t0.15_s3_af2pred  ✓
  orient_255_pt12__18_pt12__69_a13_t0.15_s7_af2pred  ✓
  orient_255_pt12__18_pt12__69_a18_t0.15_s8_af2pred  ✓
  orient_255_pt12__18_pt12__69_a5_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__69_a7_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__69_a9_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__71_a1_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__71_a1_t0.1_s2_af2pred    ✓
  orient_255_pt12__18_pt12__71_a1_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__71_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__71_a1_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__71_a1_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__71_a1_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__71_a1_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__80_a10_t0.1_s5_af2pred   ✓
  orient_255_pt12__18_pt12__80_a12_t0.15_s1_af2pred  ✓
  orient_255_pt12__18_pt12__80_a15_t0.15_s4_af2pred  ✓
  orient_255_pt12__18_pt12__80_a18_t0.15_s8_af2pred  ✓
  orient_255_pt12__18_pt12__80_a26_t0.2_s7_af2pred   ✓
  orient_255_pt12__18_pt12__83_a1_t0.1_s3_af2pred    ✓
  orient_255_pt12__18_pt12__83_a1_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__83_a1_t0.1_s7_af2pred    ✓
  orient_255_pt12__18_pt12__83_a1_t0.1_s8_af2pred    ✓
  orient_255_pt12__18_pt12__83_a5_t0.1_s4_af2pred    ✓
  orient_255_pt12__18_pt12__83_a5_t0.1_s5_af2pred    ✓
  orient_255_pt12__18_pt12__83_a5_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__83_a7_t0.1_s6_af2pred    ✓
  orient_255_pt12__18_pt12__84_a1_t0.1_s1_af2pred    ✓
  orient_255_pt12__18_pt12__84_a1_t0.1_s5_af2pred    ✓

In [4]:
# ── Quick ipSAE summary table at the nominal cutoff ─────────────────────────
print(f"{'Design':<50s} {'binder':>7} {'MHC':>5} {'pep':>4} {'ipSAE':>7} {'n_contacts':>11} {'mean_PAE':>9}")
print("─" * 100)

results_table = []
for npy, pdb, label in zip(npy_files, pdb_files, labels):
    try:
        cl = chain_lengths_from_pdb(pdb, peptide_length=PEPTIDE_LEN) if pdb else None
        if cl is None:
            print(f"  {label}: no PDB, skipping")
            continue
        r = score_binder_peptide_ipsae(str(npy), cl, pae_cutoff=NOMINAL_CUTOFF)
        results_table.append({"label": label, "chain_lengths": cl, **r})
        print(f"  {label:<48s} {cl['binder']:>7} {cl['MHC']:>5} {cl['peptide']:>4} "
              f"  {r['ipsae_binder_peptide']:>6.4f}  {r['n_contacts']:>10}  {r['mean_pae_bp']:>8.2f} Å")
    except Exception as e:
        print(f"  {label}: ERROR — {e}")

print(f"\nScored {len(results_table)} designs at PAE cutoff = {NOMINAL_CUTOFF} Å")

results_df = pd.DataFrame(results_table)

Design                                              binder   MHC  pep   ipSAE  n_contacts  mean_PAE
────────────────────────────────────────────────────────────────────────────────────────────────────
  orient_252_pt20__31_pt12__0_a10_t0.1_s7_af2pred       97   178    9   0.0000           0     22.10 Å
  orient_252_pt20__31_pt12__0_a14_t0.15_s8_af2pred      97   178    9   0.8607         853      4.20 Å
  orient_252_pt20__31_pt12__0_a15_t0.15_s6_af2pred      97   178    9   0.0000           0     20.35 Å
  orient_252_pt20__31_pt12__0_a25_t0.2_s8_af2pred       97   178    9   0.0000           0     22.40 Å
  orient_252_pt20__31_pt12__0_a3_t0.1_s3_af2pred        97   178    9   0.8721         868      3.76 Å
  orient_252_pt20__31_pt12__0_a7_t0.1_s8_af2pred        97   178    9   0.7129         843      6.61 Å
  orient_252_pt20__31_pt12__0_a8_t0.1_s4_af2pred        97   178    9   0.0000           0     21.56 Å
  orient_252_pt20__31_pt12__0_a8_t0.1_s7_af2pred        97   178    9   0.4528         557     11.13 Å
  orient_252_pt20__31_pt12__14_a14_t0.15_s5_af2pred      97   178    9   0.0000           0     23.10 Å
  orient_252_pt20__31_pt12__14_a15_t0.15_s1_af2pred      97   178    9   0.0000           0     22.50 Å
  orient_252_pt20__31_pt12__14_a15_t0.15_s3_af2pred      97   178    9   0.0000           0     21.98 Å
  orient_252_pt20__31_pt12__14_a16_t0.15_s4_af2pred      97   178    9   0.0000           0     21.09 Å
  orient_252_pt20__31_pt12__14_a20_t0.15_s5_af2pred      97   178    9   0.1023          95     16.05 Å
  orient_252_pt20__31_pt12__14_a22_t0.2_s3_af2pred      97   178    9   0.7714         851      5.64 Å
  orient_252_pt20__31_pt12__14_a8_t0.1_s1_af2pred       97   178    9   0.0476          53     16.66 Å
  orient_252_pt20__31_pt12__14_a9_t0.1_s8_af2pred       97   178    9   0.0000           0     22.61 Å
  orient_252_pt20__31_pt12__16_a1_t0.1_s5_af2pred       97   178    9   0.8641         864      3.97 Å
  orient_252_pt20__31_pt12__16_a2_t0.1_s4_af2pred       97   178    9   0.0000           0     21.63 Å
  orient_252_pt20__31_pt12__16_a2_t0.1_s5_af2pred       97   178    9   0.7715         861      5.54 Å
  orient_252_pt20__31_pt12__16_a2_t0.1_s7_af2pred       97   178    9   0.3422         375     12.67 Å
  orient_252_pt20__31_pt12__16_a3_t0.1_s7_af2pred       97   178    9   0.0000           0     21.39 Å
  orient_252_pt20__31_pt12__16_a4_t0.1_s3_af2pred       97   178    9   0.0021           1     21.66 Å
  orient_252_pt20__31_pt12__16_a5_t0.1_s2_af2pred       97   178    9   0.8099         869      4.80 Å
  orient_252_pt20__31_pt12__16_a5_t0.1_s6_af2pred       97   178    9   0.0019           3     19.88 Å
  orient_252_pt20__31_pt12__27_a1_t0.1_s2_af2pred       97   178    9   0.0000           0     21.38 Å
  orient_252_pt20__31_pt12__27_a2_t0.1_s1_af2pred       97   178    9   0.8813         870      3.59 Å
  orient_252_pt20__31_pt12__27_a3_t0.1_s6_af2pred       97   178    9   0.0019           2     18.68 Å
  orient_252_pt20__31_pt12__27_a5_t0.1_s2_af2pred       97   178    9   0.0000           0     24.22 Å
  orient_252_pt20__31_pt12__27_a7_t0.1_s4_af2pred       97   178    9   0.8846         860      3.65 Å
  orient_252_pt20__31_pt12__27_a7_t0.1_s5_af2pred       97   178    9   0.6190         810      8.17 Å
  orient_252_pt20__31_pt12__27_a8_t0.1_s1_af2pred       97   178    9   0.0000           0     21.17 Å
  orient_252_pt20__31_pt12__27_a8_t0.1_s4_af2pred       97   178    9   0.0000           0     24.71 Å
  orient_252_pt20__31_pt12__42_a1_t0.1_s5_af2pred       97   178    9   0.0000           0     22.58 Å
  orient_252_pt20__31_pt12__42_a1_t0.1_s6_af2pred       97   178    9   0.0000           0     22.72 Å
  orient_252_pt20__31_pt12__42_a1_t0.1_s7_af2pred       97   178    9   0.0000           0     21.54 Å
  orient_252_pt20__31_pt12__42_a2_t0.1_s2_af2pred       97   178    9   0.0000           0     22.36 Å
  orient_252_pt20__31_pt12__42_a2_t0.1_s5_af2pred       97   178    9   0.0000           0     23.05 Å
  orient_252_pt20__31_pt12__42_a2_t0.1_s8_af2pred       97   178    9   0.0000           0     23.14 Å
  orient_252_pt20__31_pt12__42_a3_t0.1_s5_af2pred       97   178    9   0.0000           0     23.39 Å
  orient_252_pt20__31_pt12__42_a4_t0.1_s2_af2pred       97   178    9   0.0000           0     22.60 Å
  orient_252_pt20__31_pt12__52_a1_t0.1_s1_af2pred       97   178    9   0.0000           0     21.78 Å
  orient_252_pt20__31_pt12__52_a1_t0.1_s2_af2pred       97   178    9   0.0000           0     21.90 Å
  orient_252_pt20__31_pt12__52_a1_t0.1_s4_af2pred       97   178    9   0.0000           0     21.62 Å
  orient_252_pt20__31_pt12__52_a1_t0.1_s6_af2pred       97   178    9   0.4970         628     10.42 Å
  orient_252_pt20__31_pt12__52_a1_t0.1_s7_af2pred       97   178    9   0.0000           0     22.10 Å
  orient_252_pt20__31_pt12__52_a2_t0.1_s1_af2pred       97   178    9   0.0000           0     22.70 Å
  orient_252_pt20__31_pt12__52_a2_t0.1_s2_af2pred       97   178    9   0.0000           0     22.84 Å
  orient_252_pt20__31_pt12__52_a2_t0.1_s3_af2pred       97   178    9   0.0000           0     23.02 Å
  orient_252_pt20__31_pt12__53_a1_t0.1_s2_af2pred       97   178    9   0.7810         859      5.42 Å
  orient_252_pt20__31_pt12__53_a1_t0.1_s3_af2pred       97   178    9   0.8643         861      4.02 Å
  orient_252_pt20__31_pt12__53_a1_t0.1_s5_af2pred       97   178    9   0.0018           1     20.41 Å
  orient_252_pt20__31_pt12__53_a1_t0.1_s6_af2pred       97   178    9   0.8339         866      4.43 Å
  orient_252_pt20__31_pt12__53_a1_t0.1_s7_af2pred       97   178    9   0.0000           0     22.90 Å
  orient_252_pt20__31_pt12__53_a2_t0.1_s3_af2pred       97   178    9   0.0000           0     21.50 Å
  orient_252_pt20__31_pt12__53_a2_t0.1_s4_af2pred       97   178    9   0.0000           0     20.71 Å
  orient_252_pt20__31_pt12__53_a2_t0.1_s8_af2pred       97   178    9   0.8753         873      3.66 Å
  orient_252_pt20__31_pt12__60_a15_t0.15_s3_af2pred      97   178    9   0.0000           0     23.05 Å
  orient_252_pt20__31_pt12__60_a18_t0.15_s4_af2pred      97   178    9   0.0000           0     21.97 Å
  orient_252_pt20__31_pt12__60_a2_t0.1_s3_af2pred       97   178    9   0.0000           0     22.67 Å
  orient_252_pt20__31_pt12__60_a4_t0.1_s1_af2pred       97   178    9   0.0000           0     24.88 Å
  orient_252_pt20__31_pt12__60_a7_t0.1_s2_af2pred       97   178    9   0.0000           0     24.78 Å
  orient_252_pt20__31_pt12__60_a7_t0.1_s8_af2pred       97   178    9   0.0000           0     24.05 Å
  orient_252_pt20__31_pt12__60_a9_t0.1_s4_af2pred       97   178    9   0.0000           0     22.37 Å
  orient_252_pt20__31_pt12__60_a9_t0.1_s8_af2pred       97   178    9   0.0028           1     22.51 Å
  orient_252_pt20__31_pt12__66_a10_t0.1_s1_af2pred      97   178    9   0.0000           0     23.43 Å
  orient_252_pt20__31_pt12__66_a10_t0.1_s8_af2pred      97   178    9   0.0000           0     23.39 Å
  orient_252_pt20__31_pt12__66_a19_t0.15_s2_af2pred      97   178    9   0.0019           1     20.55 Å
  orient_252_pt20__31_pt12__66_a1_t0.1_s2_af2pred       97   178    9   0.0000           0     22.59 Å
  orient_252_pt20__31_pt12__66_a24_t0.2_s6_af2pred      97   178    9   0.0000           0     22.31 Å
  orient_252_pt20__31_pt12__66_a24_t0.2_s7_af2pred      97   178    9   0.0000           0     22.03 Å
  orient_252_pt20__31_pt12__66_a3_t0.1_s7_af2pred       97   178    9   0.0000           0     22.52 Å
  orient_252_pt20__31_pt12__66_a8_t0.1_s7_af2pred       97   178    9   0.0000           0     21.95 Å
  orient_252_pt20__31_pt12__72_a10_t0.1_s2_af2pred      97   178    9   0.8210         864      4.67 Å
  orient_252_pt20__31_pt12__72_a11_t0.15_s1_af2pred      97   178    9   0.0000           0     22.94 Å
  orient_252_pt20__31_pt12__72_a1_t0.1_s5_af2pred       97   178    9   0.8067         858      4.94 Å
  orient_252_pt20__31_pt12__72_a5_t0.1_s3_af2pred       97   178    9   0.8652         870      3.85 Å
  orient_252_pt20__31_pt12__72_a7_t0.1_s5_af2pred       97   178    9   0.0000           0     22.84 Å
  orient_252_pt20__31_pt12__72_a7_t0.1_s7_af2pred       97   178    9   0.8139         867      4.75 Å
  orient_252_pt20__31_pt12__72_a8_t0.1_s6_af2pred       97   178    9   0.8197         866      4.68 Å
  orient_252_pt20__31_pt12__72_a9_t0.1_s4_af2pred       97   178    9   0.0019           4     19.03 Å
  orient_252_pt20__31_pt12__73_a1_t0.1_s2_af2pred       97   178    9   0.0000           0     22.23 Å
  orient_252_pt20__31_pt12__73_a5_t0.1_s3_af2pred       97   178    9   0.0000           0     22.39 Å
  orient_252_pt20__31_pt12__73_a5_t0.1_s6_af2pred       97   178    9   0.0000           0     25.51 Å
  orient_252_pt20__31_pt12__73_a5_t0.1_s8_af2pred       97   178    9   0.0000           0     21.59 Å

  orient_252_pt20__31_pt12__73_a6_t0.1_s3_af2pred       97   178    9   0.0000           0     22.03 Å
  orient_252_pt20__31_pt12__73_a7_t0.1_s5_af2pred       97   178    9   0.0000           0     21.82 Å
  orient_252_pt20__31_pt12__73_a7_t0.1_s6_af2pred       97   178    9   0.0000           0     22.52 Å
  orient_252_pt20__31_pt12__73_a8_t0.1_s1_af2pred       97   178    9   0.0000           0     22.71 Å
  orient_252_pt20__31_pt12__91_a13_t0.15_s2_af2pred      97   178    9   0.0000           0     25.16 Å
  orient_252_pt20__31_pt12__91_a15_t0.15_s1_af2pred      97   178    9   0.3623         366     16.63 Å
  orient_252_pt20__31_pt12__91_a8_t0.1_s7_af2pred       97   178    9   0.0000           0     22.69 Å
  orient_252_pt20__31_pt12__97_a1_t0.1_s1_af2pred       97   178    9   0.8802         873      3.57 Å
  orient_252_pt20__31_pt12__97_a1_t0.1_s4_af2pred       97   178    9   0.0000           0     20.94 Å
  orient_252_pt20__31_pt12__97_a2_t0.1_s2_af2pred       97   178    9   0.0000           0     22.48 Å
  orient_252_pt20__31_pt12__97_a2_t0.1_s8_af2pred       97   178    9   0.7948         859      5.15 Å
  orient_252_pt20__31_pt12__97_a3_t0.1_s1_af2pred       97   178    9   0.8366         869      4.35 Å
  orient_252_pt20__31_pt12__97_a3_t0.1_s5_af2pred       97   178    9   0.8648         873      3.82 Å
  orient_252_pt20__31_pt12__97_a6_t0.1_s2_af2pred       97   178    9   0.7719         845      5.62 Å
  orient_252_pt20__31_pt12__97_a7_t0.1_s2_af2pred       97   178    9   0.8464         868      4.20 Å
  orient_252_pt20__31_pt12__9_a2_t0.1_s4_af2pred        97   178    9   0.0000           0     23.30 Å
  orient_252_pt20__31_pt12__9_a2_t0.1_s6_af2pred        97   178    9   0.0000           0     21.35 Å
  orient_252_pt20__31_pt12__9_a5_t0.1_s6_af2pred        97   178    9   0.1699         159     15.07 Å
  orient_252_pt20__31_pt12__9_a6_t0.1_s2_af2pred        97   178    9   0.0000           0     22.15 Å
  orient_252_pt20__31_pt12__9_a7_t0.1_s2_af2pred        97   178    9   0.0021           3     20.47 Å
  orient_252_pt20__31_pt12__9_a7_t0.1_s3_af2pred        97   178    9   0.0000           0     22.80 Å
  orient_252_pt20__31_pt12__9_a7_t0.1_s5_af2pred        97   178    9   0.0000           0     21.92 Å
  orient_252_pt20__31_pt12__9_a7_t0.1_s6_af2pred        97   178    9   0.0000           0     22.42 Å
  orient_255_pt12__18_pt12__0_a1_t0.1_s7_af2pred        93   178    9   0.7934         820      5.14 Å
  orient_255_pt12__18_pt12__0_a2_t0.1_s7_af2pred        93   178    9   0.3088         288     13.35 Å
  orient_255_pt12__18_pt12__0_a2_t0.1_s8_af2pred        93   178    9   0.7842         823      5.30 Å
  orient_255_pt12__18_pt12__0_a3_t0.1_s1_af2pred        93   178    9   0.6372         764      7.86 Å
  orient_255_pt12__18_pt12__0_a3_t0.1_s3_af2pred        93   178    9   0.5942         672      9.14 Å
  orient_255_pt12__18_pt12__0_a5_t0.1_s3_af2pred        93   178    9   0.0020           4     20.06 Å
  orient_255_pt12__18_pt12__0_a5_t0.1_s5_af2pred        93   178    9   0.0155          31     17.50 Å
  orient_255_pt12__18_pt12__0_a5_t0.1_s6_af2pred        93   178    9   0.7480         819      5.89 Å
  orient_255_pt12__18_pt12__10_a1_t0.1_s2_af2pred       93   178    9   0.3848         409     12.47 Å
  orient_255_pt12__18_pt12__10_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     19.72 Å
  orient_255_pt12__18_pt12__10_a1_t0.1_s5_af2pred       93   178    9   0.0019           6     19.44 Å
  orient_255_pt12__18_pt12__10_a1_t0.1_s8_af2pred       93   178    9   0.3069         285     13.38 Å
  orient_255_pt12__18_pt12__10_a2_t0.1_s1_af2pred       93   178    9   0.6321         764      8.07 Å
  orient_255_pt12__18_pt12__10_a2_t0.1_s4_af2pred       93   178    9   0.3935         449     12.06 Å
  orient_255_pt12__18_pt12__10_a2_t0.1_s6_af2pred       93   178    9   0.2188         196     14.41 Å
  orient_255_pt12__18_pt12__10_a2_t0.1_s7_af2pred       93   178    9   0.7535         819      5.82 Å
  orient_255_pt12__18_pt12__12_a18_t0.15_s4_af2pred      93   178    9   0.7580         809      5.75 Å
  orient_255_pt12__18_pt12__12_a1_t0.1_s1_af2pred       93   178    9   0.8022         826      4.91 Å
  orient_255_pt12__18_pt12__12_a20_t0.15_s6_af2pred      93   178    9   0.0000           0     22.19 Å
  orient_255_pt12__18_pt12__12_a24_t0.2_s6_af2pred      93   178    9   0.0000           0     25.19 Å
  orient_255_pt12__18_pt12__12_a26_t0.2_s3_af2pred      93   178    9   0.5716         662      9.33 Å
  orient_255_pt12__18_pt12__12_a30_t0.2_s6_af2pred      93   178    9   0.0000           0     21.32 Å
  orient_255_pt12__18_pt12__12_a4_t0.1_s6_af2pred       93   178    9   0.8360         806      4.67 Å
  orient_255_pt12__18_pt12__13_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     22.34 Å
  orient_255_pt12__18_pt12__13_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     22.37 Å
  orient_255_pt12__18_pt12__13_a1_t0.1_s4_af2pred       93   178    9   0.6955         791      6.95 Å
  orient_255_pt12__18_pt12__13_a1_t0.1_s7_af2pred       93   178    9   0.7895         812      5.38 Å
  orient_255_pt12__18_pt12__13_a2_t0.1_s2_af2pred       93   178    9   0.6867         792      7.12 Å
  orient_255_pt12__18_pt12__13_a3_t0.1_s3_af2pred       93   178    9   0.2371         212     14.29 Å
  orient_255_pt12__18_pt12__13_a3_t0.1_s5_af2pred       93   178    9   0.0000           0     19.50 Å
  orient_255_pt12__18_pt12__13_a3_t0.1_s6_af2pred       93   178    9   0.6286         763      8.05 Å
  orient_255_pt12__18_pt12__14_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     22.18 Å
  orient_255_pt12__18_pt12__14_a2_t0.1_s6_af2pred       93   178    9   0.7958         798      5.30 Å
  orient_255_pt12__18_pt12__14_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     22.62 Å
  orient_255_pt12__18_pt12__14_a4_t0.1_s3_af2pred       93   178    9   0.0019           4     19.56 Å
  orient_255_pt12__18_pt12__14_a4_t0.1_s4_af2pred       93   178    9   0.0000           0     22.15 Å
  orient_255_pt12__18_pt12__14_a5_t0.1_s4_af2pred       93   178    9   0.0000           0     22.56 Å
  orient_255_pt12__18_pt12__14_a5_t0.1_s6_af2pred       93   178    9   0.0000           0     19.11 Å
  orient_255_pt12__18_pt12__14_a7_t0.1_s7_af2pred       93   178    9   0.3473         340     12.95 Å
  orient_255_pt12__18_pt12__1_a1_t0.1_s7_af2pred        93   178    9   0.7247         808      6.29 Å
  orient_255_pt12__18_pt12__1_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     20.54 Å
  orient_255_pt12__18_pt12__1_a2_t0.1_s4_af2pred        93   178    9   0.6688         798      7.25 Å
  orient_255_pt12__18_pt12__1_a2_t0.1_s5_af2pred        93   178    9   0.0020           2     20.98 Å
  orient_255_pt12__18_pt12__1_a3_t0.1_s1_af2pred        93   178    9   0.8052         830      4.82 Å
  orient_255_pt12__18_pt12__1_a3_t0.1_s2_af2pred        93   178    9   0.0000           0     21.70 Å
  orient_255_pt12__18_pt12__1_a3_t0.1_s4_af2pred        93   178    9   0.0660          65     16.70 Å
  orient_255_pt12__18_pt12__1_a3_t0.1_s6_af2pred        93   178    9   0.3510         368     12.71 Å
  orient_255_pt12__18_pt12__21_a11_t0.15_s3_af2pred      93   178    9   0.0019           6     18.52 Å
  orient_255_pt12__18_pt12__21_a13_t0.15_s7_af2pred      93   178    9   0.0000           0     21.63 Å
  orient_255_pt12__18_pt12__21_a14_t0.15_s7_af2pred      93   178    9   0.6917         785      7.07 Å
  orient_255_pt12__18_pt12__21_a16_t0.15_s5_af2pred      93   178    9   0.0000           0     21.61 Å
  orient_255_pt12__18_pt12__21_a3_t0.1_s1_af2pred       93   178    9   0.0000           0     21.99 Å
  orient_255_pt12__18_pt12__21_a7_t0.1_s7_af2pred       93   178    9   0.0671          67     16.78 Å
  orient_255_pt12__18_pt12__21_a8_t0.1_s2_af2pred       93   178    9   0.0000           0     23.03 Å
  orient_255_pt12__18_pt12__21_a9_t0.1_s7_af2pred       93   178    9   0.0000           0     22.23 Å
  orient_255_pt12__18_pt12__23_a29_t0.2_s4_af2pred      93   178    9   0.0000           0     22.10 Å
  orient_255_pt12__18_pt12__24_a1_t0.1_s1_af2pred       93   178    9   0.2476         236     14.19 Å
  orient_255_pt12__18_pt12__24_a1_t0.1_s2_af2pred       93   178    9   0.0020          19     17.89 Å
  orient_255_pt12__18_pt12__24_a1_t0.1_s4_af2pred       93   178    9   0.0019          11     18.70 Å

  orient_255_pt12__18_pt12__24_a1_t0.1_s6_af2pred       93   178    9   0.3985         448     11.96 Å
  orient_255_pt12__18_pt12__24_a2_t0.1_s2_af2pred       93   178    9   0.0190          34     17.67 Å
  orient_255_pt12__18_pt12__24_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     22.00 Å
  orient_255_pt12__18_pt12__24_a2_t0.1_s5_af2pred       93   178    9   0.1946         169     14.63 Å
  orient_255_pt12__18_pt12__24_a2_t0.1_s6_af2pred       93   178    9   0.7283         806      6.26 Å
  orient_255_pt12__18_pt12__25_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     25.39 Å
  orient_255_pt12__18_pt12__25_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     25.54 Å
  orient_255_pt12__18_pt12__25_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     24.06 Å
  orient_255_pt12__18_pt12__25_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     21.05 Å
  orient_255_pt12__18_pt12__25_a2_t0.1_s1_af2pred       93   178    9   0.0238          37     17.41 Å
  orient_255_pt12__18_pt12__25_a2_t0.1_s4_af2pred       93   178    9   0.8158         831      4.64 Å
  orient_255_pt12__18_pt12__25_a2_t0.1_s5_af2pred       93   178    9   0.0000           0     23.00 Å
  orient_255_pt12__18_pt12__25_a2_t0.1_s7_af2pred       93   178    9   0.7202         795      6.58 Å
  orient_255_pt12__18_pt12__26_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     23.94 Å
  orient_255_pt12__18_pt12__26_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     23.08 Å
  orient_255_pt12__18_pt12__26_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.97 Å
  orient_255_pt12__18_pt12__26_a2_t0.1_s4_af2pred       93   178    9   0.5739         693      9.15 Å
  orient_255_pt12__18_pt12__26_a3_t0.1_s5_af2pred       93   178    9   0.0000           0     22.70 Å
  orient_255_pt12__18_pt12__26_a3_t0.1_s7_af2pred       93   178    9   0.0000           0     23.27 Å
  orient_255_pt12__18_pt12__26_a3_t0.1_s8_af2pred       93   178    9   0.0000           0     23.39 Å
  orient_255_pt12__18_pt12__26_a4_t0.1_s1_af2pred       93   178    9   0.0000           0     23.93 Å
  orient_255_pt12__18_pt12__29_a11_t0.15_s4_af2pred      93   178    9   0.0000           0     22.16 Å
  orient_255_pt12__18_pt12__29_a13_t0.15_s2_af2pred      93   178    9   0.0019           2     20.11 Å
  orient_255_pt12__18_pt12__29_a20_t0.15_s3_af2pred      93   178    9   0.0000           0     22.44 Å
  orient_255_pt12__18_pt12__29_a22_t0.2_s5_af2pred      93   178    9   0.0000           0     22.34 Å
  orient_255_pt12__18_pt12__29_a27_t0.2_s8_af2pred      93   178    9   0.0000           0     22.75 Å
  orient_255_pt12__18_pt12__29_a28_t0.2_s3_af2pred      93   178    9   0.0017           1     21.38 Å
  orient_255_pt12__18_pt12__29_a28_t0.2_s6_af2pred      93   178    9   0.0000           0     22.75 Å
  orient_255_pt12__18_pt12__29_a5_t0.1_s8_af2pred       93   178    9   0.0000           0     25.66 Å
  orient_255_pt12__18_pt12__30_a1_t0.1_s2_af2pred       93   178    9   0.4849         577     10.69 Å
  orient_255_pt12__18_pt12__30_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     21.55 Å
  orient_255_pt12__18_pt12__30_a1_t0.1_s4_af2pred       93   178    9   0.0023           9     18.52 Å
  orient_255_pt12__18_pt12__30_a1_t0.1_s6_af2pred       93   178    9   0.0022           3     19.94 Å
  orient_255_pt12__18_pt12__30_a1_t0.1_s7_af2pred       93   178    9   0.2752         267     13.78 Å
  orient_255_pt12__18_pt12__30_a2_t0.1_s2_af2pred       93   178    9   0.0122          29     17.86 Å
  orient_255_pt12__18_pt12__30_a2_t0.1_s3_af2pred       93   178    9   0.5103         611     10.18 Å
  orient_255_pt12__18_pt12__30_a2_t0.1_s4_af2pred       93   178    9   0.6361         766      8.07 Å
  orient_255_pt12__18_pt12__31_a1_t0.1_s1_af2pred       93   178    9   0.3516         380     12.78 Å
  orient_255_pt12__18_pt12__31_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     22.92 Å
  orient_255_pt12__18_pt12__31_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     22.06 Å
  orient_255_pt12__18_pt12__31_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     22.05 Å
  orient_255_pt12__18_pt12__31_a1_t0.1_s7_af2pred       93   178    9   0.8137         815      4.90 Å
  orient_255_pt12__18_pt12__31_a2_t0.1_s1_af2pred       93   178    9   0.7693         805      5.76 Å
  orient_255_pt12__18_pt12__31_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     22.07 Å
  orient_255_pt12__18_pt12__31_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     23.13 Å
  orient_255_pt12__18_pt12__34_a1_t0.1_s2_af2pred       93   178    9   0.6903         779      7.27 Å
  orient_255_pt12__18_pt12__34_a1_t0.1_s4_af2pred       93   178    9   0.7803         804      5.54 Å
  orient_255_pt12__18_pt12__34_a2_t0.1_s4_af2pred       93   178    9   0.8192         828      4.65 Å
  orient_255_pt12__18_pt12__34_a2_t0.1_s5_af2pred       93   178    9   0.0000           0     20.99 Å
  orient_255_pt12__18_pt12__34_a2_t0.1_s6_af2pred       93   178    9   0.7959         827      5.00 Å
  orient_255_pt12__18_pt12__34_a2_t0.1_s7_af2pred       93   178    9   0.1379         124     15.67 Å
  orient_255_pt12__18_pt12__34_a3_t0.1_s1_af2pred       93   178    9   0.6674         766      7.41 Å
  orient_255_pt12__18_pt12__34_a4_t0.1_s4_af2pred       93   178    9   0.7423         800      6.12 Å
  orient_255_pt12__18_pt12__39_a10_t0.1_s6_af2pred      93   178    9   0.0000           0     21.09 Å
  orient_255_pt12__18_pt12__39_a11_t0.15_s4_af2pred      93   178    9   0.0000           0     22.18 Å
  orient_255_pt12__18_pt12__39_a11_t0.15_s7_af2pred      93   178    9   0.0000           0     21.99 Å
  orient_255_pt12__18_pt12__39_a11_t0.15_s8_af2pred      93   178    9   0.0019           2     21.27 Å
  orient_255_pt12__18_pt12__39_a3_t0.1_s1_af2pred       93   178    9   0.0000           0     23.21 Å
  orient_255_pt12__18_pt12__39_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     28.16 Å
  orient_255_pt12__18_pt12__39_a3_t0.1_s8_af2pred       93   178    9   0.0000           0     21.89 Å
  orient_255_pt12__18_pt12__39_a7_t0.1_s8_af2pred       93   178    9   0.0000           0     23.09 Å
  orient_255_pt12__18_pt12__40_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     23.42 Å
  orient_255_pt12__18_pt12__40_a2_t0.1_s1_af2pred       93   178    9   0.8285         821      4.59 Å
  orient_255_pt12__18_pt12__40_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     23.00 Å
  orient_255_pt12__18_pt12__40_a3_t0.1_s1_af2pred       93   178    9   0.5995         736      8.56 Å
  orient_255_pt12__18_pt12__40_a3_t0.1_s2_af2pred       93   178    9   0.3575         385     12.71 Å
  orient_255_pt12__18_pt12__40_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.52 Å
  orient_255_pt12__18_pt12__40_a4_t0.1_s2_af2pred       93   178    9   0.0000           0     23.18 Å
  orient_255_pt12__18_pt12__40_a6_t0.1_s2_af2pred       93   178    9   0.0000           0     24.49 Å
  orient_255_pt12__18_pt12__41_a14_t0.15_s1_af2pred      93   178    9   0.0000           0     23.70 Å
  orient_255_pt12__18_pt12__41_a16_t0.15_s4_af2pred      93   178    9   0.0000           0     23.75 Å
  orient_255_pt12__18_pt12__41_a16_t0.15_s5_af2pred      93   178    9   0.0000           0     23.67 Å
  orient_255_pt12__18_pt12__41_a19_t0.15_s1_af2pred      93   178    9   0.0000           0     23.49 Å
  orient_255_pt12__18_pt12__41_a20_t0.15_s8_af2pred      93   178    9   0.7672         807      5.64 Å
  orient_255_pt12__18_pt12__41_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     23.93 Å
  orient_255_pt12__18_pt12__41_a2_t0.1_s8_af2pred       93   178    9   0.0000           0     22.80 Å
  orient_255_pt12__18_pt12__41_a9_t0.1_s6_af2pred       93   178    9   0.7506         830      5.71 Å
  orient_255_pt12__18_pt12__42_a1_t0.1_s1_af2pred       93   178    9   0.0783          80     16.19 Å
  orient_255_pt12__18_pt12__42_a1_t0.1_s2_af2pred       93   178    9   0.0199          35     17.75 Å
  orient_255_pt12__18_pt12__42_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     23.16 Å

  orient_255_pt12__18_pt12__42_a1_t0.1_s4_af2pred       93   178    9   0.5661         685      9.32 Å
  orient_255_pt12__18_pt12__42_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     21.87 Å
  orient_255_pt12__18_pt12__42_a1_t0.1_s7_af2pred       93   178    9   0.2938         293     13.60 Å
  orient_255_pt12__18_pt12__42_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     22.17 Å
  orient_255_pt12__18_pt12__42_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     21.62 Å
  orient_255_pt12__18_pt12__45_a10_t0.1_s5_af2pred      93   178    9   0.0000           0     21.10 Å
  orient_255_pt12__18_pt12__45_a11_t0.15_s8_af2pred      93   178    9   0.0000           0     21.49 Å
  orient_255_pt12__18_pt12__45_a13_t0.15_s2_af2pred      93   178    9   0.7132         806      6.52 Å
  orient_255_pt12__18_pt12__45_a2_t0.1_s6_af2pred       93   178    9   0.3132         324     13.18 Å
  orient_255_pt12__18_pt12__45_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.76 Å
  orient_255_pt12__18_pt12__45_a5_t0.1_s8_af2pred       93   178    9   0.8324         818      4.56 Å
  orient_255_pt12__18_pt12__45_a8_t0.1_s8_af2pred       93   178    9   0.0000           0     22.92 Å
  orient_255_pt12__18_pt12__45_a9_t0.1_s8_af2pred       93   178    9   0.1903         177     14.94 Å
  orient_255_pt12__18_pt12__47_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     22.73 Å
  orient_255_pt12__18_pt12__47_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     20.47 Å
  orient_255_pt12__18_pt12__47_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.00 Å
  orient_255_pt12__18_pt12__47_a2_t0.1_s4_af2pred       93   178    9   0.0022          19     18.28 Å
  orient_255_pt12__18_pt12__47_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     21.96 Å
  orient_255_pt12__18_pt12__47_a3_t0.1_s1_af2pred       93   178    9   0.0000           0     21.61 Å
  orient_255_pt12__18_pt12__47_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.26 Å
  orient_255_pt12__18_pt12__47_a4_t0.1_s5_af2pred       93   178    9   0.0000           0     21.90 Å
  orient_255_pt12__18_pt12__52_a10_t0.1_s8_af2pred      93   178    9   0.0000           0     23.39 Å
  orient_255_pt12__18_pt12__52_a12_t0.15_s1_af2pred      93   178    9   0.0000           0     24.72 Å
  orient_255_pt12__18_pt12__52_a16_t0.15_s3_af2pred      93   178    9   0.0000           0     24.20 Å
  orient_255_pt12__18_pt12__52_a17_t0.15_s1_af2pred      93   178    9   0.0000           0     24.19 Å
  orient_255_pt12__18_pt12__52_a4_t0.1_s3_af2pred       93   178    9   0.0000           0     23.69 Å
  orient_255_pt12__18_pt12__52_a5_t0.1_s3_af2pred       93   178    9   0.0000           0     22.84 Å
  orient_255_pt12__18_pt12__52_a6_t0.1_s2_af2pred       93   178    9   0.0000           0     23.98 Å
  orient_255_pt12__18_pt12__52_a8_t0.1_s5_af2pred       93   178    9   0.0000           0     22.26 Å
  orient_255_pt12__18_pt12__53_a1_t0.1_s4_af2pred       93   178    9   0.6738         770      7.48 Å
  orient_255_pt12__18_pt12__53_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     22.73 Å
  orient_255_pt12__18_pt12__53_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     22.60 Å
  orient_255_pt12__18_pt12__53_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     20.83 Å
  orient_255_pt12__18_pt12__53_a2_t0.1_s1_af2pred       93   178    9   0.0018           1     20.43 Å
  orient_255_pt12__18_pt12__53_a2_t0.1_s2_af2pred       93   178    9   0.6634         773      7.48 Å
  orient_255_pt12__18_pt12__53_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     22.64 Å
  orient_255_pt12__18_pt12__53_a2_t0.1_s5_af2pred       93   178    9   0.0019           6     20.01 Å
  orient_255_pt12__18_pt12__54_a1_t0.1_s1_af2pred       93   178    9   0.0019           2     20.10 Å
  orient_255_pt12__18_pt12__54_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     21.26 Å
  orient_255_pt12__18_pt12__54_a1_t0.1_s4_af2pred       93   178    9   0.4307         480     11.65 Å
  orient_255_pt12__18_pt12__54_a1_t0.1_s8_af2pred       93   178    9   0.1741         154     15.36 Å
  orient_255_pt12__18_pt12__54_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.22 Å
  orient_255_pt12__18_pt12__54_a2_t0.1_s2_af2pred       93   178    9   0.0018           2     19.97 Å
  orient_255_pt12__18_pt12__54_a2_t0.1_s6_af2pred       93   178    9   0.6531         773      7.55 Å
  orient_255_pt12__18_pt12__54_a2_t0.1_s8_af2pred       93   178    9   0.6665         794      7.34 Å
  orient_255_pt12__18_pt12__60_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     22.15 Å
  orient_255_pt12__18_pt12__60_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     23.68 Å
  orient_255_pt12__18_pt12__60_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     22.31 Å
  orient_255_pt12__18_pt12__60_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     22.39 Å
  orient_255_pt12__18_pt12__60_a2_t0.1_s1_af2pred       93   178    9   0.6115         751      8.35 Å
  orient_255_pt12__18_pt12__60_a2_t0.1_s4_af2pred       93   178    9   0.4749         542     10.83 Å
  orient_255_pt12__18_pt12__60_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     23.31 Å
  orient_255_pt12__18_pt12__60_a3_t0.1_s1_af2pred       93   178    9   0.5138         614     10.17 Å
  orient_255_pt12__18_pt12__63_a11_t0.15_s4_af2pred      93   178    9   0.6742         776      7.42 Å
  orient_255_pt12__18_pt12__63_a13_t0.15_s3_af2pred      93   178    9   0.0000           0     22.36 Å
  orient_255_pt12__18_pt12__63_a14_t0.15_s5_af2pred      93   178    9   0.0000           0     23.61 Å
  orient_255_pt12__18_pt12__63_a14_t0.15_s6_af2pred      93   178    9   0.7166         821      6.32 Å
  orient_255_pt12__18_pt12__63_a15_t0.15_s3_af2pred      93   178    9   0.0000           0     22.66 Å
  orient_255_pt12__18_pt12__63_a16_t0.15_s2_af2pred      93   178    9   0.4733         580     10.70 Å
  orient_255_pt12__18_pt12__63_a16_t0.15_s3_af2pred      93   178    9   0.0000           0     22.80 Å
  orient_255_pt12__18_pt12__63_a4_t0.1_s6_af2pred       93   178    9   0.0324          44     17.12 Å
  orient_255_pt12__18_pt12__65_a1_t0.1_s3_af2pred       93   178    9   0.1428         128     15.45 Å
  orient_255_pt12__18_pt12__65_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     25.28 Å
  orient_255_pt12__18_pt12__65_a1_t0.1_s5_af2pred       93   178    9   0.2591         234     14.04 Å
  orient_255_pt12__18_pt12__65_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     21.29 Å
  orient_255_pt12__18_pt12__65_a2_t0.1_s1_af2pred       93   178    9   0.0019           2     20.26 Å
  orient_255_pt12__18_pt12__65_a2_t0.1_s2_af2pred       93   178    9   0.6996         778      6.94 Å
  orient_255_pt12__18_pt12__65_a2_t0.1_s3_af2pred       93   178    9   0.4840         561     10.82 Å
  orient_255_pt12__18_pt12__65_a2_t0.1_s4_af2pred       93   178    9   0.6243         756      8.08 Å
  orient_255_pt12__18_pt12__66_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     20.25 Å
  orient_255_pt12__18_pt12__66_a1_t0.1_s2_af2pred       93   178    9   0.7705         803      5.72 Å
  orient_255_pt12__18_pt12__66_a1_t0.1_s3_af2pred       93   178    9   0.7534         807      6.08 Å
  orient_255_pt12__18_pt12__66_a1_t0.1_s4_af2pred       93   178    9   0.8407         827      4.29 Å
  orient_255_pt12__18_pt12__66_a1_t0.1_s5_af2pred       93   178    9   0.5928         695      9.00 Å
  orient_255_pt12__18_pt12__66_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     23.28 Å
  orient_255_pt12__18_pt12__66_a2_t0.1_s3_af2pred       93   178    9   0.5147         608     10.15 Å
  orient_255_pt12__18_pt12__66_a2_t0.1_s4_af2pred       93   178    9   0.7659         807      5.85 Å
  orient_255_pt12__18_pt12__68_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     22.27 Å
  orient_255_pt12__18_pt12__68_a1_t0.1_s2_af2pred       93   178    9   0.4891         595     10.72 Å
  orient_255_pt12__18_pt12__68_a1_t0.1_s4_af2pred       93   178    9   0.0020          12     18.83 Å

  orient_255_pt12__18_pt12__68_a1_t0.1_s5_af2pred       93   178    9   0.0020           5     19.75 Å
  orient_255_pt12__18_pt12__68_a1_t0.1_s7_af2pred       93   178    9   0.6710         784      7.29 Å
  orient_255_pt12__18_pt12__68_a1_t0.1_s8_af2pred       93   178    9   0.6604         784      7.54 Å
  orient_255_pt12__18_pt12__68_a2_t0.1_s1_af2pred       93   178    9   0.7197         819      6.31 Å
  orient_255_pt12__18_pt12__68_a2_t0.1_s2_af2pred       93   178    9   0.7536         818      5.77 Å
  orient_255_pt12__18_pt12__69_a10_t0.1_s6_af2pred      93   178    9   0.4832         570     11.21 Å
  orient_255_pt12__18_pt12__69_a13_t0.15_s2_af2pred      93   178    9   0.7672         806      5.66 Å
  orient_255_pt12__18_pt12__69_a13_t0.15_s3_af2pred      93   178    9   0.0000           0     19.40 Å
  orient_255_pt12__18_pt12__69_a13_t0.15_s7_af2pred      93   178    9   0.7747         820      5.45 Å
  orient_255_pt12__18_pt12__69_a18_t0.15_s8_af2pred      93   178    9   0.8004         813      5.16 Å
  orient_255_pt12__18_pt12__69_a5_t0.1_s6_af2pred       93   178    9   0.5834         702      8.95 Å
  orient_255_pt12__18_pt12__69_a7_t0.1_s8_af2pred       93   178    9   0.6862         787      6.96 Å
  orient_255_pt12__18_pt12__69_a9_t0.1_s7_af2pred       93   178    9   0.7945         811      5.32 Å
  orient_255_pt12__18_pt12__71_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     22.62 Å
  orient_255_pt12__18_pt12__71_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     22.93 Å
  orient_255_pt12__18_pt12__71_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     22.08 Å
  orient_255_pt12__18_pt12__71_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     22.15 Å
  orient_255_pt12__18_pt12__71_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     22.32 Å
  orient_255_pt12__18_pt12__71_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     22.55 Å
  orient_255_pt12__18_pt12__71_a1_t0.1_s7_af2pred       93   178    9   0.1109         102     15.77 Å
  orient_255_pt12__18_pt12__71_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     22.11 Å
  orient_255_pt12__18_pt12__80_a10_t0.1_s5_af2pred      93   178    9   0.7241         804      6.43 Å
  orient_255_pt12__18_pt12__80_a12_t0.15_s1_af2pred      93   178    9   0.0000           0     23.02 Å
  orient_255_pt12__18_pt12__80_a15_t0.15_s4_af2pred      93   178    9   0.0000           0     22.35 Å
  orient_255_pt12__18_pt12__80_a18_t0.15_s8_af2pred      93   178    9   0.0000           0     23.53 Å
  orient_255_pt12__18_pt12__80_a26_t0.2_s7_af2pred      93   178    9   0.3224         328     13.02 Å
  orient_255_pt12__18_pt12__83_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     22.59 Å
  orient_255_pt12__18_pt12__83_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     21.35 Å
  orient_255_pt12__18_pt12__83_a1_t0.1_s7_af2pred       93   178    9   0.7362         806      6.19 Å
  orient_255_pt12__18_pt12__83_a1_t0.1_s8_af2pred       93   178    9   0.2276         205     14.36 Å
  orient_255_pt12__18_pt12__83_a5_t0.1_s4_af2pred       93   178    9   0.0000           0     22.41 Å
  orient_255_pt12__18_pt12__83_a5_t0.1_s5_af2pred       93   178    9   0.0020           9     19.09 Å
  orient_255_pt12__18_pt12__83_a5_t0.1_s6_af2pred       93   178    9   0.0000           0     21.80 Å
  orient_255_pt12__18_pt12__83_a7_t0.1_s6_af2pred       93   178    9   0.0000           0     21.94 Å
  orient_255_pt12__18_pt12__84_a1_t0.1_s1_af2pred       93   178    9   0.8339         834      4.32 Å
  orient_255_pt12__18_pt12__84_a1_t0.1_s5_af2pred       93   178    9   0.6934         786      6.91 Å
  orient_255_pt12__18_pt12__84_a1_t0.1_s7_af2pred       93   178    9   0.7590         794      5.97 Å
  orient_255_pt12__18_pt12__84_a2_t0.1_s1_af2pred       93   178    9   0.8305         825      4.47 Å
  orient_255_pt12__18_pt12__84_a2_t0.1_s8_af2pred       93   178    9   0.7833         804      5.47 Å
  orient_255_pt12__18_pt12__84_a3_t0.1_s2_af2pred       93   178    9   0.7593         808      5.80 Å
  orient_255_pt12__18_pt12__84_a3_t0.1_s3_af2pred       93   178    9   0.3962         451     12.19 Å
  orient_255_pt12__18_pt12__84_a5_t0.1_s8_af2pred       93   178    9   0.7517         800      6.05 Å
  orient_255_pt12__18_pt12__85_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     20.99 Å
  orient_255_pt12__18_pt12__85_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     20.47 Å
  orient_255_pt12__18_pt12__85_a1_t0.1_s7_af2pred       93   178    9   0.3532         375     12.69 Å
  orient_255_pt12__18_pt12__85_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     21.63 Å
  orient_255_pt12__18_pt12__85_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     23.69 Å
  orient_255_pt12__18_pt12__85_a3_t0.1_s4_af2pred       93   178    9   0.0000           0     20.54 Å
  orient_255_pt12__18_pt12__85_a5_t0.1_s1_af2pred       93   178    9   0.0021           2     19.67 Å
  orient_255_pt12__18_pt12__85_a5_t0.1_s4_af2pred       93   178    9   0.6921         789      6.91 Å
  orient_255_pt12__18_pt12__86_a1_t0.1_s1_af2pred       93   178    9   0.7313         803      6.31 Å
  orient_255_pt12__18_pt12__86_a1_t0.1_s2_af2pred       93   178    9   0.0019          11     18.27 Å
  orient_255_pt12__18_pt12__86_a1_t0.1_s3_af2pred       93   178    9   0.0019           5     19.56 Å
  orient_255_pt12__18_pt12__86_a1_t0.1_s5_af2pred       93   178    9   0.7970         815      5.10 Å
  orient_255_pt12__18_pt12__86_a1_t0.1_s6_af2pred       93   178    9   0.6938         800      6.91 Å
  orient_255_pt12__18_pt12__86_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     23.50 Å
  orient_255_pt12__18_pt12__86_a1_t0.1_s8_af2pred       93   178    9   0.7801         824      5.36 Å
  orient_255_pt12__18_pt12__86_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     21.32 Å
  orient_255_pt12__18_pt12__89_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     22.31 Å
  orient_255_pt12__18_pt12__89_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     22.45 Å
  orient_255_pt12__18_pt12__89_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     21.82 Å
  orient_255_pt12__18_pt12__89_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     24.83 Å
  orient_255_pt12__18_pt12__89_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     24.48 Å
  orient_255_pt12__18_pt12__89_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     24.38 Å
  orient_255_pt12__18_pt12__89_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     22.99 Å
  orient_255_pt12__18_pt12__89_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     22.93 Å
  orient_255_pt12__18_pt12__8_a1_t0.1_s1_af2pred        93   178    9   0.6885         793      7.05 Å
  orient_255_pt12__18_pt12__8_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     23.16 Å
  orient_255_pt12__18_pt12__8_a1_t0.1_s7_af2pred        93   178    9   0.1865         162     14.98 Å
  orient_255_pt12__18_pt12__8_a2_t0.1_s1_af2pred        93   178    9   0.1465         130     15.50 Å
  orient_255_pt12__18_pt12__8_a2_t0.1_s3_af2pred        93   178    9   0.0000           0     22.68 Å
  orient_255_pt12__18_pt12__8_a2_t0.1_s7_af2pred        93   178    9   0.6630         757      7.71 Å
  orient_255_pt12__18_pt12__8_a3_t0.1_s1_af2pred        93   178    9   0.0000           0     23.26 Å
  orient_255_pt12__18_pt12__8_a3_t0.1_s2_af2pred        93   178    9   0.0000           0     23.42 Å
  orient_255_pt12__18_pt12__90_a16_t0.15_s3_af2pred      93   178    9   0.7794         831      5.25 Å
  orient_255_pt12__18_pt12__90_a17_t0.15_s4_af2pred      93   178    9   0.0022          10     19.38 Å
  orient_255_pt12__18_pt12__90_a18_t0.15_s4_af2pred      93   178    9   0.6761         730      7.61 Å
  orient_255_pt12__18_pt12__90_a19_t0.15_s5_af2pred      93   178    9   0.2589         241     14.34 Å
  orient_255_pt12__18_pt12__90_a20_t0.15_s3_af2pred      93   178    9   0.8491         804      4.39 Å
  orient_255_pt12__18_pt12__90_a3_t0.1_s7_af2pred       93   178    9   0.8148         833      4.65 Å

  orient_255_pt12__18_pt12__90_a8_t0.1_s7_af2pred       93   178    9   0.8051         794      5.27 Å
  orient_255_pt12__18_pt12__90_a9_t0.1_s8_af2pred       93   178    9   0.8572         806      4.28 Å
  orient_255_pt12__18_pt12__91_a1_t0.1_s1_af2pred       93   178    9   0.7791         820      5.43 Å
  orient_255_pt12__18_pt12__91_a1_t0.1_s3_af2pred       93   178    9   0.8429         824      4.32 Å
  orient_255_pt12__18_pt12__91_a1_t0.1_s4_af2pred       93   178    9   0.8302         821      4.63 Å
  orient_255_pt12__18_pt12__91_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     21.94 Å
  orient_255_pt12__18_pt12__91_a1_t0.1_s6_af2pred       93   178    9   0.7437         815      5.97 Å
  orient_255_pt12__18_pt12__91_a1_t0.1_s7_af2pred       93   178    9   0.6982         793      6.78 Å
  orient_255_pt12__18_pt12__91_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.06 Å
  orient_255_pt12__18_pt12__91_a2_t0.1_s2_af2pred       93   178    9   0.7374         809      6.09 Å
  orient_255_pt12__18_pt12__95_a1_t0.1_s4_af2pred       93   178    9   0.7089         786      6.74 Å
  orient_255_pt12__18_pt12__95_a1_t0.1_s5_af2pred       93   178    9   0.0019           1     22.16 Å
  orient_255_pt12__18_pt12__95_a1_t0.1_s7_af2pred       93   178    9   0.0020           4     19.62 Å
  orient_255_pt12__18_pt12__95_a2_t0.1_s2_af2pred       93   178    9   0.0729          71     16.37 Å
  orient_255_pt12__18_pt12__95_a2_t0.1_s6_af2pred       93   178    9   0.4270         495     11.46 Å
  orient_255_pt12__18_pt12__95_a3_t0.1_s2_af2pred       93   178    9   0.6912         792      6.95 Å
  orient_255_pt12__18_pt12__95_a4_t0.1_s2_af2pred       93   178    9   0.3736         419     12.55 Å
  orient_255_pt12__18_pt12__95_a7_t0.1_s7_af2pred       93   178    9   0.5911         685      9.05 Å
  orient_255_pt12__18_pt12__9_a2_t0.1_s5_af2pred        93   178    9   0.4254         479     11.58 Å
  orient_255_pt12__18_pt12__9_a3_t0.1_s2_af2pred        93   178    9   0.6852         802      6.99 Å
  orient_255_pt12__18_pt12__9_a3_t0.1_s3_af2pred        93   178    9   0.8068         820      4.92 Å
  orient_255_pt12__18_pt12__9_a3_t0.1_s5_af2pred        93   178    9   0.3988         433     12.04 Å
  orient_255_pt12__18_pt12__9_a3_t0.1_s7_af2pred        93   178    9   0.0000           0     21.88 Å
  orient_255_pt12__18_pt12__9_a4_t0.1_s1_af2pred        93   178    9   0.5860         708      8.89 Å
  orient_255_pt12__18_pt12__9_a4_t0.1_s6_af2pred        93   178    9   0.7788         809      5.58 Å
  orient_255_pt12__18_pt12__9_a6_t0.1_s6_af2pred        93   178    9   0.0018           1     20.86 Å
  orient_255_pt12__27_pt25__0_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     23.97 Å
  orient_255_pt12__27_pt25__0_a1_t0.1_s3_af2pred        93   178    9   0.0024           2     19.98 Å
  orient_255_pt12__27_pt25__0_a2_t0.1_s4_af2pred        93   178    9   0.5129         633     10.10 Å
  orient_255_pt12__27_pt25__0_a3_t0.1_s6_af2pred        93   178    9   0.0000           0     23.98 Å
  orient_255_pt12__27_pt25__0_a3_t0.1_s7_af2pred        93   178    9   0.0000           0     22.32 Å
  orient_255_pt12__27_pt25__0_a6_t0.1_s4_af2pred        93   178    9   0.0000           0     24.05 Å
  orient_255_pt12__27_pt25__0_a6_t0.1_s5_af2pred        93   178    9   0.0000           0     24.82 Å
  orient_255_pt12__27_pt25__0_a7_t0.1_s4_af2pred        93   178    9   0.0000           0     25.20 Å
  orient_255_pt12__27_pt25__10_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     23.77 Å
  orient_255_pt12__27_pt25__10_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     20.48 Å
  orient_255_pt12__27_pt25__10_a1_t0.1_s4_af2pred       93   178    9   0.0021           6     20.54 Å
  orient_255_pt12__27_pt25__10_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     22.52 Å
  orient_255_pt12__27_pt25__10_a2_t0.1_s1_af2pred       93   178    9   0.0017           1     21.16 Å
  orient_255_pt12__27_pt25__10_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     23.11 Å
  orient_255_pt12__27_pt25__10_a3_t0.1_s2_af2pred       93   178    9   0.0020           6     19.77 Å
  orient_255_pt12__27_pt25__10_a4_t0.1_s5_af2pred       93   178    9   0.0376          46     17.28 Å
  orient_255_pt12__27_pt25__11_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     23.49 Å
  orient_255_pt12__27_pt25__11_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     23.18 Å
  orient_255_pt12__27_pt25__11_a4_t0.1_s2_af2pred       93   178    9   0.0000           0     23.56 Å
  orient_255_pt12__27_pt25__11_a4_t0.1_s5_af2pred       93   178    9   0.0000           0     23.90 Å
  orient_255_pt12__27_pt25__11_a6_t0.1_s2_af2pred       93   178    9   0.0000           0     23.18 Å
  orient_255_pt12__27_pt25__11_a6_t0.1_s6_af2pred       93   178    9   0.0000           0     23.63 Å
  orient_255_pt12__27_pt25__11_a6_t0.1_s7_af2pred       93   178    9   0.0000           0     25.73 Å
  orient_255_pt12__27_pt25__11_a7_t0.1_s1_af2pred       93   178    9   0.0000           0     25.13 Å
  orient_255_pt12__27_pt25__15_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     24.04 Å
  orient_255_pt12__27_pt25__15_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     24.57 Å
  orient_255_pt12__27_pt25__15_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     23.85 Å
  orient_255_pt12__27_pt25__15_a4_t0.1_s1_af2pred       93   178    9   0.0000           0     23.77 Å
  orient_255_pt12__27_pt25__15_a4_t0.1_s8_af2pred       93   178    9   0.0000           0     23.66 Å
  orient_255_pt12__27_pt25__15_a5_t0.1_s1_af2pred       93   178    9   0.0000           0     23.75 Å
  orient_255_pt12__27_pt25__15_a5_t0.1_s2_af2pred       93   178    9   0.0000           0     23.22 Å
  orient_255_pt12__27_pt25__15_a7_t0.1_s6_af2pred       93   178    9   0.0000           0     25.52 Å
  orient_255_pt12__27_pt25__17_a11_t0.15_s3_af2pred      93   178    9   0.0000           0     21.85 Å
  orient_255_pt12__27_pt25__17_a1_t0.1_s2_af2pred       93   178    9   0.0570          60     16.13 Å
  orient_255_pt12__27_pt25__17_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     21.17 Å
  orient_255_pt12__27_pt25__17_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.38 Å
  orient_255_pt12__27_pt25__17_a4_t0.1_s2_af2pred       93   178    9   0.0019           4     19.66 Å
  orient_255_pt12__27_pt25__17_a5_t0.1_s3_af2pred       93   178    9   0.0000           0     23.50 Å
  orient_255_pt12__27_pt25__17_a6_t0.1_s4_af2pred       93   178    9   0.0000           0     24.27 Å
  orient_255_pt12__27_pt25__17_a9_t0.1_s6_af2pred       93   178    9   0.0000           0     26.07 Å
  orient_255_pt12__27_pt25__20_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     23.79 Å
  orient_255_pt12__27_pt25__20_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     22.95 Å
  orient_255_pt12__27_pt25__20_a3_t0.1_s2_af2pred       93   178    9   0.0000           0     23.55 Å
  orient_255_pt12__27_pt25__20_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     23.95 Å
  orient_255_pt12__27_pt25__20_a3_t0.1_s5_af2pred       93   178    9   0.0000           0     23.75 Å
  orient_255_pt12__27_pt25__20_a4_t0.1_s2_af2pred       93   178    9   0.0020           7     18.97 Å
  orient_255_pt12__27_pt25__20_a4_t0.1_s7_af2pred       93   178    9   0.0000           0     22.69 Å
  orient_255_pt12__27_pt25__20_a6_t0.1_s2_af2pred       93   178    9   0.0000           0     23.38 Å
  orient_255_pt12__27_pt25__22_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     25.26 Å
  orient_255_pt12__27_pt25__22_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     23.53 Å
  orient_255_pt12__27_pt25__22_a1_t0.1_s6_af2pred       93   178    9   0.0020           6     19.86 Å
  orient_255_pt12__27_pt25__22_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     25.80 Å
  orient_255_pt12__27_pt25__22_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     24.97 Å
  orient_255_pt12__27_pt25__22_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     26.57 Å
  orient_255_pt12__27_pt25__22_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     26.51 Å
  orient_255_pt12__27_pt25__22_a3_t0.1_s4_af2pred       93   178    9   0.0000           0     25.64 Å
  orient_255_pt12__27_pt25__24_a10_t0.1_s8_af2pred      93   178    9   0.0000           0     22.60 Å

  orient_255_pt12__27_pt25__24_a11_t0.15_s2_af2pred      93   178    9   0.0000           0     22.88 Å
  orient_255_pt12__27_pt25__24_a11_t0.15_s3_af2pred      93   178    9   0.0000           0     22.18 Å
  orient_255_pt12__27_pt25__24_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     19.24 Å
  orient_255_pt12__27_pt25__24_a2_t0.1_s7_af2pred       93   178    9   0.0018           1     20.11 Å
  orient_255_pt12__27_pt25__24_a6_t0.1_s3_af2pred       93   178    9   0.0000           0     20.36 Å
  orient_255_pt12__27_pt25__24_a7_t0.1_s5_af2pred       93   178    9   0.0000           0     22.58 Å
  orient_255_pt12__27_pt25__24_a9_t0.1_s3_af2pred       93   178    9   0.0000           0     22.01 Å
  orient_255_pt12__27_pt25__29_a1_t0.1_s5_af2pred       93   178    9   0.0020           4     20.98 Å
  orient_255_pt12__27_pt25__29_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     21.87 Å
  orient_255_pt12__27_pt25__29_a2_t0.1_s3_af2pred       93   178    9   0.0024           9     19.06 Å
  orient_255_pt12__27_pt25__29_a2_t0.1_s6_af2pred       93   178    9   0.0019           3     20.22 Å
  orient_255_pt12__27_pt25__29_a2_t0.1_s7_af2pred       93   178    9   0.0024           9     19.05 Å
  orient_255_pt12__27_pt25__29_a2_t0.1_s8_af2pred       93   178    9   0.0022          20     17.63 Å
  orient_255_pt12__27_pt25__29_a3_t0.1_s1_af2pred       93   178    9   0.0000           0     23.59 Å
  orient_255_pt12__27_pt25__29_a3_t0.1_s3_af2pred       93   178    9   0.6380         750      7.96 Å
  orient_255_pt12__27_pt25__30_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     22.53 Å
  orient_255_pt12__27_pt25__30_a1_t0.1_s4_af2pred       93   178    9   0.0019           1     19.14 Å
  orient_255_pt12__27_pt25__30_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     25.29 Å
  orient_255_pt12__27_pt25__30_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     24.29 Å
  orient_255_pt12__27_pt25__30_a2_t0.1_s4_af2pred       93   178    9   0.0018           1     21.05 Å
  orient_255_pt12__27_pt25__30_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     23.42 Å
  orient_255_pt12__27_pt25__30_a2_t0.1_s7_af2pred       93   178    9   0.0022          12     18.86 Å
  orient_255_pt12__27_pt25__30_a3_t0.1_s1_af2pred       93   178    9   0.0000           0     24.32 Å
  orient_255_pt12__27_pt25__32_a16_t0.15_s2_af2pred      93   178    9   0.0000           0     22.62 Å
  orient_255_pt12__27_pt25__32_a20_t0.15_s1_af2pred      93   178    9   0.0000           0     23.79 Å
  orient_255_pt12__27_pt25__32_a25_t0.2_s8_af2pred      93   178    9   0.0000           0     24.55 Å
  orient_255_pt12__27_pt25__32_a26_t0.2_s5_af2pred      93   178    9   0.0000           0     27.63 Å
  orient_255_pt12__27_pt25__32_a6_t0.1_s3_af2pred       93   178    9   0.0000           0     23.20 Å
  orient_255_pt12__27_pt25__36_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     21.93 Å
  orient_255_pt12__27_pt25__36_a1_t0.1_s3_af2pred       93   178    9   0.0022          12     18.65 Å
  orient_255_pt12__27_pt25__36_a1_t0.1_s6_af2pred       93   178    9   0.4839         601     10.69 Å
  orient_255_pt12__27_pt25__36_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     22.55 Å
  orient_255_pt12__27_pt25__36_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     21.12 Å
  orient_255_pt12__27_pt25__36_a2_t0.1_s2_af2pred       93   178    9   0.0018           1     20.54 Å
  orient_255_pt12__27_pt25__36_a2_t0.1_s3_af2pred       93   178    9   0.3001         310     13.25 Å
  orient_255_pt12__27_pt25__36_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     21.48 Å
  orient_255_pt12__27_pt25__37_a1_t0.1_s2_af2pred       93   178    9   0.0019           6     20.60 Å
  orient_255_pt12__27_pt25__37_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     23.42 Å
  orient_255_pt12__27_pt25__37_a1_t0.1_s4_af2pred       93   178    9   0.0912          85     16.47 Å
  orient_255_pt12__27_pt25__37_a1_t0.1_s5_af2pred       93   178    9   0.5590         676      9.59 Å
  orient_255_pt12__27_pt25__37_a1_t0.1_s7_af2pred       93   178    9   0.5278         635     10.04 Å
  orient_255_pt12__27_pt25__37_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.39 Å
  orient_255_pt12__27_pt25__37_a2_t0.1_s2_af2pred       93   178    9   0.7289         768      6.64 Å
  orient_255_pt12__27_pt25__37_a2_t0.1_s3_af2pred       93   178    9   0.0018           5     20.11 Å
  orient_255_pt12__27_pt25__38_a12_t0.15_s2_af2pred      93   178    9   0.0000           0     24.72 Å
  orient_255_pt12__27_pt25__38_a12_t0.15_s3_af2pred      93   178    9   0.0000           0     22.53 Å
  orient_255_pt12__27_pt25__38_a13_t0.15_s2_af2pred      93   178    9   0.0000           0     22.30 Å
  orient_255_pt12__27_pt25__38_a4_t0.1_s2_af2pred       93   178    9   0.0000           0     26.06 Å
  orient_255_pt12__27_pt25__38_a5_t0.1_s2_af2pred       93   178    9   0.0000           0     25.21 Å
  orient_255_pt12__27_pt25__38_a6_t0.1_s3_af2pred       93   178    9   0.0000           0     25.73 Å
  orient_255_pt12__27_pt25__38_a9_t0.1_s1_af2pred       93   178    9   0.0000           0     23.30 Å
  orient_255_pt12__27_pt25__38_a9_t0.1_s2_af2pred       93   178    9   0.0000           0     24.42 Å
  orient_255_pt12__27_pt25__39_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     23.23 Å
  orient_255_pt12__27_pt25__39_a5_t0.1_s5_af2pred       93   178    9   0.0000           0     23.02 Å
  orient_255_pt12__27_pt25__39_a6_t0.1_s5_af2pred       93   178    9   0.0000           0     22.16 Å
  orient_255_pt12__27_pt25__39_a6_t0.1_s7_af2pred       93   178    9   0.0000           0     21.61 Å
  orient_255_pt12__27_pt25__39_a6_t0.1_s8_af2pred       93   178    9   0.0000           0     22.01 Å
  orient_255_pt12__27_pt25__39_a7_t0.1_s4_af2pred       93   178    9   0.0000           0     21.12 Å
  orient_255_pt12__27_pt25__39_a8_t0.1_s5_af2pred       93   178    9   0.0000           0     23.07 Å
  orient_255_pt12__27_pt25__39_a9_t0.1_s4_af2pred       93   178    9   0.0000           0     21.74 Å
  orient_255_pt12__27_pt25__41_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     23.07 Å
  orient_255_pt12__27_pt25__41_a2_t0.1_s4_af2pred       93   178    9   0.0019           1     21.08 Å
  orient_255_pt12__27_pt25__41_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     23.88 Å
  orient_255_pt12__27_pt25__41_a3_t0.1_s1_af2pred       93   178    9   0.0000           0     22.86 Å
  orient_255_pt12__27_pt25__41_a4_t0.1_s3_af2pred       93   178    9   0.0000           0     22.30 Å
  orient_255_pt12__27_pt25__41_a4_t0.1_s5_af2pred       93   178    9   0.0000           0     22.76 Å
  orient_255_pt12__27_pt25__41_a5_t0.1_s1_af2pred       93   178    9   0.0000           0     22.65 Å
  orient_255_pt12__27_pt25__41_a5_t0.1_s2_af2pred       93   178    9   0.0000           0     21.96 Å
  orient_255_pt12__27_pt25__42_a1_t0.1_s1_af2pred       93   178    9   0.0020           2     21.43 Å
  orient_255_pt12__27_pt25__42_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.32 Å
  orient_255_pt12__27_pt25__42_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     21.64 Å
  orient_255_pt12__27_pt25__42_a3_t0.1_s1_af2pred       93   178    9   0.0000           0     22.81 Å
  orient_255_pt12__27_pt25__42_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.75 Å
  orient_255_pt12__27_pt25__42_a4_t0.1_s1_af2pred       93   178    9   0.0000           0     24.63 Å
  orient_255_pt12__27_pt25__42_a4_t0.1_s3_af2pred       93   178    9   0.0000           0     21.82 Å
  orient_255_pt12__27_pt25__42_a4_t0.1_s5_af2pred       93   178    9   0.0000           0     23.59 Å
  orient_255_pt12__27_pt25__44_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     23.31 Å
  orient_255_pt12__27_pt25__44_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     23.18 Å
  orient_255_pt12__27_pt25__44_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     25.15 Å
  orient_255_pt12__27_pt25__44_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     22.76 Å
  orient_255_pt12__27_pt25__44_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     23.39 Å
  orient_255_pt12__27_pt25__44_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     23.18 Å
  orient_255_pt12__27_pt25__44_a2_t0.1_s8_af2pred       93   178    9   0.0000           0     22.30 Å
  orient_255_pt12__27_pt25__44_a3_t0.1_s2_af2pred       93   178    9   0.0000           0     23.37 Å

  orient_255_pt12__27_pt25__48_a1_t0.1_s1_af2pred       93   178    9   0.5436         638     10.03 Å
  orient_255_pt12__27_pt25__48_a1_t0.1_s2_af2pred       93   178    9   0.3210         322     13.39 Å
  orient_255_pt12__27_pt25__48_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     22.25 Å
  orient_255_pt12__27_pt25__48_a1_t0.1_s6_af2pred       93   178    9   0.0025           1     20.46 Å
  orient_255_pt12__27_pt25__48_a1_t0.1_s7_af2pred       93   178    9   0.2997         303     13.86 Å
  orient_255_pt12__27_pt25__48_a1_t0.1_s8_af2pred       93   178    9   0.1881         163     15.13 Å
  orient_255_pt12__27_pt25__48_a2_t0.1_s1_af2pred       93   178    9   0.5317         613     10.47 Å
  orient_255_pt12__27_pt25__48_a2_t0.1_s3_af2pred       93   178    9   0.1742         155     15.36 Å
  orient_255_pt12__27_pt25__4_a10_t0.1_s2_af2pred       93   178    9   0.1259         125     15.10 Å
  orient_255_pt12__27_pt25__4_a11_t0.15_s1_af2pred      93   178    9   0.0000           0     24.46 Å
  orient_255_pt12__27_pt25__4_a12_t0.15_s4_af2pred      93   178    9   0.0000           0     19.72 Å
  orient_255_pt12__27_pt25__4_a13_t0.15_s3_af2pred      93   178    9   0.0000           0     19.45 Å
  orient_255_pt12__27_pt25__4_a14_t0.15_s5_af2pred      93   178    9   0.0000           0     23.88 Å
  orient_255_pt12__27_pt25__4_a4_t0.1_s6_af2pred        93   178    9   0.0000           0     22.06 Å
  orient_255_pt12__27_pt25__4_a8_t0.1_s8_af2pred        93   178    9   0.3578         402     12.89 Å
  orient_255_pt12__27_pt25__4_a9_t0.1_s2_af2pred        93   178    9   0.0000           0     23.52 Å
  orient_255_pt12__27_pt25__7_a11_t0.15_s6_af2pred      93   178    9   0.0000           0     23.40 Å
  orient_255_pt12__27_pt25__7_a13_t0.15_s4_af2pred      93   178    9   0.0020           8     18.77 Å
  orient_255_pt12__27_pt25__7_a16_t0.15_s2_af2pred      93   178    9   0.0000           0     26.01 Å
  orient_255_pt12__27_pt25__7_a16_t0.15_s5_af2pred      93   178    9   0.0000           0     23.22 Å
  orient_255_pt12__27_pt25__7_a2_t0.1_s4_af2pred        93   178    9   0.0000           0     27.11 Å
  orient_255_pt12__27_pt25__7_a2_t0.1_s7_af2pred        93   178    9   0.0000           0     25.53 Å
  orient_255_pt12__27_pt25__7_a3_t0.1_s3_af2pred        93   178    9   0.0000           0     24.24 Å
  orient_255_pt12__27_pt25__7_a5_t0.1_s1_af2pred        93   178    9   0.0000           0     23.83 Å
  orient_255_pt12__2_pt12__12_a1_t0.1_s1_af2pred        93   178    9   0.7597         805      5.82 Å
  orient_255_pt12__2_pt12__12_a1_t0.1_s3_af2pred        93   178    9   0.5050         584     10.70 Å
  orient_255_pt12__2_pt12__12_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     22.36 Å
  orient_255_pt12__2_pt12__12_a1_t0.1_s7_af2pred        93   178    9   0.8607         824      3.97 Å
  orient_255_pt12__2_pt12__12_a1_t0.1_s8_af2pred        93   178    9   0.6922         781      7.05 Å
  orient_255_pt12__2_pt12__12_a2_t0.1_s1_af2pred        93   178    9   0.0927          85     16.34 Å
  orient_255_pt12__2_pt12__12_a2_t0.1_s2_af2pred        93   178    9   0.7714         810      5.59 Å
  orient_255_pt12__2_pt12__12_a2_t0.1_s4_af2pred        93   178    9   0.6644         754      7.65 Å
  orient_255_pt12__2_pt12__13_a1_t0.1_s2_af2pred        93   178    9   0.8078         831      4.76 Å
  orient_255_pt12__2_pt12__13_a1_t0.1_s4_af2pred        93   178    9   0.0474          53     17.34 Å
  orient_255_pt12__2_pt12__13_a1_t0.1_s5_af2pred        93   178    9   0.7516         826      5.75 Å
  orient_255_pt12__2_pt12__13_a1_t0.1_s7_af2pred        93   178    9   0.8080         828      4.80 Å
  orient_255_pt12__2_pt12__13_a1_t0.1_s8_af2pred        93   178    9   0.0312          42     17.36 Å
  orient_255_pt12__2_pt12__13_a2_t0.1_s1_af2pred        93   178    9   0.8541         837      3.95 Å
  orient_255_pt12__2_pt12__13_a2_t0.1_s2_af2pred        93   178    9   0.8450         837      4.10 Å
  orient_255_pt12__2_pt12__13_a2_t0.1_s3_af2pred        93   178    9   0.8693         837      3.70 Å
  orient_255_pt12__2_pt12__15_a10_t0.1_s2_af2pred       93   178    9   0.7325         756      6.68 Å
  orient_255_pt12__2_pt12__15_a10_t0.1_s3_af2pred       93   178    9   0.3291         344     13.36 Å
  orient_255_pt12__2_pt12__15_a1_t0.1_s8_af2pred        93   178    9   0.4015         435     12.29 Å
  orient_255_pt12__2_pt12__15_a2_t0.1_s4_af2pred        93   178    9   0.6037         677      8.87 Å
  orient_255_pt12__2_pt12__15_a3_t0.1_s4_af2pred        93   178    9   0.0000           0     22.99 Å
  orient_255_pt12__2_pt12__15_a5_t0.1_s3_af2pred        93   178    9   0.1433         127     15.78 Å
  orient_255_pt12__2_pt12__15_a6_t0.1_s2_af2pred        93   178    9   0.6327         707      8.56 Å
  orient_255_pt12__2_pt12__15_a7_t0.1_s8_af2pred        93   178    9   0.0000           0     22.90 Å
  orient_255_pt12__2_pt12__16_a10_t0.1_s8_af2pred       93   178    9   0.6916         789      6.91 Å
  orient_255_pt12__2_pt12__16_a11_t0.15_s5_af2pred      93   178    9   0.0000           0     22.58 Å
  orient_255_pt12__2_pt12__16_a17_t0.15_s5_af2pred      93   178    9   0.5615         656      9.60 Å
  orient_255_pt12__2_pt12__16_a1_t0.1_s4_af2pred        93   178    9   0.7649         827      5.50 Å
  orient_255_pt12__2_pt12__16_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     21.98 Å
  orient_255_pt12__2_pt12__16_a1_t0.1_s7_af2pred        93   178    9   0.0000           0     21.43 Å
  orient_255_pt12__2_pt12__16_a6_t0.1_s2_af2pred        93   178    9   0.0000           0     22.61 Å
  orient_255_pt12__2_pt12__16_a6_t0.1_s8_af2pred        93   178    9   0.3076         295     13.45 Å
  orient_255_pt12__2_pt12__17_a1_t0.1_s5_af2pred        93   178    9   0.0018           1     21.37 Å
  orient_255_pt12__2_pt12__17_a1_t0.1_s7_af2pred        93   178    9   0.7926         806      5.41 Å
  orient_255_pt12__2_pt12__17_a1_t0.1_s8_af2pred        93   178    9   0.6554         779      7.48 Å
  orient_255_pt12__2_pt12__17_a2_t0.1_s1_af2pred        93   178    9   0.8059         825      4.92 Å
  orient_255_pt12__2_pt12__17_a2_t0.1_s4_af2pred        93   178    9   0.6032         745      8.44 Å
  orient_255_pt12__2_pt12__17_a2_t0.1_s7_af2pred        93   178    9   0.0000           0     21.31 Å
  orient_255_pt12__2_pt12__17_a3_t0.1_s2_af2pred        93   178    9   0.0060          25     17.48 Å
  orient_255_pt12__2_pt12__17_a3_t0.1_s7_af2pred        93   178    9   0.1711         152     14.95 Å
  orient_255_pt12__2_pt12__18_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     23.70 Å
  orient_255_pt12__2_pt12__18_a1_t0.1_s3_af2pred        93   178    9   0.7352         817      6.09 Å
  orient_255_pt12__2_pt12__18_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     26.04 Å
  orient_255_pt12__2_pt12__18_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     23.70 Å
  orient_255_pt12__2_pt12__18_a1_t0.1_s6_af2pred        93   178    9   0.0063          25     18.29 Å
  orient_255_pt12__2_pt12__18_a2_t0.1_s4_af2pred        93   178    9   0.4967         541     11.04 Å
  orient_255_pt12__2_pt12__18_a2_t0.1_s6_af2pred        93   178    9   0.8234         833      4.51 Å
  orient_255_pt12__2_pt12__18_a2_t0.1_s8_af2pred        93   178    9   0.7705         811      5.63 Å
  orient_255_pt12__2_pt12__19_a1_t0.1_s1_af2pred        93   178    9   0.5698         679      9.37 Å
  orient_255_pt12__2_pt12__19_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     22.57 Å
  orient_255_pt12__2_pt12__19_a1_t0.1_s5_af2pred        93   178    9   0.6797         760      7.48 Å
  orient_255_pt12__2_pt12__19_a2_t0.1_s1_af2pred        93   178    9   0.0019           2     20.57 Å
  orient_255_pt12__2_pt12__19_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     22.95 Å
  orient_255_pt12__2_pt12__19_a2_t0.1_s4_af2pred        93   178    9   0.5069         582     10.54 Å
  orient_255_pt12__2_pt12__19_a2_t0.1_s6_af2pred        93   178    9   0.0449          51     17.43 Å
  orient_255_pt12__2_pt12__19_a2_t0.1_s8_af2pred        93   178    9   0.6223         741      8.25 Å
  orient_255_pt12__2_pt12__1_a11_t0.15_s5_af2pred       93   178    9   0.6932         811      6.74 Å
  orient_255_pt12__2_pt12__1_a2_t0.1_s4_af2pred         93   178    9   0.3672         394     12.56 Å
  orient_255_pt12__2_pt12__1_a3_t0.1_s4_af2pred         93   178    9   0.0000           0     22.90 Å
  orient_255_pt12__2_pt12__1_a5_t0.1_s3_af2pred         93   178    9   0.0000           0     22.54 Å

  orient_255_pt12__2_pt12__1_a6_t0.1_s3_af2pred         93   178    9   0.7215         805      6.36 Å
  orient_255_pt12__2_pt12__1_a8_t0.1_s5_af2pred         93   178    9   0.0000           0     22.23 Å
  orient_255_pt12__2_pt12__1_a9_t0.1_s6_af2pred         93   178    9   0.0000           0     25.18 Å
  orient_255_pt12__2_pt12__1_a9_t0.1_s8_af2pred         93   178    9   0.0030           2     20.23 Å
  orient_255_pt12__2_pt12__21_a1_t0.1_s1_af2pred        93   178    9   0.0021           3     19.32 Å
  orient_255_pt12__2_pt12__21_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     20.20 Å
  orient_255_pt12__2_pt12__21_a1_t0.1_s4_af2pred        93   178    9   0.0020           6     18.57 Å
  orient_255_pt12__2_pt12__21_a1_t0.1_s6_af2pred        93   178    9   0.0000           0     25.33 Å
  orient_255_pt12__2_pt12__21_a1_t0.1_s8_af2pred        93   178    9   0.3141         328     13.15 Å
  orient_255_pt12__2_pt12__21_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     21.82 Å
  orient_255_pt12__2_pt12__21_a2_t0.1_s6_af2pred        93   178    9   0.0021           7     19.48 Å
  orient_255_pt12__2_pt12__21_a2_t0.1_s7_af2pred        93   178    9   0.0019           2     19.11 Å
  orient_255_pt12__2_pt12__22_a1_t0.1_s1_af2pred        93   178    9   0.7167         795      6.53 Å
  orient_255_pt12__2_pt12__22_a1_t0.1_s3_af2pred        93   178    9   0.0020           8     19.27 Å
  orient_255_pt12__2_pt12__22_a1_t0.1_s4_af2pred        93   178    9   0.7904         804      5.36 Å
  orient_255_pt12__2_pt12__22_a1_t0.1_s7_af2pred        93   178    9   0.7295         786      6.41 Å
  orient_255_pt12__2_pt12__22_a1_t0.1_s8_af2pred        93   178    9   0.8075         826      4.83 Å
  orient_255_pt12__2_pt12__22_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     20.62 Å
  orient_255_pt12__2_pt12__22_a2_t0.1_s2_af2pred        93   178    9   0.6022         700      8.75 Å
  orient_255_pt12__2_pt12__22_a3_t0.1_s1_af2pred        93   178    9   0.5655         659      9.45 Å
  orient_255_pt12__2_pt12__25_a1_t0.1_s1_af2pred        93   178    9   0.6259         737      8.40 Å
  orient_255_pt12__2_pt12__25_a1_t0.1_s5_af2pred        93   178    9   0.0020          12     19.40 Å
  orient_255_pt12__2_pt12__25_a1_t0.1_s8_af2pred        93   178    9   0.0022          14     18.28 Å
  orient_255_pt12__2_pt12__25_a2_t0.1_s1_af2pred        93   178    9   0.2975         288     13.52 Å
  orient_255_pt12__2_pt12__25_a2_t0.1_s8_af2pred        93   178    9   0.5330         663      9.78 Å
  orient_255_pt12__2_pt12__25_a3_t0.1_s2_af2pred        93   178    9   0.0076          26     18.47 Å
  orient_255_pt12__2_pt12__25_a3_t0.1_s3_af2pred        93   178    9   0.5112         601     10.39 Å
  orient_255_pt12__2_pt12__25_a3_t0.1_s8_af2pred        93   178    9   0.7134         787      6.67 Å
  orient_255_pt12__2_pt12__26_a1_t0.1_s2_af2pred        93   178    9   0.6828         767      7.24 Å
  orient_255_pt12__2_pt12__26_a1_t0.1_s4_af2pred        93   178    9   0.1732         150     15.18 Å
  orient_255_pt12__2_pt12__26_a1_t0.1_s6_af2pred        93   178    9   0.6905         750      7.31 Å
  orient_255_pt12__2_pt12__26_a1_t0.1_s7_af2pred        93   178    9   0.6926         774      7.09 Å
  orient_255_pt12__2_pt12__26_a1_t0.1_s8_af2pred        93   178    9   0.6155         726      8.53 Å
  orient_255_pt12__2_pt12__26_a2_t0.1_s6_af2pred        93   178    9   0.7021         804      6.65 Å
  orient_255_pt12__2_pt12__26_a3_t0.1_s1_af2pred        93   178    9   0.7233         785      6.45 Å
  orient_255_pt12__2_pt12__26_a3_t0.1_s3_af2pred        93   178    9   0.7258         784      6.46 Å
  orient_255_pt12__2_pt12__28_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     23.03 Å
  orient_255_pt12__2_pt12__28_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     22.89 Å
  orient_255_pt12__2_pt12__28_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     23.26 Å
  orient_255_pt12__2_pt12__28_a1_t0.1_s6_af2pred        93   178    9   0.0000           0     22.19 Å
  orient_255_pt12__2_pt12__28_a1_t0.1_s8_af2pred        93   178    9   0.0000           0     22.39 Å
  orient_255_pt12__2_pt12__28_a2_t0.1_s3_af2pred        93   178    9   0.0000           0     20.75 Å
  orient_255_pt12__2_pt12__28_a2_t0.1_s4_af2pred        93   178    9   0.6004         701      8.64 Å
  orient_255_pt12__2_pt12__28_a2_t0.1_s6_af2pred        93   178    9   0.0094          27     17.86 Å
  orient_255_pt12__2_pt12__29_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     22.40 Å
  orient_255_pt12__2_pt12__29_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     20.85 Å
  orient_255_pt12__2_pt12__29_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     23.01 Å
  orient_255_pt12__2_pt12__29_a1_t0.1_s6_af2pred        93   178    9   0.0346          42     17.59 Å
  orient_255_pt12__2_pt12__29_a1_t0.1_s8_af2pred        93   178    9   0.7384         798      6.18 Å
  orient_255_pt12__2_pt12__29_a2_t0.1_s1_af2pred        93   178    9   0.7210         812      6.34 Å
  orient_255_pt12__2_pt12__29_a2_t0.1_s2_af2pred        93   178    9   0.2704         277     13.81 Å
  orient_255_pt12__2_pt12__29_a2_t0.1_s7_af2pred        93   178    9   0.0020           3     20.57 Å
  orient_255_pt12__2_pt12__30_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     21.40 Å
  orient_255_pt12__2_pt12__30_a1_t0.1_s8_af2pred        93   178    9   0.2056         179     15.01 Å
  orient_255_pt12__2_pt12__30_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     22.44 Å
  orient_255_pt12__2_pt12__30_a2_t0.1_s5_af2pred        93   178    9   0.3207         324     13.16 Å
  orient_255_pt12__2_pt12__30_a2_t0.1_s6_af2pred        93   178    9   0.5701         670      9.22 Å
  orient_255_pt12__2_pt12__30_a3_t0.1_s1_af2pred        93   178    9   0.8188         827      4.63 Å
  orient_255_pt12__2_pt12__30_a3_t0.1_s8_af2pred        93   178    9   0.0020           1     22.31 Å
  orient_255_pt12__2_pt12__30_a4_t0.1_s3_af2pred        93   178    9   0.0969          90     16.57 Å
  orient_255_pt12__2_pt12__32_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     22.53 Å
  orient_255_pt12__2_pt12__32_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     21.31 Å
  orient_255_pt12__2_pt12__32_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     22.90 Å
  orient_255_pt12__2_pt12__32_a1_t0.1_s7_af2pred        93   178    9   0.7029         774      7.01 Å
  orient_255_pt12__2_pt12__32_a1_t0.1_s8_af2pred        93   178    9   0.3271         331     13.08 Å
  orient_255_pt12__2_pt12__32_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     22.05 Å
  orient_255_pt12__2_pt12__32_a2_t0.1_s4_af2pred        93   178    9   0.0000           0     22.14 Å
  orient_255_pt12__2_pt12__32_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     22.41 Å
  orient_255_pt12__2_pt12__33_a1_t0.1_s2_af2pred        93   178    9   0.2627         256     14.31 Å
  orient_255_pt12__2_pt12__33_a1_t0.1_s3_af2pred        93   178    9   0.0021          14     18.93 Å
  orient_255_pt12__2_pt12__33_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     21.44 Å
  orient_255_pt12__2_pt12__33_a1_t0.1_s6_af2pred        93   178    9   0.0876          81     16.87 Å
  orient_255_pt12__2_pt12__33_a1_t0.1_s7_af2pred        93   178    9   0.8108         832      4.71 Å
  orient_255_pt12__2_pt12__33_a2_t0.1_s2_af2pred        93   178    9   0.7120         790      6.56 Å
  orient_255_pt12__2_pt12__33_a2_t0.1_s4_af2pred        93   178    9   0.7893         837      5.04 Å
  orient_255_pt12__2_pt12__33_a2_t0.1_s8_af2pred        93   178    9   0.7155         810      6.39 Å
  orient_255_pt12__2_pt12__35_a13_t0.15_s7_af2pred      93   178    9   0.0000           0     24.32 Å
  orient_255_pt12__2_pt12__35_a21_t0.2_s2_af2pred       93   178    9   0.0000           0     22.94 Å
  orient_255_pt12__2_pt12__35_a28_t0.2_s2_af2pred       93   178    9   0.0000           0     22.99 Å
  orient_255_pt12__2_pt12__35_a28_t0.2_s3_af2pred       93   178    9   0.0000           0     22.69 Å
  orient_255_pt12__2_pt12__37_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     23.63 Å
  orient_255_pt12__2_pt12__37_a1_t0.1_s7_af2pred        93   178    9   0.0024           7     20.41 Å
  orient_255_pt12__2_pt12__37_a5_t0.1_s3_af2pred        93   178    9   0.1228         113     15.98 Å
  orient_255_pt12__2_pt12__37_a5_t0.1_s8_af2pred        93   178    9   0.7785         801      5.54 Å

  orient_255_pt12__2_pt12__37_a7_t0.1_s2_af2pred        93   178    9   0.0017           1     21.50 Å
  orient_255_pt12__2_pt12__37_a8_t0.1_s1_af2pred        93   178    9   0.6812         777      7.25 Å
  orient_255_pt12__2_pt12__37_a8_t0.1_s3_af2pred        93   178    9   0.0000           0     25.34 Å
  orient_255_pt12__2_pt12__37_a9_t0.1_s7_af2pred        93   178    9   0.7531         776      6.36 Å
  orient_255_pt12__2_pt12__39_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     23.19 Å
  orient_255_pt12__2_pt12__39_a1_t0.1_s6_af2pred        93   178    9   0.0000           0     22.08 Å
  orient_255_pt12__2_pt12__39_a1_t0.1_s8_af2pred        93   178    9   0.0768          74     16.39 Å
  orient_255_pt12__2_pt12__39_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     22.29 Å
  orient_255_pt12__2_pt12__39_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     22.24 Å
  orient_255_pt12__2_pt12__39_a2_t0.1_s7_af2pred        93   178    9   0.0000           0     22.89 Å
  orient_255_pt12__2_pt12__39_a2_t0.1_s8_af2pred        93   178    9   0.0000           0     21.37 Å
  orient_255_pt12__2_pt12__39_a3_t0.1_s4_af2pred        93   178    9   0.0018           1     20.60 Å
  orient_255_pt12__2_pt12__3_a1_t0.1_s1_af2pred         93   178    9   0.8226         829      4.57 Å
  orient_255_pt12__2_pt12__3_a1_t0.1_s2_af2pred         93   178    9   0.7896         812      5.31 Å
  orient_255_pt12__2_pt12__3_a1_t0.1_s4_af2pred         93   178    9   0.7659         815      5.74 Å
  orient_255_pt12__2_pt12__3_a1_t0.1_s5_af2pred         93   178    9   0.8383         828      4.30 Å
  orient_255_pt12__2_pt12__3_a1_t0.1_s7_af2pred         93   178    9   0.8639         819      4.17 Å
  orient_255_pt12__2_pt12__3_a1_t0.1_s8_af2pred         93   178    9   0.7932         820      5.12 Å
  orient_255_pt12__2_pt12__3_a2_t0.1_s1_af2pred         93   178    9   0.3229         328     13.17 Å
  orient_255_pt12__2_pt12__3_a2_t0.1_s2_af2pred         93   178    9   0.7558         826      5.66 Å
  orient_255_pt12__2_pt12__41_a1_t0.1_s3_af2pred        93   178    9   0.5664         677      9.32 Å
  orient_255_pt12__2_pt12__41_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     21.57 Å
  orient_255_pt12__2_pt12__41_a2_t0.1_s1_af2pred        93   178    9   0.7759         808      5.57 Å
  orient_255_pt12__2_pt12__41_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     24.44 Å
  orient_255_pt12__2_pt12__41_a2_t0.1_s3_af2pred        93   178    9   0.6715         783      7.24 Å
  orient_255_pt12__2_pt12__41_a2_t0.1_s7_af2pred        93   178    9   0.0000           0     22.52 Å
  orient_255_pt12__2_pt12__41_a4_t0.1_s4_af2pred        93   178    9   0.6476         748      7.87 Å
  orient_255_pt12__2_pt12__41_a5_t0.1_s7_af2pred        93   178    9   0.4702         532     10.99 Å
  orient_255_pt12__2_pt12__43_a10_t0.1_s1_af2pred       93   178    9   0.8479         834      4.09 Å
  orient_255_pt12__2_pt12__43_a10_t0.1_s3_af2pred       93   178    9   0.0000           0     20.86 Å
  orient_255_pt12__2_pt12__43_a2_t0.1_s4_af2pred        93   178    9   0.0000           0     21.81 Å
  orient_255_pt12__2_pt12__43_a4_t0.1_s1_af2pred        93   178    9   0.0000           0     22.27 Å
  orient_255_pt12__2_pt12__43_a6_t0.1_s4_af2pred        93   178    9   0.0000           0     22.14 Å
  orient_255_pt12__2_pt12__43_a6_t0.1_s5_af2pred        93   178    9   0.0000           0     22.62 Å
  orient_255_pt12__2_pt12__43_a9_t0.1_s2_af2pred        93   178    9   0.0203          34     17.77 Å
  orient_255_pt12__2_pt12__43_a9_t0.1_s7_af2pred        93   178    9   0.0000           0     20.93 Å
  orient_255_pt12__2_pt12__46_a1_t0.1_s2_af2pred        93   178    9   0.0021          12     18.69 Å
  orient_255_pt12__2_pt12__46_a1_t0.1_s3_af2pred        93   178    9   0.1924         188     14.43 Å
  orient_255_pt12__2_pt12__46_a1_t0.1_s4_af2pred        93   178    9   0.1689         168     14.59 Å
  orient_255_pt12__2_pt12__46_a1_t0.1_s5_af2pred        93   178    9   0.0020          18     18.29 Å
  orient_255_pt12__2_pt12__46_a1_t0.1_s7_af2pred        93   178    9   0.0049          24     17.76 Å
  orient_255_pt12__2_pt12__46_a1_t0.1_s8_af2pred        93   178    9   0.5954         701      8.81 Å
  orient_255_pt12__2_pt12__46_a2_t0.1_s2_af2pred        93   178    9   0.6183         737      8.28 Å
  orient_255_pt12__2_pt12__46_a2_t0.1_s6_af2pred        93   178    9   0.2464         231     14.10 Å
  orient_255_pt12__2_pt12__47_a1_t0.1_s1_af2pred        93   178    9   0.5569         687      9.53 Å
  orient_255_pt12__2_pt12__47_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     20.15 Å
  orient_255_pt12__2_pt12__47_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     21.36 Å
  orient_255_pt12__2_pt12__47_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     21.12 Å
  orient_255_pt12__2_pt12__47_a1_t0.1_s6_af2pred        93   178    9   0.0000           0     22.22 Å
  orient_255_pt12__2_pt12__47_a1_t0.1_s8_af2pred        93   178    9   0.0000           0     21.40 Å
  orient_255_pt12__2_pt12__47_a2_t0.1_s1_af2pred        93   178    9   0.4136         446     12.10 Å
  orient_255_pt12__2_pt12__47_a2_t0.1_s2_af2pred        93   178    9   0.6756         775      7.29 Å
  orient_255_pt12__2_pt12__49_a11_t0.15_s5_af2pred      93   178    9   0.8133         828      4.75 Å
  orient_255_pt12__2_pt12__49_a13_t0.15_s4_af2pred      93   178    9   0.0000           0     23.71 Å
  orient_255_pt12__2_pt12__49_a14_t0.15_s4_af2pred      93   178    9   0.0000           0     21.81 Å
  orient_255_pt12__2_pt12__49_a15_t0.15_s4_af2pred      93   178    9   0.8303         819      4.65 Å
  orient_255_pt12__2_pt12__49_a16_t0.15_s1_af2pred      93   178    9   0.0000           0     22.31 Å
  orient_255_pt12__2_pt12__49_a1_t0.1_s3_af2pred        93   178    9   0.8336         820      4.56 Å
  orient_255_pt12__2_pt12__49_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     22.00 Å
  orient_255_pt12__2_pt12__49_a7_t0.1_s5_af2pred        93   178    9   0.0000           0     24.21 Å
  orient_255_pt12__2_pt12__4_a1_t0.1_s1_af2pred         93   178    9   0.4875         572     11.07 Å
  orient_255_pt12__2_pt12__4_a1_t0.1_s2_af2pred         93   178    9   0.0000           0     22.77 Å
  orient_255_pt12__2_pt12__4_a1_t0.1_s4_af2pred         93   178    9   0.0000           0     22.10 Å
  orient_255_pt12__2_pt12__4_a1_t0.1_s8_af2pred         93   178    9   0.0000           0     22.10 Å
  orient_255_pt12__2_pt12__4_a2_t0.1_s2_af2pred         93   178    9   0.0000           0     22.09 Å
  orient_255_pt12__2_pt12__4_a2_t0.1_s4_af2pred         93   178    9   0.0000           0     21.43 Å
  orient_255_pt12__2_pt12__4_a2_t0.1_s6_af2pred         93   178    9   0.0000           0     21.52 Å
  orient_255_pt12__2_pt12__4_a2_t0.1_s7_af2pred         93   178    9   0.0000           0     22.95 Å
  orient_255_pt12__2_pt12__52_a1_t0.1_s1_af2pred        93   178    9   0.7890         813      5.42 Å
  orient_255_pt12__2_pt12__52_a1_t0.1_s2_af2pred        93   178    9   0.0000           0     22.31 Å
  orient_255_pt12__2_pt12__52_a1_t0.1_s6_af2pred        93   178    9   0.0020           5     20.90 Å
  orient_255_pt12__2_pt12__52_a1_t0.1_s7_af2pred        93   178    9   0.0000           0     22.77 Å
  orient_255_pt12__2_pt12__52_a1_t0.1_s8_af2pred        93   178    9   0.0000           0     21.23 Å
  orient_255_pt12__2_pt12__52_a2_t0.1_s1_af2pred        93   178    9   0.7248         754      7.02 Å
  orient_255_pt12__2_pt12__52_a2_t0.1_s4_af2pred        93   178    9   0.0020           1     21.71 Å
  orient_255_pt12__2_pt12__52_a3_t0.1_s1_af2pred        93   178    9   0.0000           0     23.17 Å
  orient_255_pt12__2_pt12__53_a1_t0.1_s2_af2pred        93   178    9   0.2575         243     14.06 Å
  orient_255_pt12__2_pt12__53_a1_t0.1_s4_af2pred        93   178    9   0.0020           1     20.94 Å
  orient_255_pt12__2_pt12__53_a1_t0.1_s7_af2pred        93   178    9   0.0000           0     22.45 Å
  orient_255_pt12__2_pt12__53_a1_t0.1_s8_af2pred        93   178    9   0.8236         836      4.47 Å
  orient_255_pt12__2_pt12__53_a2_t0.1_s2_af2pred        93   178    9   0.8506         837      3.99 Å

  orient_255_pt12__2_pt12__53_a2_t0.1_s4_af2pred        93   178    9   0.8116         826      4.76 Å
  orient_255_pt12__2_pt12__53_a2_t0.1_s6_af2pred        93   178    9   0.5954         697      8.72 Å
  orient_255_pt12__2_pt12__53_a2_t0.1_s8_af2pred        93   178    9   0.6986         806      6.71 Å
  orient_255_pt12__2_pt12__55_a1_t0.1_s2_af2pred        93   178    9   0.0000           0     22.71 Å
  orient_255_pt12__2_pt12__55_a1_t0.1_s6_af2pred        93   178    9   0.6066         731      8.50 Å
  orient_255_pt12__2_pt12__55_a1_t0.1_s7_af2pred        93   178    9   0.0000           0     22.33 Å
  orient_255_pt12__2_pt12__55_a1_t0.1_s8_af2pred        93   178    9   0.5184         613     10.05 Å
  orient_255_pt12__2_pt12__55_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     21.55 Å
  orient_255_pt12__2_pt12__55_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     22.27 Å
  orient_255_pt12__2_pt12__55_a2_t0.1_s4_af2pred        93   178    9   0.3153         310     13.25 Å
  orient_255_pt12__2_pt12__55_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     22.61 Å
  orient_255_pt12__2_pt12__57_a1_t0.1_s1_af2pred        93   178    9   0.6344         747      8.06 Å
  orient_255_pt12__2_pt12__57_a1_t0.1_s4_af2pred        93   178    9   0.7949         815      5.33 Å
  orient_255_pt12__2_pt12__57_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     22.12 Å
  orient_255_pt12__2_pt12__57_a1_t0.1_s7_af2pred        93   178    9   0.8093         816      5.05 Å
  orient_255_pt12__2_pt12__57_a1_t0.1_s8_af2pred        93   178    9   0.7695         817      5.53 Å
  orient_255_pt12__2_pt12__57_a2_t0.1_s3_af2pred        93   178    9   0.7308         813      6.16 Å
  orient_255_pt12__2_pt12__57_a2_t0.1_s4_af2pred        93   178    9   0.8406         829      4.28 Å
  orient_255_pt12__2_pt12__57_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     22.55 Å
  orient_255_pt12__2_pt12__5_a1_t0.1_s1_af2pred         93   178    9   0.8573         827      3.98 Å
  orient_255_pt12__2_pt12__5_a1_t0.1_s3_af2pred         93   178    9   0.6435         777      7.74 Å
  orient_255_pt12__2_pt12__5_a1_t0.1_s4_af2pred         93   178    9   0.0020          18     18.85 Å
  orient_255_pt12__2_pt12__5_a1_t0.1_s5_af2pred         93   178    9   0.6216         728      8.28 Å
  orient_255_pt12__2_pt12__5_a1_t0.1_s7_af2pred         93   178    9   0.7846         822      5.24 Å
  orient_255_pt12__2_pt12__5_a1_t0.1_s8_af2pred         93   178    9   0.6966         777      6.94 Å
  orient_255_pt12__2_pt12__5_a2_t0.1_s1_af2pred         93   178    9   0.8553         836      3.94 Å
  orient_255_pt12__2_pt12__5_a2_t0.1_s2_af2pred         93   178    9   0.0000           0     23.80 Å
  orient_255_pt12__2_pt12__64_a1_t0.1_s2_af2pred        93   178    9   0.4954         567     10.64 Å
  orient_255_pt12__2_pt12__64_a1_t0.1_s3_af2pred        93   178    9   0.0019           2     19.33 Å
  orient_255_pt12__2_pt12__64_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     21.04 Å
  orient_255_pt12__2_pt12__64_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     21.45 Å
  orient_255_pt12__2_pt12__64_a1_t0.1_s7_af2pred        93   178    9   0.3958         415     12.13 Å
  orient_255_pt12__2_pt12__64_a1_t0.1_s8_af2pred        93   178    9   0.0000           0     22.80 Å
  orient_255_pt12__2_pt12__64_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     21.66 Å
  orient_255_pt12__2_pt12__64_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     20.88 Å
  orient_255_pt12__2_pt12__65_a12_t0.15_s2_af2pred      93   178    9   0.0000           0     21.16 Å
  orient_255_pt12__2_pt12__65_a17_t0.15_s1_af2pred      93   178    9   0.0000           0     22.48 Å
  orient_255_pt12__2_pt12__65_a20_t0.15_s3_af2pred      93   178    9   0.3118         301     13.52 Å
  orient_255_pt12__2_pt12__65_a22_t0.2_s3_af2pred       93   178    9   0.0000           0     24.35 Å
  orient_255_pt12__2_pt12__65_a22_t0.2_s5_af2pred       93   178    9   0.0591          61     17.05 Å
  orient_255_pt12__2_pt12__65_a26_t0.2_s4_af2pred       93   178    9   0.0000           0     22.65 Å
  orient_255_pt12__2_pt12__65_a28_t0.2_s3_af2pred       93   178    9   0.7843         823      5.25 Å
  orient_255_pt12__2_pt12__66_a16_t0.15_s5_af2pred      93   178    9   0.0000           0     23.04 Å
  orient_255_pt12__2_pt12__66_a20_t0.15_s5_af2pred      93   178    9   0.0000           0     22.69 Å
  orient_255_pt12__2_pt12__66_a25_t0.2_s1_af2pred       93   178    9   0.0000           0     22.30 Å
  orient_255_pt12__2_pt12__66_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     21.51 Å
  orient_255_pt12__2_pt12__66_a4_t0.1_s6_af2pred        93   178    9   0.0000           0     23.34 Å
  orient_255_pt12__2_pt12__66_a7_t0.1_s2_af2pred        93   178    9   0.0000           0     22.87 Å
  orient_255_pt12__2_pt12__66_a8_t0.1_s5_af2pred        93   178    9   0.0000           0     21.96 Å
  orient_255_pt12__2_pt12__66_a8_t0.1_s6_af2pred        93   178    9   0.0000           0     23.39 Å
  orient_255_pt12__2_pt12__67_a16_t0.15_s2_af2pred      93   178    9   0.0000           0     22.25 Å
  orient_255_pt12__2_pt12__67_a21_t0.2_s6_af2pred       93   178    9   0.0020          15     18.51 Å
  orient_255_pt12__2_pt12__67_a28_t0.2_s3_af2pred       93   178    9   0.0000           0     23.75 Å
  orient_255_pt12__2_pt12__67_a6_t0.1_s3_af2pred        93   178    9   0.0000           0     23.11 Å
  orient_255_pt12__2_pt12__68_a1_t0.1_s3_af2pred        93   178    9   0.4872         566     10.64 Å
  orient_255_pt12__2_pt12__68_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     22.30 Å
  orient_255_pt12__2_pt12__68_a1_t0.1_s6_af2pred        93   178    9   0.0000           0     22.46 Å
  orient_255_pt12__2_pt12__68_a1_t0.1_s8_af2pred        93   178    9   0.0021           1     19.62 Å
  orient_255_pt12__2_pt12__68_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     22.40 Å
  orient_255_pt12__2_pt12__68_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     22.15 Å
  orient_255_pt12__2_pt12__68_a2_t0.1_s6_af2pred        93   178    9   0.7321         800      6.22 Å
  orient_255_pt12__2_pt12__68_a2_t0.1_s8_af2pred        93   178    9   0.2102         180     14.94 Å
  orient_255_pt12__2_pt12__70_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     22.05 Å
  orient_255_pt12__2_pt12__70_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     22.19 Å
  orient_255_pt12__2_pt12__70_a1_t0.1_s7_af2pred        93   178    9   0.0000           0     22.46 Å
  orient_255_pt12__2_pt12__70_a2_t0.1_s4_af2pred        93   178    9   0.0000           0     20.30 Å
  orient_255_pt12__2_pt12__70_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     20.57 Å
  orient_255_pt12__2_pt12__70_a2_t0.1_s7_af2pred        93   178    9   0.0493          55     16.85 Å
  orient_255_pt12__2_pt12__70_a2_t0.1_s8_af2pred        93   178    9   0.0000           0     21.72 Å
  orient_255_pt12__2_pt12__70_a3_t0.1_s3_af2pred        93   178    9   0.0022           1     21.79 Å
  orient_255_pt12__2_pt12__74_a1_t0.1_s1_af2pred        93   178    9   0.7297         788      6.39 Å
  orient_255_pt12__2_pt12__74_a1_t0.1_s7_af2pred        93   178    9   0.7875         793      5.53 Å
  orient_255_pt12__2_pt12__74_a2_t0.1_s4_af2pred        93   178    9   0.5895         684      8.99 Å
  orient_255_pt12__2_pt12__74_a3_t0.1_s7_af2pred        93   178    9   0.0000           0     23.22 Å
  orient_255_pt12__2_pt12__74_a3_t0.1_s8_af2pred        93   178    9   0.8529         823      4.13 Å
  orient_255_pt12__2_pt12__74_a4_t0.1_s1_af2pred        93   178    9   0.1831         156     15.48 Å
  orient_255_pt12__2_pt12__74_a4_t0.1_s6_af2pred        93   178    9   0.0000           0     23.21 Å
  orient_255_pt12__2_pt12__74_a5_t0.1_s3_af2pred        93   178    9   0.7736         802      5.69 Å
  orient_255_pt12__2_pt12__75_a13_t0.15_s5_af2pred      93   178    9   0.0000           0     22.01 Å
  orient_255_pt12__2_pt12__75_a15_t0.15_s3_af2pred      93   178    9   0.0000           0     26.05 Å
  orient_255_pt12__2_pt12__75_a16_t0.15_s5_af2pred      93   178    9   0.0000           0     23.32 Å
  orient_255_pt12__2_pt12__75_a17_t0.15_s3_af2pred      93   178    9   0.0000           0     20.99 Å
  orient_255_pt12__2_pt12__75_a28_t0.2_s5_af2pred       93   178    9   0.0000           0     27.05 Å
  orient_255_pt12__2_pt12__75_a3_t0.1_s3_af2pred        93   178    9   0.0000           0     23.75 Å
  orient_255_pt12__2_pt12__79_a1_t0.1_s3_af2pred        93   178    9   0.1446         134     15.55 Å
  orient_255_pt12__2_pt12__79_a1_t0.1_s8_af2pred        93   178    9   0.0021           4     19.64 Å
  orient_255_pt12__2_pt12__79_a2_t0.1_s1_af2pred        93   178    9   0.0018           2     20.10 Å
  orient_255_pt12__2_pt12__79_a2_t0.1_s2_af2pred        93   178    9   0.0018           1     21.32 Å
  orient_255_pt12__2_pt12__79_a2_t0.1_s4_af2pred        93   178    9   0.0000           0     21.48 Å
  orient_255_pt12__2_pt12__79_a2_t0.1_s7_af2pred        93   178    9   0.0000           0     22.24 Å
  orient_255_pt12__2_pt12__79_a3_t0.1_s1_af2pred        93   178    9   0.6838         767      7.26 Å
  orient_255_pt12__2_pt12__79_a3_t0.1_s2_af2pred        93   178    9   0.6709         751      7.55 Å
  orient_255_pt12__2_pt12__80_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     22.56 Å
  orient_255_pt12__2_pt12__80_a1_t0.1_s2_af2pred        93   178    9   0.0000           0     22.86 Å
  orient_255_pt12__2_pt12__80_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     25.58 Å
  orient_255_pt12__2_pt12__80_a1_t0.1_s4_af2pred        93   178    9   0.0022           1     19.81 Å
  orient_255_pt12__2_pt12__80_a1_t0.1_s8_af2pred        93   178    9   0.0000           0     20.88 Å
  orient_255_pt12__2_pt12__80_a2_t0.1_s2_af2pred        93   178    9   0.6584         761      7.64 Å
  orient_255_pt12__2_pt12__80_a2_t0.1_s4_af2pred        93   178    9   0.0021           1     19.51 Å
  orient_255_pt12__2_pt12__80_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     20.90 Å
  orient_255_pt12__2_pt12__85_a4_t0.1_s1_af2pred        93   178    9   0.0000           0     23.32 Å
  orient_255_pt12__2_pt12__91_a1_t0.1_s1_af2pred        93   178    9   0.7496         803      5.97 Å
  orient_255_pt12__2_pt12__91_a1_t0.1_s5_af2pred        93   178    9   0.0023           3     19.36 Å
  orient_255_pt12__2_pt12__91_a1_t0.1_s8_af2pred        93   178    9   0.7788         788      5.67 Å
  orient_255_pt12__2_pt12__91_a2_t0.1_s1_af2pred        93   178    9   0.8012         825      5.00 Å
  orient_255_pt12__2_pt12__91_a2_t0.1_s2_af2pred        93   178    9   0.0019           1     21.46 Å

  orient_255_pt12__2_pt12__91_a2_t0.1_s4_af2pred        93   178    9   0.7783         815      5.41 Å
  orient_255_pt12__2_pt12__91_a2_t0.1_s7_af2pred        93   178    9   0.0000           0     25.27 Å
  orient_255_pt12__2_pt12__91_a2_t0.1_s8_af2pred        93   178    9   0.0020           7     19.23 Å
  orient_255_pt12__2_pt12__94_a1_t0.1_s2_af2pred        93   178    9   0.0000           0     21.18 Å
  orient_255_pt12__2_pt12__94_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     21.67 Å
  orient_255_pt12__2_pt12__94_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     22.92 Å
  orient_255_pt12__2_pt12__94_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     21.66 Å
  orient_255_pt12__2_pt12__94_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     22.22 Å
  orient_255_pt12__2_pt12__94_a2_t0.1_s8_af2pred        93   178    9   0.5376         611     10.01 Å
  orient_255_pt12__2_pt12__94_a3_t0.1_s8_af2pred        93   178    9   0.0000           0     22.61 Å
  orient_255_pt12__2_pt12__94_a4_t0.1_s5_af2pred        93   178    9   0.5764         647      9.38 Å
  orient_255_pt12__2_pt12__99_a10_t0.1_s6_af2pred       93   178    9   0.8640         837      3.77 Å
  orient_255_pt12__2_pt12__99_a11_t0.15_s4_af2pred      93   178    9   0.5874         665      9.63 Å
  orient_255_pt12__2_pt12__99_a15_t0.15_s3_af2pred      93   178    9   0.8143         823      4.74 Å
  orient_255_pt12__2_pt12__99_a1_t0.1_s4_af2pred        93   178    9   0.8182         837      4.57 Å
  orient_255_pt12__2_pt12__99_a2_t0.1_s6_af2pred        93   178    9   0.8110         759      5.66 Å
  orient_255_pt12__2_pt12__99_a5_t0.1_s6_af2pred        93   178    9   0.0000           0     22.94 Å
  orient_255_pt12__2_pt12__99_a8_t0.1_s1_af2pred        93   178    9   0.7503         820      5.77 Å
  orient_255_pt12__2_pt12__99_a8_t0.1_s5_af2pred        93   178    9   0.7282         803      6.24 Å
  orient_255_pt12__31_pt12__0_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     23.20 Å
  orient_255_pt12__31_pt12__0_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     22.96 Å
  orient_255_pt12__31_pt12__0_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     25.40 Å
  orient_255_pt12__31_pt12__0_a1_t0.1_s8_af2pred        93   178    9   0.2225         182     14.95 Å
  orient_255_pt12__31_pt12__0_a2_t0.1_s1_af2pred        93   178    9   0.4977         597     10.49 Å
  orient_255_pt12__31_pt12__0_a2_t0.1_s2_af2pred        93   178    9   0.3663         369     12.64 Å
  orient_255_pt12__31_pt12__0_a2_t0.1_s4_af2pred        93   178    9   0.0000           0     23.76 Å
  orient_255_pt12__31_pt12__0_a2_t0.1_s8_af2pred        93   178    9   0.0000           0     22.24 Å
  orient_255_pt12__31_pt12__11_a1_t0.1_s3_af2pred       93   178    9   0.0416          49     16.81 Å
  orient_255_pt12__31_pt12__11_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     21.91 Å
  orient_255_pt12__31_pt12__11_a1_t0.1_s7_af2pred       93   178    9   0.0021           2     18.68 Å
  orient_255_pt12__31_pt12__11_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     22.18 Å
  orient_255_pt12__31_pt12__11_a2_t0.1_s1_af2pred       93   178    9   0.6328         726      8.38 Å
  orient_255_pt12__31_pt12__11_a2_t0.1_s2_af2pred       93   178    9   0.2306         220     14.42 Å
  orient_255_pt12__31_pt12__11_a2_t0.1_s4_af2pred       93   178    9   0.0021           1     20.90 Å
  orient_255_pt12__31_pt12__11_a2_t0.1_s6_af2pred       93   178    9   0.6954         760      7.15 Å
  orient_255_pt12__31_pt12__15_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     23.56 Å
  orient_255_pt12__31_pt12__15_a2_t0.1_s2_af2pred       93   178    9   0.0019           7     20.02 Å
  orient_255_pt12__31_pt12__15_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     22.58 Å
  orient_255_pt12__31_pt12__15_a2_t0.1_s5_af2pred       93   178    9   0.0000           0     26.84 Å
  orient_255_pt12__31_pt12__15_a3_t0.1_s2_af2pred       93   178    9   0.0020           3     20.34 Å
  orient_255_pt12__31_pt12__15_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.94 Å
  orient_255_pt12__31_pt12__15_a3_t0.1_s5_af2pred       93   178    9   0.8493         829      4.11 Å
  orient_255_pt12__31_pt12__15_a4_t0.1_s2_af2pred       93   178    9   0.8018         797      5.30 Å
  orient_255_pt12__31_pt12__18_a1_t0.1_s1_af2pred       93   178    9   0.7328         804      6.21 Å
  orient_255_pt12__31_pt12__18_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     22.38 Å
  orient_255_pt12__31_pt12__18_a1_t0.1_s3_af2pred       93   178    9   0.0315          42     17.61 Å
  orient_255_pt12__31_pt12__18_a1_t0.1_s4_af2pred       93   178    9   0.6165         743      8.43 Å
  orient_255_pt12__31_pt12__18_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     23.31 Å
  orient_255_pt12__31_pt12__18_a1_t0.1_s7_af2pred       93   178    9   0.3683         385     12.73 Å
  orient_255_pt12__31_pt12__18_a2_t0.1_s8_af2pred       93   178    9   0.5983         700      8.79 Å
  orient_255_pt12__31_pt12__18_a3_t0.1_s3_af2pred       93   178    9   0.0018           1     20.99 Å
  orient_255_pt12__31_pt12__26_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     23.32 Å
  orient_255_pt12__31_pt12__26_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     21.87 Å
  orient_255_pt12__31_pt12__26_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.26 Å
  orient_255_pt12__31_pt12__26_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     25.85 Å
  orient_255_pt12__31_pt12__26_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.67 Å
  orient_255_pt12__31_pt12__26_a3_t0.1_s5_af2pred       93   178    9   0.0019           1     20.86 Å
  orient_255_pt12__31_pt12__26_a3_t0.1_s8_af2pred       93   178    9   0.0000           0     21.82 Å
  orient_255_pt12__31_pt12__26_a4_t0.1_s1_af2pred       93   178    9   0.0000           0     22.11 Å
  orient_255_pt12__31_pt12__28_a1_t0.1_s1_af2pred       93   178    9   0.8141         816      4.91 Å
  orient_255_pt12__31_pt12__28_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     22.37 Å
  orient_255_pt12__31_pt12__28_a1_t0.1_s3_af2pred       93   178    9   0.7539         802      5.92 Å
  orient_255_pt12__31_pt12__28_a1_t0.1_s4_af2pred       93   178    9   0.8273         803      4.79 Å
  orient_255_pt12__31_pt12__28_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     21.07 Å
  orient_255_pt12__31_pt12__28_a1_t0.1_s7_af2pred       93   178    9   0.7378         766      6.55 Å
  orient_255_pt12__31_pt12__28_a1_t0.1_s8_af2pred       93   178    9   0.5397         626     10.10 Å
  orient_255_pt12__31_pt12__28_a2_t0.1_s2_af2pred       93   178    9   0.3583         352     13.38 Å
  orient_255_pt12__31_pt12__2_a1_t0.1_s4_af2pred        93   178    9   0.8312         828      4.45 Å
  orient_255_pt12__31_pt12__2_a3_t0.1_s2_af2pred        93   178    9   0.1370         122     15.72 Å
  orient_255_pt12__31_pt12__2_a3_t0.1_s8_af2pred        93   178    9   0.7108         797      6.68 Å
  orient_255_pt12__31_pt12__2_a4_t0.1_s1_af2pred        93   178    9   0.0000           0     22.43 Å
  orient_255_pt12__31_pt12__2_a4_t0.1_s4_af2pred        93   178    9   0.0000           0     22.69 Å
  orient_255_pt12__31_pt12__2_a5_t0.1_s3_af2pred        93   178    9   0.0021           3     20.42 Å
  orient_255_pt12__31_pt12__2_a5_t0.1_s6_af2pred        93   178    9   0.7663         819      5.56 Å
  orient_255_pt12__31_pt12__2_a6_t0.1_s3_af2pred        93   178    9   0.8015         829      4.90 Å
  orient_255_pt12__31_pt12__31_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     23.03 Å
  orient_255_pt12__31_pt12__31_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.39 Å
  orient_255_pt12__31_pt12__31_a3_t0.1_s8_af2pred       93   178    9   0.7720         826      5.41 Å
  orient_255_pt12__31_pt12__31_a5_t0.1_s5_af2pred       93   178    9   0.0000           0     23.16 Å
  orient_255_pt12__31_pt12__31_a6_t0.1_s5_af2pred       93   178    9   0.0000           0     22.58 Å
  orient_255_pt12__31_pt12__31_a6_t0.1_s7_af2pred       93   178    9   0.0000           0     22.53 Å
  orient_255_pt12__31_pt12__31_a8_t0.1_s5_af2pred       93   178    9   0.8208         822      4.68 Å
  orient_255_pt12__31_pt12__31_a9_t0.1_s3_af2pred       93   178    9   0.8258         837      4.45 Å
  orient_255_pt12__31_pt12__33_a1_t0.1_s1_af2pred       93   178    9   0.4550         512     11.35 Å
  orient_255_pt12__31_pt12__33_a1_t0.1_s4_af2pred       93   178    9   0.6666         763      7.45 Å
  orient_255_pt12__31_pt12__33_a1_t0.1_s8_af2pred       93   178    9   0.0020           6     20.13 Å
  orient_255_pt12__31_pt12__33_a2_t0.1_s6_af2pred       93   178    9   0.0899          83     16.11 Å
  orient_255_pt12__31_pt12__33_a3_t0.1_s7_af2pred       93   178    9   0.3400         346     12.99 Å

  orient_255_pt12__31_pt12__33_a4_t0.1_s4_af2pred       93   178    9   0.4119         462     11.91 Å
  orient_255_pt12__31_pt12__33_a5_t0.1_s3_af2pred       93   178    9   0.0000           0     24.70 Å
  orient_255_pt12__31_pt12__33_a5_t0.1_s7_af2pred       93   178    9   0.0000           0     24.13 Å
  orient_255_pt12__31_pt12__3_a1_t0.1_s3_af2pred        93   178    9   0.8121         829      4.72 Å
  orient_255_pt12__31_pt12__3_a1_t0.1_s4_af2pred        93   178    9   0.0023           8     18.66 Å
  orient_255_pt12__31_pt12__3_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     22.65 Å
  orient_255_pt12__31_pt12__3_a2_t0.1_s2_af2pred        93   178    9   0.6071         728      8.68 Å
  orient_255_pt12__31_pt12__3_a2_t0.1_s4_af2pred        93   178    9   0.4093         457     11.77 Å
  orient_255_pt12__31_pt12__3_a2_t0.1_s5_af2pred        93   178    9   0.6548         779      7.55 Å
  orient_255_pt12__31_pt12__3_a2_t0.1_s7_af2pred        93   178    9   0.8178         821      4.80 Å
  orient_255_pt12__31_pt12__3_a3_t0.1_s1_af2pred        93   178    9   0.0000           0     24.34 Å
  orient_255_pt12__31_pt12__41_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     21.39 Å
  orient_255_pt12__31_pt12__41_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     21.99 Å
  orient_255_pt12__31_pt12__41_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     23.63 Å
  orient_255_pt12__31_pt12__41_a3_t0.1_s1_af2pred       93   178    9   0.0000           0     23.00 Å
  orient_255_pt12__31_pt12__41_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.67 Å
  orient_255_pt12__31_pt12__41_a3_t0.1_s7_af2pred       93   178    9   0.0000           0     22.57 Å
  orient_255_pt12__31_pt12__41_a4_t0.1_s5_af2pred       93   178    9   0.0021           5     19.79 Å
  orient_255_pt12__31_pt12__41_a5_t0.1_s1_af2pred       93   178    9   0.0000           0     21.59 Å
  orient_255_pt12__31_pt12__42_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     21.78 Å
  orient_255_pt12__31_pt12__42_a1_t0.1_s3_af2pred       93   178    9   0.0019           2     19.91 Å
  orient_255_pt12__31_pt12__42_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     21.64 Å
  orient_255_pt12__31_pt12__42_a1_t0.1_s7_af2pred       93   178    9   0.1387         135     15.36 Å
  orient_255_pt12__31_pt12__42_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     21.46 Å
  orient_255_pt12__31_pt12__42_a2_t0.1_s2_af2pred       93   178    9   0.5327         625      9.95 Å
  orient_255_pt12__31_pt12__42_a2_t0.1_s3_af2pred       93   178    9   0.0019           1     21.15 Å
  orient_255_pt12__31_pt12__42_a2_t0.1_s4_af2pred       93   178    9   0.8148         807      4.94 Å
  orient_255_pt12__31_pt12__43_a1_t0.1_s1_af2pred       93   178    9   0.7648         812      5.65 Å
  orient_255_pt12__31_pt12__43_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     27.43 Å
  orient_255_pt12__31_pt12__43_a1_t0.1_s7_af2pred       93   178    9   0.7913         827      5.12 Å
  orient_255_pt12__31_pt12__43_a1_t0.1_s8_af2pred       93   178    9   0.0019           3     19.91 Å
  orient_255_pt12__31_pt12__43_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     27.67 Å
  orient_255_pt12__31_pt12__43_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     24.52 Å
  orient_255_pt12__31_pt12__43_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     22.50 Å
  orient_255_pt12__31_pt12__43_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     24.91 Å
  orient_255_pt12__31_pt12__49_a1_t0.1_s1_af2pred       93   178    9   0.7817         802      5.61 Å
  orient_255_pt12__31_pt12__49_a1_t0.1_s2_af2pred       93   178    9   0.7582         820      5.66 Å
  orient_255_pt12__31_pt12__49_a1_t0.1_s3_af2pred       93   178    9   0.7516         816      5.90 Å
  orient_255_pt12__31_pt12__49_a1_t0.1_s4_af2pred       93   178    9   0.6084         729      8.53 Å
  orient_255_pt12__31_pt12__49_a1_t0.1_s5_af2pred       93   178    9   0.2113         186     15.01 Å
  orient_255_pt12__31_pt12__49_a1_t0.1_s6_af2pred       93   178    9   0.7460         808      5.99 Å
  orient_255_pt12__31_pt12__49_a1_t0.1_s7_af2pred       93   178    9   0.7613         801      5.81 Å
  orient_255_pt12__31_pt12__49_a1_t0.1_s8_af2pred       93   178    9   0.7919         819      5.22 Å
  orient_255_pt12__31_pt12__4_a1_t0.1_s1_af2pred        93   178    9   0.0020          18     18.41 Å
  orient_255_pt12__31_pt12__4_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     22.48 Å
  orient_255_pt12__31_pt12__4_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     21.55 Å
  orient_255_pt12__31_pt12__4_a2_t0.1_s4_af2pred        93   178    9   0.4969         591     10.58 Å
  orient_255_pt12__31_pt12__4_a2_t0.1_s6_af2pred        93   178    9   0.4960         588     10.49 Å
  orient_255_pt12__31_pt12__4_a3_t0.1_s3_af2pred        93   178    9   0.0000           0     20.84 Å
  orient_255_pt12__31_pt12__4_a3_t0.1_s4_af2pred        93   178    9   0.0000           0     21.08 Å
  orient_255_pt12__31_pt12__4_a3_t0.1_s7_af2pred        93   178    9   0.0019           4     19.11 Å
  orient_255_pt12__31_pt12__51_a1_t0.1_s4_af2pred       93   178    9   0.7212         790      6.62 Å
  orient_255_pt12__31_pt12__51_a2_t0.1_s4_af2pred       93   178    9   0.6506         746      7.81 Å
  orient_255_pt12__31_pt12__51_a2_t0.1_s6_af2pred       93   178    9   0.5957         711      8.88 Å
  orient_255_pt12__31_pt12__51_a2_t0.1_s7_af2pred       93   178    9   0.7838         807      5.44 Å
  orient_255_pt12__31_pt12__51_a3_t0.1_s3_af2pred       93   178    9   0.7052         776      6.82 Å
  orient_255_pt12__31_pt12__51_a3_t0.1_s8_af2pred       93   178    9   0.5915         694      9.04 Å
  orient_255_pt12__31_pt12__51_a4_t0.1_s1_af2pred       93   178    9   0.6976         791      6.83 Å
  orient_255_pt12__31_pt12__51_a5_t0.1_s1_af2pred       93   178    9   0.0020           9     19.14 Å
  orient_255_pt12__31_pt12__53_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     21.20 Å
  orient_255_pt12__31_pt12__53_a1_t0.1_s2_af2pred       93   178    9   0.1040          95     15.97 Å
  orient_255_pt12__31_pt12__53_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     21.72 Å
  orient_255_pt12__31_pt12__53_a1_t0.1_s7_af2pred       93   178    9   0.7915         826      5.12 Å
  orient_255_pt12__31_pt12__53_a2_t0.1_s1_af2pred       93   178    9   0.8390         808      4.66 Å
  orient_255_pt12__31_pt12__53_a2_t0.1_s2_af2pred       93   178    9   0.0019           2     20.47 Å
  orient_255_pt12__31_pt12__53_a2_t0.1_s6_af2pred       93   178    9   0.8391         827      4.29 Å
  orient_255_pt12__31_pt12__53_a2_t0.1_s7_af2pred       93   178    9   0.5091         605     10.37 Å
  orient_255_pt12__31_pt12__54_a1_t0.1_s1_af2pred       93   178    9   0.0018           1     20.39 Å
  orient_255_pt12__31_pt12__54_a1_t0.1_s3_af2pred       93   178    9   0.7129         776      6.75 Å
  orient_255_pt12__31_pt12__54_a1_t0.1_s4_af2pred       93   178    9   0.0018           9     19.32 Å
  orient_255_pt12__31_pt12__54_a1_t0.1_s5_af2pred       93   178    9   0.0023          10     19.13 Å
  orient_255_pt12__31_pt12__54_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     22.47 Å
  orient_255_pt12__31_pt12__54_a1_t0.1_s7_af2pred       93   178    9   0.0020           5     19.59 Å
  orient_255_pt12__31_pt12__54_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     22.32 Å
  orient_255_pt12__31_pt12__54_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.21 Å
  orient_255_pt12__31_pt12__57_a1_t0.1_s1_af2pred       93   178    9   0.1200         112     15.82 Å
  orient_255_pt12__31_pt12__57_a1_t0.1_s3_af2pred       93   178    9   0.7928         822      5.15 Å
  orient_255_pt12__31_pt12__57_a1_t0.1_s4_af2pred       93   178    9   0.7517         808      5.96 Å
  orient_255_pt12__31_pt12__57_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     22.45 Å
  orient_255_pt12__31_pt12__57_a1_t0.1_s6_af2pred       93   178    9   0.6617         757      7.67 Å
  orient_255_pt12__31_pt12__57_a1_t0.1_s7_af2pred       93   178    9   0.8093         816      4.97 Å
  orient_255_pt12__31_pt12__57_a2_t0.1_s1_af2pred       93   178    9   0.3742         379     12.89 Å
  orient_255_pt12__31_pt12__57_a2_t0.1_s2_af2pred       93   178    9   0.1097          97     16.43 Å
  orient_255_pt12__31_pt12__59_a1_t0.1_s1_af2pred       93   178    9   0.0020          12     19.11 Å
  orient_255_pt12__31_pt12__59_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     24.35 Å

  orient_255_pt12__31_pt12__59_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     21.90 Å
  orient_255_pt12__31_pt12__59_a1_t0.1_s4_af2pred       93   178    9   0.4844         531     10.84 Å
  orient_255_pt12__31_pt12__59_a1_t0.1_s5_af2pred       93   178    9   0.1467         120     15.63 Å
  orient_255_pt12__31_pt12__59_a1_t0.1_s6_af2pred       93   178    9   0.0070          25     17.93 Å
  orient_255_pt12__31_pt12__59_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     21.86 Å
  orient_255_pt12__31_pt12__59_a2_t0.1_s2_af2pred       93   178    9   0.0020          15     19.34 Å
  orient_255_pt12__31_pt12__60_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     21.55 Å
  orient_255_pt12__31_pt12__60_a1_t0.1_s2_af2pred       93   178    9   0.7278         794      6.39 Å
  orient_255_pt12__31_pt12__60_a1_t0.1_s3_af2pred       93   178    9   0.8165         829      4.65 Å
  orient_255_pt12__31_pt12__60_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     21.16 Å
  orient_255_pt12__31_pt12__60_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     22.13 Å
  orient_255_pt12__31_pt12__60_a1_t0.1_s7_af2pred       93   178    9   0.6440         769      7.76 Å
  orient_255_pt12__31_pt12__60_a2_t0.1_s2_af2pred       93   178    9   0.3958         431     12.17 Å
  orient_255_pt12__31_pt12__60_a2_t0.1_s4_af2pred       93   178    9   0.7867         825      5.19 Å
  orient_255_pt12__31_pt12__63_a1_t0.1_s1_af2pred       93   178    9   0.2314         225     14.46 Å
  orient_255_pt12__31_pt12__63_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     22.15 Å
  orient_255_pt12__31_pt12__63_a1_t0.1_s3_af2pred       93   178    9   0.0018           2     19.42 Å
  orient_255_pt12__31_pt12__63_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     20.82 Å
  orient_255_pt12__31_pt12__63_a1_t0.1_s5_af2pred       93   178    9   0.0021           1     20.44 Å
  orient_255_pt12__31_pt12__63_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     21.22 Å
  orient_255_pt12__31_pt12__63_a1_t0.1_s7_af2pred       93   178    9   0.7704         797      5.78 Å
  orient_255_pt12__31_pt12__63_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     21.87 Å
  orient_255_pt12__31_pt12__64_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     24.52 Å
  orient_255_pt12__31_pt12__64_a1_t0.1_s2_af2pred       93   178    9   0.5940         691      8.97 Å
  orient_255_pt12__31_pt12__64_a1_t0.1_s3_af2pred       93   178    9   0.7717         805      5.58 Å
  orient_255_pt12__31_pt12__64_a1_t0.1_s4_af2pred       93   178    9   0.8166         809      4.84 Å
  orient_255_pt12__31_pt12__64_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     22.87 Å
  orient_255_pt12__31_pt12__64_a1_t0.1_s6_af2pred       93   178    9   0.4683         520     11.20 Å
  orient_255_pt12__31_pt12__64_a1_t0.1_s7_af2pred       93   178    9   0.3869         412     12.47 Å
  orient_255_pt12__31_pt12__64_a1_t0.1_s8_af2pred       93   178    9   0.6472         755      7.80 Å
  orient_255_pt12__31_pt12__65_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     23.27 Å
  orient_255_pt12__31_pt12__65_a1_t0.1_s6_af2pred       93   178    9   0.0020           1     20.25 Å
  orient_255_pt12__31_pt12__65_a1_t0.1_s7_af2pred       93   178    9   0.0017           1     20.47 Å
  orient_255_pt12__31_pt12__65_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     21.24 Å
  orient_255_pt12__31_pt12__65_a2_t0.1_s2_af2pred       93   178    9   0.2368         217     14.45 Å
  orient_255_pt12__31_pt12__65_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     24.43 Å
  orient_255_pt12__31_pt12__65_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     21.65 Å
  orient_255_pt12__31_pt12__65_a2_t0.1_s8_af2pred       93   178    9   0.6686         756      7.51 Å
  orient_255_pt12__31_pt12__66_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     21.79 Å
  orient_255_pt12__31_pt12__66_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     21.32 Å
  orient_255_pt12__31_pt12__66_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     24.84 Å
  orient_255_pt12__31_pt12__66_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     22.30 Å
  orient_255_pt12__31_pt12__66_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     23.66 Å
  orient_255_pt12__31_pt12__66_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     25.27 Å
  orient_255_pt12__31_pt12__66_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     21.47 Å
  orient_255_pt12__31_pt12__66_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     21.95 Å
  orient_255_pt12__31_pt12__67_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     19.89 Å
  orient_255_pt12__31_pt12__67_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     21.37 Å
  orient_255_pt12__31_pt12__67_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     22.00 Å
  orient_255_pt12__31_pt12__67_a1_t0.1_s6_af2pred       93   178    9   0.8515         819      4.27 Å
  orient_255_pt12__31_pt12__67_a1_t0.1_s7_af2pred       93   178    9   0.7735         816      5.60 Å
  orient_255_pt12__31_pt12__67_a1_t0.1_s8_af2pred       93   178    9   0.7645         816      5.61 Å
  orient_255_pt12__31_pt12__67_a2_t0.1_s1_af2pred       93   178    9   0.4652         521     11.07 Å
  orient_255_pt12__31_pt12__67_a2_t0.1_s2_af2pred       93   178    9   0.0018           1     21.73 Å
  orient_255_pt12__31_pt12__73_a1_t0.1_s4_af2pred       93   178    9   0.0020           5     19.98 Å
  orient_255_pt12__31_pt12__73_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     23.35 Å
  orient_255_pt12__31_pt12__73_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     22.28 Å
  orient_255_pt12__31_pt12__73_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     22.38 Å
  orient_255_pt12__31_pt12__73_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     21.84 Å
  orient_255_pt12__31_pt12__73_a2_t0.1_s8_af2pred       93   178    9   0.8340         826      4.43 Å
  orient_255_pt12__31_pt12__73_a3_t0.1_s2_af2pred       93   178    9   0.0000           0     22.23 Å
  orient_255_pt12__31_pt12__73_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     23.02 Å
  orient_255_pt12__31_pt12__76_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     22.57 Å
  orient_255_pt12__31_pt12__76_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.87 Å
  orient_255_pt12__31_pt12__76_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     21.73 Å
  orient_255_pt12__31_pt12__76_a2_t0.1_s4_af2pred       93   178    9   0.7929         818      5.14 Å
  orient_255_pt12__31_pt12__76_a2_t0.1_s7_af2pred       93   178    9   0.7114         746      7.15 Å
  orient_255_pt12__31_pt12__76_a3_t0.1_s5_af2pred       93   178    9   0.7698         814      5.56 Å
  orient_255_pt12__31_pt12__76_a3_t0.1_s8_af2pred       93   178    9   0.7868         807      5.43 Å
  orient_255_pt12__31_pt12__76_a4_t0.1_s6_af2pred       93   178    9   0.7219         754      7.05 Å
  orient_255_pt12__31_pt12__7_a1_t0.1_s4_af2pred        93   178    9   0.1172         103     16.22 Å
  orient_255_pt12__31_pt12__7_a1_t0.1_s6_af2pred        93   178    9   0.4968         582     10.62 Å
  orient_255_pt12__31_pt12__7_a1_t0.1_s7_af2pred        93   178    9   0.7761         800      5.78 Å
  orient_255_pt12__31_pt12__7_a2_t0.1_s1_af2pred        93   178    9   0.5680         691      9.21 Å
  orient_255_pt12__31_pt12__7_a2_t0.1_s2_af2pred        93   178    9   0.0583          61     17.02 Å
  orient_255_pt12__31_pt12__7_a2_t0.1_s3_af2pred        93   178    9   0.0021           8     19.06 Å
  orient_255_pt12__31_pt12__7_a2_t0.1_s4_af2pred        93   178    9   0.6785         761      7.49 Å
  orient_255_pt12__31_pt12__7_a2_t0.1_s6_af2pred        93   178    9   0.7493         805      6.04 Å
  orient_255_pt12__31_pt12__84_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     20.68 Å
  orient_255_pt12__31_pt12__84_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     22.84 Å
  orient_255_pt12__31_pt12__84_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     22.42 Å
  orient_255_pt12__31_pt12__84_a1_t0.1_s7_af2pred       93   178    9   0.7643         782      6.07 Å
  orient_255_pt12__31_pt12__84_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     22.25 Å
  orient_255_pt12__31_pt12__84_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.02 Å

  orient_255_pt12__31_pt12__84_a2_t0.1_s5_af2pred       93   178    9   0.0000           0     22.64 Å
  orient_255_pt12__31_pt12__84_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     19.96 Å
  orient_255_pt12__31_pt12__87_a1_t0.1_s1_af2pred       93   178    9   0.1444         120     15.99 Å
  orient_255_pt12__31_pt12__87_a1_t0.1_s3_af2pred       93   178    9   0.3768         387     12.49 Å
  orient_255_pt12__31_pt12__87_a1_t0.1_s4_af2pred       93   178    9   0.0024           9     19.20 Å
  orient_255_pt12__31_pt12__87_a1_t0.1_s5_af2pred       93   178    9   0.3853         423     12.35 Å
  orient_255_pt12__31_pt12__87_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     21.79 Å
  orient_255_pt12__31_pt12__87_a1_t0.1_s7_af2pred       93   178    9   0.0022          16     18.42 Å
  orient_255_pt12__31_pt12__87_a1_t0.1_s8_af2pred       93   178    9   0.6180         714      8.47 Å
  orient_255_pt12__31_pt12__87_a2_t0.1_s1_af2pred       93   178    9   0.6783         749      7.48 Å
  orient_255_pt12__31_pt12__8_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     21.43 Å
  orient_255_pt12__31_pt12__8_a1_t0.1_s6_af2pred        93   178    9   0.0692          73     16.21 Å
  orient_255_pt12__31_pt12__8_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     22.40 Å
  orient_255_pt12__31_pt12__8_a2_t0.1_s7_af2pred        93   178    9   0.1735         157     15.26 Å
  orient_255_pt12__31_pt12__8_a2_t0.1_s8_af2pred        93   178    9   0.0022          20     18.09 Å
  orient_255_pt12__31_pt12__8_a3_t0.1_s8_af2pred        93   178    9   0.0021           6     19.62 Å
  orient_255_pt12__31_pt12__8_a4_t0.1_s1_af2pred        93   178    9   0.0019           4     19.11 Å
  orient_255_pt12__31_pt12__8_a4_t0.1_s4_af2pred        93   178    9   0.0000           0     22.22 Å
  orient_255_pt12__31_pt12__90_a1_t0.1_s2_af2pred       93   178    9   0.7443         792      6.15 Å
  orient_255_pt12__31_pt12__90_a1_t0.1_s3_af2pred       93   178    9   0.4332         488     11.66 Å
  orient_255_pt12__31_pt12__90_a1_t0.1_s4_af2pred       93   178    9   0.6889         761      7.24 Å
  orient_255_pt12__31_pt12__90_a1_t0.1_s5_af2pred       93   178    9   0.8412         835      4.18 Å
  orient_255_pt12__31_pt12__90_a1_t0.1_s6_af2pred       93   178    9   0.7254         816      6.22 Å
  orient_255_pt12__31_pt12__90_a1_t0.1_s7_af2pred       93   178    9   0.7345         799      6.23 Å
  orient_255_pt12__31_pt12__90_a1_t0.1_s8_af2pred       93   178    9   0.0021          17     19.38 Å
  orient_255_pt12__31_pt12__90_a2_t0.1_s1_af2pred       93   178    9   0.6334         746      8.02 Å
  orient_255_pt12__31_pt12__93_a1_t0.1_s2_af2pred       93   178    9   0.0363          46     17.08 Å
  orient_255_pt12__31_pt12__93_a1_t0.1_s3_af2pred       93   178    9   0.8386         826      4.35 Å
  orient_255_pt12__31_pt12__93_a1_t0.1_s4_af2pred       93   178    9   0.8657         828      3.85 Å
  orient_255_pt12__31_pt12__93_a1_t0.1_s5_af2pred       93   178    9   0.0023           5     20.56 Å
  orient_255_pt12__31_pt12__93_a1_t0.1_s6_af2pred       93   178    9   0.8127         819      4.85 Å
  orient_255_pt12__31_pt12__93_a1_t0.1_s7_af2pred       93   178    9   0.4011         438     12.15 Å
  orient_255_pt12__31_pt12__93_a2_t0.1_s4_af2pred       93   178    9   0.7699         822      5.50 Å
  orient_255_pt12__31_pt12__93_a2_t0.1_s7_af2pred       93   178    9   0.8492         819      4.28 Å
  orient_255_pt12__33_pt12__10_a1_t0.1_s5_af2pred       93   178    9   0.8648         826      3.90 Å
  orient_255_pt12__33_pt12__10_a1_t0.1_s7_af2pred       93   178    9   0.8182         824      4.78 Å
  orient_255_pt12__33_pt12__10_a2_t0.1_s6_af2pred       93   178    9   0.0865          82     16.36 Å
  orient_255_pt12__33_pt12__10_a2_t0.1_s7_af2pred       93   178    9   0.0313          40     17.00 Å
  orient_255_pt12__33_pt12__10_a3_t0.1_s1_af2pred       93   178    9   0.8034         830      4.86 Å
  orient_255_pt12__33_pt12__10_a3_t0.1_s2_af2pred       93   178    9   0.0020          14     19.78 Å
  orient_255_pt12__33_pt12__10_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     21.59 Å
  orient_255_pt12__33_pt12__10_a3_t0.1_s7_af2pred       93   178    9   0.0000           0     22.86 Å
  orient_255_pt12__33_pt12__14_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     24.88 Å
  orient_255_pt12__33_pt12__14_a3_t0.1_s2_af2pred       93   178    9   0.6000         709      8.64 Å
  orient_255_pt12__33_pt12__14_a3_t0.1_s5_af2pred       93   178    9   0.0000           0     23.56 Å
  orient_255_pt12__33_pt12__14_a4_t0.1_s8_af2pred       93   178    9   0.8269         835      4.41 Å
  orient_255_pt12__33_pt12__14_a5_t0.1_s5_af2pred       93   178    9   0.8110         831      4.72 Å
  orient_255_pt12__33_pt12__14_a5_t0.1_s6_af2pred       93   178    9   0.7909         831      5.05 Å
  orient_255_pt12__33_pt12__14_a7_t0.1_s5_af2pred       93   178    9   0.7203         813      6.34 Å
  orient_255_pt12__33_pt12__14_a8_t0.1_s6_af2pred       93   178    9   0.7547         820      5.71 Å
  orient_255_pt12__33_pt12__20_a1_t0.1_s8_af2pred       93   178    9   0.1402         135     15.11 Å
  orient_255_pt12__33_pt12__20_a20_t0.15_s3_af2pred      93   178    9   0.6323         744      8.10 Å
  orient_255_pt12__33_pt12__20_a20_t0.15_s8_af2pred      93   178    9   0.0000           0     27.22 Å
  orient_255_pt12__33_pt12__20_a21_t0.2_s1_af2pred      93   178    9   0.2565         267     14.31 Å
  orient_255_pt12__33_pt12__20_a22_t0.2_s1_af2pred      93   178    9   0.0000           0     25.33 Å
  orient_255_pt12__33_pt12__20_a22_t0.2_s2_af2pred      93   178    9   0.6110         727      8.52 Å
  orient_255_pt12__33_pt12__20_a28_t0.2_s2_af2pred      93   178    9   0.0000           0     22.46 Å
  orient_255_pt12__33_pt12__20_a29_t0.2_s4_af2pred      93   178    9   0.0000           0     22.57 Å
  orient_255_pt12__33_pt12__23_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     21.00 Å
  orient_255_pt12__33_pt12__23_a1_t0.1_s3_af2pred       93   178    9   0.7435         788      6.17 Å
  orient_255_pt12__33_pt12__23_a1_t0.1_s4_af2pred       93   178    9   0.0608          63     17.05 Å
  orient_255_pt12__33_pt12__23_a1_t0.1_s6_af2pred       93   178    9   0.7166         766      6.89 Å
  orient_255_pt12__33_pt12__23_a1_t0.1_s7_af2pred       93   178    9   0.7156         790      6.55 Å
  orient_255_pt12__33_pt12__23_a1_t0.1_s8_af2pred       93   178    9   0.8197         828      4.63 Å
  orient_255_pt12__33_pt12__23_a2_t0.1_s1_af2pred       93   178    9   0.7685         828      5.49 Å
  orient_255_pt12__33_pt12__23_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     21.31 Å
  orient_255_pt12__33_pt12__26_a16_t0.15_s5_af2pred      93   178    9   0.0022           5     19.82 Å
  orient_255_pt12__33_pt12__26_a17_t0.15_s7_af2pred      93   178    9   0.0000           0     23.21 Å
  orient_255_pt12__33_pt12__26_a1_t0.1_s7_af2pred       93   178    9   0.0273          38     17.12 Å
  orient_255_pt12__33_pt12__26_a26_t0.2_s1_af2pred      93   178    9   0.0000           0     25.18 Å
  orient_255_pt12__33_pt12__26_a27_t0.2_s2_af2pred      93   178    9   0.8628         827      3.93 Å
  orient_255_pt12__33_pt12__26_a28_t0.2_s6_af2pred      93   178    9   0.8833         826      3.58 Å
  orient_255_pt12__33_pt12__27_a1_t0.1_s1_af2pred       93   178    9   0.5646         711      9.23 Å
  orient_255_pt12__33_pt12__27_a1_t0.1_s5_af2pred       93   178    9   0.0019           4     20.27 Å
  orient_255_pt12__33_pt12__27_a2_t0.1_s1_af2pred       93   178    9   0.0024          12     19.00 Å
  orient_255_pt12__33_pt12__27_a2_t0.1_s2_af2pred       93   178    9   0.7427         829      5.84 Å
  orient_255_pt12__33_pt12__27_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     21.78 Å
  orient_255_pt12__33_pt12__27_a2_t0.1_s6_af2pred       93   178    9   0.0021           6     20.24 Å
  orient_255_pt12__33_pt12__27_a2_t0.1_s7_af2pred       93   178    9   0.8152         829      4.69 Å
  orient_255_pt12__33_pt12__27_a2_t0.1_s8_af2pred       93   178    9   0.0022           5     20.25 Å
  orient_255_pt12__33_pt12__30_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     21.57 Å
  orient_255_pt12__33_pt12__30_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     24.29 Å

  orient_255_pt12__33_pt12__30_a1_t0.1_s4_af2pred       93   178    9   0.0019           5     20.46 Å
  orient_255_pt12__33_pt12__30_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     22.07 Å
  orient_255_pt12__33_pt12__30_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     25.70 Å
  orient_255_pt12__33_pt12__30_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     22.20 Å
  orient_255_pt12__33_pt12__30_a2_t0.1_s3_af2pred       93   178    9   0.3362         333     13.18 Å
  orient_255_pt12__33_pt12__30_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     22.69 Å
  orient_255_pt12__33_pt12__31_a1_t0.1_s6_af2pred       93   178    9   0.0021           5     18.90 Å
  orient_255_pt12__33_pt12__31_a1_t0.1_s7_af2pred       93   178    9   0.8547         834      3.98 Å
  orient_255_pt12__33_pt12__31_a1_t0.1_s8_af2pred       93   178    9   0.5720         701      9.19 Å
  orient_255_pt12__33_pt12__31_a2_t0.1_s2_af2pred       93   178    9   0.0024          10     18.68 Å
  orient_255_pt12__33_pt12__31_a2_t0.1_s4_af2pred       93   178    9   0.7836         828      5.19 Å
  orient_255_pt12__33_pt12__31_a2_t0.1_s6_af2pred       93   178    9   0.3158         334     13.11 Å
  orient_255_pt12__33_pt12__31_a2_t0.1_s7_af2pred       93   178    9   0.6830         793      7.05 Å
  orient_255_pt12__33_pt12__31_a3_t0.1_s1_af2pred       93   178    9   0.6800         797      7.03 Å
  orient_255_pt12__33_pt12__33_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     22.24 Å
  orient_255_pt12__33_pt12__33_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     22.55 Å
  orient_255_pt12__33_pt12__33_a1_t0.1_s3_af2pred       93   178    9   0.0927          84     16.43 Å
  orient_255_pt12__33_pt12__33_a1_t0.1_s4_af2pred       93   178    9   0.7025         800      6.70 Å
  orient_255_pt12__33_pt12__33_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     21.67 Å
  orient_255_pt12__33_pt12__33_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     21.21 Å
  orient_255_pt12__33_pt12__33_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     21.47 Å
  orient_255_pt12__33_pt12__33_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     22.62 Å
  orient_255_pt12__33_pt12__37_a1_t0.1_s2_af2pred       93   178    9   0.8481         835      4.08 Å
  orient_255_pt12__33_pt12__37_a1_t0.1_s8_af2pred       93   178    9   0.8609         835      3.85 Å
  orient_255_pt12__33_pt12__37_a2_t0.1_s1_af2pred       93   178    9   0.0097          27     17.73 Å
  orient_255_pt12__33_pt12__37_a2_t0.1_s4_af2pred       93   178    9   0.6280         732      8.36 Å
  orient_255_pt12__33_pt12__37_a2_t0.1_s7_af2pred       93   178    9   0.8565         837      3.92 Å
  orient_255_pt12__33_pt12__37_a2_t0.1_s8_af2pred       93   178    9   0.2948         286     13.27 Å
  orient_255_pt12__33_pt12__37_a3_t0.1_s1_af2pred       93   178    9   0.0022          19     18.63 Å
  orient_255_pt12__33_pt12__37_a3_t0.1_s2_af2pred       93   178    9   0.0000           0     22.26 Å
  orient_255_pt12__33_pt12__41_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     21.61 Å
  orient_255_pt12__33_pt12__41_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     21.98 Å
  orient_255_pt12__33_pt12__41_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     22.84 Å
  orient_255_pt12__33_pt12__41_a4_t0.1_s4_af2pred       93   178    9   0.0019           2     20.62 Å
  orient_255_pt12__33_pt12__41_a5_t0.1_s3_af2pred       93   178    9   0.0000           0     24.75 Å
  orient_255_pt12__33_pt12__41_a8_t0.1_s7_af2pred       93   178    9   0.7813         799      5.56 Å
  orient_255_pt12__33_pt12__41_a9_t0.1_s2_af2pred       93   178    9   0.0000           0     23.12 Å
  orient_255_pt12__33_pt12__41_a9_t0.1_s3_af2pred       93   178    9   0.0000           0     25.13 Å
  orient_255_pt12__33_pt12__43_a1_t0.1_s3_af2pred       93   178    9   0.6146         753      8.30 Å
  orient_255_pt12__33_pt12__43_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     24.33 Å
  orient_255_pt12__33_pt12__43_a1_t0.1_s6_af2pred       93   178    9   0.7486         814      5.88 Å
  orient_255_pt12__33_pt12__43_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     22.50 Å
  orient_255_pt12__33_pt12__43_a1_t0.1_s8_af2pred       93   178    9   0.7941         816      5.21 Å
  orient_255_pt12__33_pt12__43_a2_t0.1_s1_af2pred       93   178    9   0.8110         794      5.20 Å
  orient_255_pt12__33_pt12__43_a2_t0.1_s2_af2pred       93   178    9   0.8593         830      3.92 Å
  orient_255_pt12__33_pt12__43_a2_t0.1_s3_af2pred       93   178    9   0.0022          10     19.80 Å
  orient_255_pt12__33_pt12__46_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     22.32 Å
  orient_255_pt12__33_pt12__46_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     24.93 Å
  orient_255_pt12__33_pt12__46_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     23.15 Å
  orient_255_pt12__33_pt12__46_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     25.61 Å
  orient_255_pt12__33_pt12__46_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     25.45 Å
  orient_255_pt12__33_pt12__46_a3_t0.1_s1_af2pred       93   178    9   0.0000           0     25.23 Å
  orient_255_pt12__33_pt12__46_a3_t0.1_s3_af2pred       93   178    9   0.7867         819      5.22 Å
  orient_255_pt12__33_pt12__46_a3_t0.1_s4_af2pred       93   178    9   0.0000           0     25.26 Å
  orient_255_pt12__33_pt12__54_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     22.17 Å
  orient_255_pt12__33_pt12__54_a1_t0.1_s3_af2pred       93   178    9   0.8049         814      5.00 Å
  orient_255_pt12__33_pt12__54_a1_t0.1_s4_af2pred       93   178    9   0.2357         225     14.21 Å
  orient_255_pt12__33_pt12__54_a1_t0.1_s5_af2pred       93   178    9   0.8244         825      4.59 Å
  orient_255_pt12__33_pt12__54_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     21.36 Å
  orient_255_pt12__33_pt12__54_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     20.66 Å
  orient_255_pt12__33_pt12__54_a2_t0.1_s1_af2pred       93   178    9   0.0830          86     16.56 Å
  orient_255_pt12__33_pt12__54_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     25.02 Å
  orient_255_pt12__33_pt12__56_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     22.84 Å
  orient_255_pt12__33_pt12__56_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     23.41 Å
  orient_255_pt12__33_pt12__56_a2_t0.1_s8_af2pred       93   178    9   0.7670         795      5.82 Å
  orient_255_pt12__33_pt12__56_a3_t0.1_s4_af2pred       93   178    9   0.6305         700      8.47 Å
  orient_255_pt12__33_pt12__56_a3_t0.1_s5_af2pred       93   178    9   0.6734         802      7.09 Å
  orient_255_pt12__33_pt12__56_a4_t0.1_s1_af2pred       93   178    9   0.0000           0     22.99 Å
  orient_255_pt12__33_pt12__56_a4_t0.1_s4_af2pred       93   178    9   0.8565         832      3.95 Å
  orient_255_pt12__33_pt12__56_a4_t0.1_s6_af2pred       93   178    9   0.7811         829      5.24 Å
  orient_255_pt12__33_pt12__59_a1_t0.1_s2_af2pred       93   178    9   0.8374         819      4.58 Å
  orient_255_pt12__33_pt12__59_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     25.23 Å
  orient_255_pt12__33_pt12__59_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     22.80 Å
  orient_255_pt12__33_pt12__59_a2_t0.1_s1_af2pred       93   178    9   0.8138         826      4.80 Å
  orient_255_pt12__33_pt12__59_a2_t0.1_s2_af2pred       93   178    9   0.5568         697      9.28 Å
  orient_255_pt12__33_pt12__59_a2_t0.1_s4_af2pred       93   178    9   0.7584         826      5.61 Å
  orient_255_pt12__33_pt12__59_a2_t0.1_s6_af2pred       93   178    9   0.7679         828      5.44 Å
  orient_255_pt12__33_pt12__59_a3_t0.1_s1_af2pred       93   178    9   0.7447         823      5.86 Å
  orient_255_pt12__33_pt12__60_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     21.57 Å
  orient_255_pt12__33_pt12__60_a1_t0.1_s5_af2pred       93   178    9   0.8404         799      4.68 Å
  orient_255_pt12__33_pt12__60_a1_t0.1_s7_af2pred       93   178    9   0.7446         785      6.31 Å
  orient_255_pt12__33_pt12__60_a1_t0.1_s8_af2pred       93   178    9   0.3679         387     12.66 Å
  orient_255_pt12__33_pt12__60_a2_t0.1_s2_af2pred       93   178    9   0.7423         800      6.13 Å
  orient_255_pt12__33_pt12__60_a2_t0.1_s8_af2pred       93   178    9   0.6053         730      8.81 Å
  orient_255_pt12__33_pt12__60_a3_t0.1_s4_af2pred       93   178    9   0.7992         790      5.42 Å

  orient_255_pt12__33_pt12__60_a3_t0.1_s5_af2pred       93   178    9   0.7748         798      5.73 Å
  orient_255_pt12__33_pt12__61_a1_t0.1_s1_af2pred       93   178    9   0.4577         519     11.27 Å
  orient_255_pt12__33_pt12__61_a1_t0.1_s2_af2pred       93   178    9   0.8148         817      4.84 Å
  orient_255_pt12__33_pt12__61_a1_t0.1_s4_af2pred       93   178    9   0.0020          12     19.73 Å
  orient_255_pt12__33_pt12__61_a2_t0.1_s1_af2pred       93   178    9   0.2921         291     13.46 Å
  orient_255_pt12__33_pt12__61_a2_t0.1_s4_af2pred       93   178    9   0.7978         814      5.11 Å
  orient_255_pt12__33_pt12__61_a2_t0.1_s6_af2pred       93   178    9   0.8229         805      4.85 Å
  orient_255_pt12__33_pt12__61_a2_t0.1_s7_af2pred       93   178    9   0.8220         825      4.62 Å
  orient_255_pt12__33_pt12__61_a3_t0.1_s8_af2pred       93   178    9   0.5658         674      9.42 Å
  orient_255_pt12__33_pt12__66_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     22.05 Å
  orient_255_pt12__33_pt12__66_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     24.05 Å
  orient_255_pt12__33_pt12__66_a1_t0.1_s6_af2pred       93   178    9   0.8266         828      4.52 Å
  orient_255_pt12__33_pt12__66_a1_t0.1_s8_af2pred       93   178    9   0.7889         811      5.32 Å
  orient_255_pt12__33_pt12__66_a2_t0.1_s1_af2pred       93   178    9   0.6329         753      8.09 Å
  orient_255_pt12__33_pt12__66_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     22.13 Å
  orient_255_pt12__33_pt12__66_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     23.97 Å
  orient_255_pt12__33_pt12__66_a2_t0.1_s4_af2pred       93   178    9   0.7870         809      5.39 Å
  orient_255_pt12__33_pt12__67_a1_t0.1_s8_af2pred       93   178    9   0.0023           1     19.73 Å
  orient_255_pt12__33_pt12__67_a2_t0.1_s1_af2pred       93   178    9   0.8700         826      3.81 Å
  orient_255_pt12__33_pt12__67_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     21.66 Å
  orient_255_pt12__33_pt12__67_a3_t0.1_s8_af2pred       93   178    9   0.8818         834      3.52 Å
  orient_255_pt12__33_pt12__67_a4_t0.1_s2_af2pred       93   178    9   0.7599         822      5.61 Å
  orient_255_pt12__33_pt12__67_a5_t0.1_s5_af2pred       93   178    9   0.4433         537     11.18 Å
  orient_255_pt12__33_pt12__67_a6_t0.1_s7_af2pred       93   178    9   0.0000           0     22.66 Å
  orient_255_pt12__33_pt12__67_a7_t0.1_s2_af2pred       93   178    9   0.6898         801      6.84 Å
  orient_255_pt12__33_pt12__69_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     22.73 Å
  orient_255_pt12__33_pt12__69_a3_t0.1_s2_af2pred       93   178    9   0.0000           0     23.74 Å
  orient_255_pt12__33_pt12__69_a3_t0.1_s4_af2pred       93   178    9   0.0000           0     25.30 Å
  orient_255_pt12__33_pt12__69_a3_t0.1_s5_af2pred       93   178    9   0.0000           0     23.84 Å
  orient_255_pt12__33_pt12__69_a3_t0.1_s8_af2pred       93   178    9   0.0000           0     23.37 Å
  orient_255_pt12__33_pt12__69_a4_t0.1_s2_af2pred       93   178    9   0.0000           0     24.12 Å
  orient_255_pt12__33_pt12__69_a4_t0.1_s4_af2pred       93   178    9   0.0018           2     20.75 Å
  orient_255_pt12__33_pt12__69_a4_t0.1_s6_af2pred       93   178    9   0.0000           0     23.52 Å
  orient_255_pt12__33_pt12__73_a1_t0.1_s2_af2pred       93   178    9   0.0020           9     19.36 Å
  orient_255_pt12__33_pt12__73_a1_t0.1_s5_af2pred       93   178    9   0.5214         618     10.33 Å
  orient_255_pt12__33_pt12__73_a2_t0.1_s4_af2pred       93   178    9   0.5344         600     10.06 Å
  orient_255_pt12__33_pt12__73_a3_t0.1_s3_af2pred       93   178    9   0.7870         792      5.57 Å
  orient_255_pt12__33_pt12__73_a3_t0.1_s8_af2pred       93   178    9   0.7983         804      5.41 Å
  orient_255_pt12__33_pt12__73_a4_t0.1_s5_af2pred       93   178    9   0.2692         248     14.03 Å
  orient_255_pt12__33_pt12__73_a4_t0.1_s8_af2pred       93   178    9   0.6800         759      7.26 Å
  orient_255_pt12__33_pt12__73_a5_t0.1_s3_af2pred       93   178    9   0.8173         787      5.06 Å
  orient_255_pt12__33_pt12__76_a2_t0.1_s6_af2pred       93   178    9   0.8317         830      4.38 Å
  orient_255_pt12__33_pt12__76_a3_t0.1_s5_af2pred       93   178    9   0.0000           0     23.10 Å
  orient_255_pt12__33_pt12__76_a4_t0.1_s2_af2pred       93   178    9   0.0000           0     22.57 Å
  orient_255_pt12__33_pt12__76_a4_t0.1_s8_af2pred       93   178    9   0.3128         304     13.23 Å
  orient_255_pt12__33_pt12__76_a7_t0.1_s5_af2pred       93   178    9   0.0000           0     23.88 Å
  orient_255_pt12__33_pt12__76_a8_t0.1_s1_af2pred       93   178    9   0.0000           0     26.30 Å
  orient_255_pt12__33_pt12__76_a9_t0.1_s7_af2pred       93   178    9   0.0019           1     20.98 Å
  orient_255_pt12__33_pt12__76_a9_t0.1_s8_af2pred       93   178    9   0.7657         814      5.66 Å
  orient_255_pt12__33_pt12__77_a1_t0.1_s3_af2pred       93   178    9   0.0021          21     18.27 Å
  orient_255_pt12__33_pt12__77_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     23.06 Å
  orient_255_pt12__33_pt12__77_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     21.69 Å
  orient_255_pt12__33_pt12__77_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     22.73 Å
  orient_255_pt12__33_pt12__77_a1_t0.1_s8_af2pred       93   178    9   0.0022           4     19.09 Å
  orient_255_pt12__33_pt12__77_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     22.62 Å
  orient_255_pt12__33_pt12__77_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     22.93 Å
  orient_255_pt12__33_pt12__77_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     22.93 Å
  orient_255_pt12__33_pt12__7_a10_t0.1_s2_af2pred       93   178    9   0.8484         805      4.44 Å
  orient_255_pt12__33_pt12__7_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     22.45 Å
  orient_255_pt12__33_pt12__7_a1_t0.1_s8_af2pred        93   178    9   0.8723         774      4.78 Å
  orient_255_pt12__33_pt12__7_a2_t0.1_s1_af2pred        93   178    9   0.8831         836      3.45 Å
  orient_255_pt12__33_pt12__7_a3_t0.1_s5_af2pred        93   178    9   0.8765         832      3.62 Å
  orient_255_pt12__33_pt12__7_a4_t0.1_s4_af2pred        93   178    9   0.8940         820      3.52 Å
  orient_255_pt12__33_pt12__7_a6_t0.1_s7_af2pred        93   178    9   0.2324         202     14.17 Å
  orient_255_pt12__33_pt12__7_a9_t0.1_s7_af2pred        93   178    9   0.8459         819      4.37 Å
  orient_255_pt12__33_pt12__80_a1_t0.1_s1_af2pred       93   178    9   0.7365         789      6.46 Å
  orient_255_pt12__33_pt12__80_a1_t0.1_s3_af2pred       93   178    9   0.0022           7     19.67 Å
  orient_255_pt12__33_pt12__80_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     24.05 Å
  orient_255_pt12__33_pt12__80_a3_t0.1_s1_af2pred       93   178    9   0.0028           2     20.36 Å
  orient_255_pt12__33_pt12__80_a4_t0.1_s5_af2pred       93   178    9   0.8374         835      4.25 Å
  orient_255_pt12__33_pt12__80_a4_t0.1_s7_af2pred       93   178    9   0.0000           0     23.55 Å
  orient_255_pt12__33_pt12__80_a5_t0.1_s1_af2pred       93   178    9   0.5884         705      8.83 Å
  orient_255_pt12__33_pt12__80_a6_t0.1_s2_af2pred       93   178    9   0.0021           8     19.80 Å
  orient_255_pt12__33_pt12__81_a1_t0.1_s2_af2pred       93   178    9   0.7774         830      5.29 Å
  orient_255_pt12__33_pt12__81_a1_t0.1_s3_af2pred       93   178    9   0.8234         821      4.62 Å
  orient_255_pt12__33_pt12__81_a1_t0.1_s4_af2pred       93   178    9   0.8292         829      4.44 Å
  orient_255_pt12__33_pt12__81_a1_t0.1_s7_af2pred       93   178    9   0.8669         832      3.78 Å
  orient_255_pt12__33_pt12__81_a2_t0.1_s6_af2pred       93   178    9   0.8270         837      4.41 Å
  orient_255_pt12__33_pt12__81_a3_t0.1_s3_af2pred       93   178    9   0.8195         833      4.57 Å
  orient_255_pt12__33_pt12__81_a4_t0.1_s5_af2pred       93   178    9   0.8959         824      3.42 Å
  orient_255_pt12__33_pt12__81_a7_t0.1_s2_af2pred       93   178    9   0.8584         826      4.03 Å
  orient_255_pt12__33_pt12__82_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     23.50 Å
  orient_255_pt12__33_pt12__82_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     24.13 Å
  orient_255_pt12__33_pt12__82_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     23.76 Å
  orient_255_pt12__33_pt12__82_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     24.23 Å
  orient_255_pt12__33_pt12__82_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     24.91 Å
  orient_255_pt12__33_pt12__82_a3_t0.1_s5_af2pred       93   178    9   0.0000           0     20.93 Å
  orient_255_pt12__33_pt12__82_a3_t0.1_s8_af2pred       93   178    9   0.0000           0     25.39 Å
  orient_255_pt12__33_pt12__82_a4_t0.1_s2_af2pred       93   178    9   0.0000           0     22.60 Å

  orient_255_pt12__33_pt12__83_a1_t0.1_s7_af2pred       93   178    9   0.8111         806      5.02 Å
  orient_255_pt12__33_pt12__83_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     22.09 Å
  orient_255_pt12__33_pt12__83_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     23.52 Å
  orient_255_pt12__33_pt12__83_a3_t0.1_s4_af2pred       93   178    9   0.5268         624     10.15 Å
  orient_255_pt12__33_pt12__83_a3_t0.1_s8_af2pred       93   178    9   0.4903         559     10.78 Å
  orient_255_pt12__33_pt12__83_a4_t0.1_s2_af2pred       93   178    9   0.0000           0     23.46 Å
  orient_255_pt12__33_pt12__83_a4_t0.1_s6_af2pred       93   178    9   0.0000           0     24.62 Å
  orient_255_pt12__33_pt12__83_a5_t0.1_s1_af2pred       93   178    9   0.0000           0     23.98 Å
  orient_255_pt12__33_pt12__88_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     26.00 Å
  orient_255_pt12__33_pt12__88_a2_t0.1_s5_af2pred       93   178    9   0.1043          94     15.96 Å
  orient_255_pt12__33_pt12__88_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     26.15 Å
  orient_255_pt12__33_pt12__88_a3_t0.1_s5_af2pred       93   178    9   0.0017           1     21.49 Å
  orient_255_pt12__33_pt12__88_a3_t0.1_s7_af2pred       93   178    9   0.6933         778      7.17 Å
  orient_255_pt12__33_pt12__88_a4_t0.1_s2_af2pred       93   178    9   0.0000           0     23.64 Å
  orient_255_pt12__33_pt12__88_a4_t0.1_s6_af2pred       93   178    9   0.0000           0     26.00 Å
  orient_255_pt12__33_pt12__88_a5_t0.1_s6_af2pred       93   178    9   0.1948         170     15.09 Å
  orient_255_pt12__33_pt12__89_a1_t0.1_s3_af2pred       93   178    9   0.6830         799      7.00 Å
  orient_255_pt12__33_pt12__89_a1_t0.1_s4_af2pred       93   178    9   0.4560         539     11.57 Å
  orient_255_pt12__33_pt12__89_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     24.50 Å
  orient_255_pt12__33_pt12__89_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     22.50 Å
  orient_255_pt12__33_pt12__89_a2_t0.1_s1_af2pred       93   178    9   0.7658         820      5.56 Å
  orient_255_pt12__33_pt12__89_a2_t0.1_s2_af2pred       93   178    9   0.0431          48     17.47 Å
  orient_255_pt12__33_pt12__89_a2_t0.1_s6_af2pred       93   178    9   0.0018           2     20.10 Å
  orient_255_pt12__33_pt12__89_a3_t0.1_s4_af2pred       93   178    9   0.0000           0     26.20 Å
  orient_255_pt12__33_pt12__8_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     23.88 Å
  orient_255_pt12__33_pt12__8_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     22.61 Å
  orient_255_pt12__33_pt12__8_a2_t0.1_s1_af2pred        93   178    9   0.6948         807      6.80 Å
  orient_255_pt12__33_pt12__8_a2_t0.1_s4_af2pred        93   178    9   0.0233          36     17.78 Å
  orient_255_pt12__33_pt12__8_a2_t0.1_s6_af2pred        93   178    9   0.0024           2     19.70 Å
  orient_255_pt12__33_pt12__8_a3_t0.1_s2_af2pred        93   178    9   0.0000           0     20.17 Å
  orient_255_pt12__33_pt12__8_a3_t0.1_s3_af2pred        93   178    9   0.7694         822      5.47 Å
  orient_255_pt12__33_pt12__8_a3_t0.1_s4_af2pred        93   178    9   0.7428         819      5.98 Å
  orient_255_pt12__33_pt12__91_a11_t0.15_s2_af2pred      93   178    9   0.7641         817      5.61 Å
  orient_255_pt12__33_pt12__91_a12_t0.15_s1_af2pred      93   178    9   0.7702         825      5.43 Å
  orient_255_pt12__33_pt12__91_a19_t0.15_s5_af2pred      93   178    9   0.6488         782      7.60 Å
  orient_255_pt12__33_pt12__91_a20_t0.15_s2_af2pred      93   178    9   0.0129          29     17.16 Å
  orient_255_pt12__33_pt12__91_a20_t0.15_s3_af2pred      93   178    9   0.0138          31     16.41 Å
  orient_255_pt12__33_pt12__91_a2_t0.1_s2_af2pred       93   178    9   0.0024           3     20.27 Å
  orient_255_pt12__33_pt12__91_a3_t0.1_s3_af2pred       93   178    9   0.3704         392     12.36 Å
  orient_255_pt12__33_pt12__91_a6_t0.1_s6_af2pred       93   178    9   0.6047         747      8.39 Å
  orient_255_pt12__33_pt12__99_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     19.95 Å
  orient_255_pt12__33_pt12__99_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     22.07 Å
  orient_255_pt12__33_pt12__99_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     23.09 Å
  orient_255_pt12__33_pt12__99_a1_t0.1_s7_af2pred       93   178    9   0.7500         819      5.81 Å
  orient_255_pt12__33_pt12__99_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     21.94 Å
  orient_255_pt12__33_pt12__99_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.43 Å
  orient_255_pt12__33_pt12__99_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     24.64 Å
  orient_255_pt12__33_pt12__99_a2_t0.1_s4_af2pred       93   178    9   0.0022          18     18.90 Å
  orient_255_pt12__46_pt12__0_a1_t0.1_s1_af2pred        93   178    9   0.0019           2     21.54 Å
  orient_255_pt12__46_pt12__0_a1_t0.1_s2_af2pred        93   178    9   0.0027          22     18.17 Å
  orient_255_pt12__46_pt12__0_a1_t0.1_s3_af2pred        93   178    9   0.6896         793      6.92 Å
  orient_255_pt12__46_pt12__0_a1_t0.1_s4_af2pred        93   178    9   0.6310         751      8.07 Å
  orient_255_pt12__46_pt12__0_a1_t0.1_s5_af2pred        93   178    9   0.4146         396     12.53 Å
  orient_255_pt12__46_pt12__0_a1_t0.1_s6_af2pred        93   178    9   0.0000           0     21.59 Å
  orient_255_pt12__46_pt12__0_a1_t0.1_s7_af2pred        93   178    9   0.0000           0     23.17 Å
  orient_255_pt12__46_pt12__0_a1_t0.1_s8_af2pred        93   178    9   0.2086         186     15.13 Å
  orient_255_pt12__46_pt12__11_a1_t0.1_s1_af2pred       93   178    9   0.7635         814      5.68 Å
  orient_255_pt12__46_pt12__11_a1_t0.1_s5_af2pred       93   178    9   0.1681         149     15.18 Å
  orient_255_pt12__46_pt12__11_a1_t0.1_s7_af2pred       93   178    9   0.2503         250     14.11 Å
  orient_255_pt12__46_pt12__11_a1_t0.1_s8_af2pred       93   178    9   0.0022           4     19.47 Å
  orient_255_pt12__46_pt12__11_a2_t0.1_s1_af2pred       93   178    9   0.0019           2     19.89 Å
  orient_255_pt12__46_pt12__11_a2_t0.1_s2_af2pred       93   178    9   0.0020           3     19.64 Å
  orient_255_pt12__46_pt12__11_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     22.34 Å
  orient_255_pt12__46_pt12__11_a3_t0.1_s3_af2pred       93   178    9   0.8453         833      4.17 Å
  orient_255_pt12__46_pt12__12_a1_t0.1_s2_af2pred       93   178    9   0.4372         453     11.91 Å
  orient_255_pt12__46_pt12__12_a1_t0.1_s4_af2pred       93   178    9   0.8307         823      4.51 Å
  orient_255_pt12__46_pt12__12_a1_t0.1_s5_af2pred       93   178    9   0.6565         763      7.59 Å
  orient_255_pt12__46_pt12__12_a1_t0.1_s7_af2pred       93   178    9   0.8633         827      3.99 Å
  orient_255_pt12__46_pt12__12_a1_t0.1_s8_af2pred       93   178    9   0.8495         836      4.04 Å
  orient_255_pt12__46_pt12__12_a2_t0.1_s1_af2pred       93   178    9   0.2035         180     14.96 Å
  orient_255_pt12__46_pt12__12_a2_t0.1_s2_af2pred       93   178    9   0.8307         827      4.43 Å
  orient_255_pt12__46_pt12__12_a2_t0.1_s4_af2pred       93   178    9   0.8094         837      4.70 Å
  orient_255_pt12__46_pt12__17_a1_t0.1_s3_af2pred       93   178    9   0.0017           2     20.24 Å
  orient_255_pt12__46_pt12__17_a2_t0.1_s1_af2pred       93   178    9   0.5722         702      9.00 Å
  orient_255_pt12__46_pt12__17_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     21.86 Å
  orient_255_pt12__46_pt12__17_a2_t0.1_s8_af2pred       93   178    9   0.0206          35     17.31 Å
  orient_255_pt12__46_pt12__17_a3_t0.1_s4_af2pred       93   178    9   0.0019           6     18.76 Å
  orient_255_pt12__46_pt12__17_a4_t0.1_s1_af2pred       93   178    9   0.0021           6     19.60 Å
  orient_255_pt12__46_pt12__17_a4_t0.1_s2_af2pred       93   178    9   0.0429          52     16.74 Å
  orient_255_pt12__46_pt12__17_a5_t0.1_s3_af2pred       93   178    9   0.1765         146     15.19 Å
  orient_255_pt12__46_pt12__18_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     23.02 Å
  orient_255_pt12__46_pt12__18_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     23.26 Å
  orient_255_pt12__46_pt12__18_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     22.64 Å
  orient_255_pt12__46_pt12__18_a1_t0.1_s6_af2pred       93   178    9   0.7361         823      6.03 Å

  orient_255_pt12__46_pt12__18_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     21.61 Å
  orient_255_pt12__46_pt12__18_a2_t0.1_s5_af2pred       93   178    9   0.0000           0     22.68 Å
  orient_255_pt12__46_pt12__18_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     21.48 Å
  orient_255_pt12__46_pt12__18_a2_t0.1_s7_af2pred       93   178    9   0.6451         755      7.82 Å
  orient_255_pt12__46_pt12__19_a1_t0.1_s6_af2pred       93   178    9   0.5171         646      9.98 Å
  orient_255_pt12__46_pt12__19_a1_t0.1_s7_af2pred       93   178    9   0.0022          18     18.41 Å
  orient_255_pt12__46_pt12__19_a1_t0.1_s8_af2pred       93   178    9   0.6054         749      8.40 Å
  orient_255_pt12__46_pt12__19_a2_t0.1_s1_af2pred       93   178    9   0.3600         386     12.47 Å
  orient_255_pt12__46_pt12__19_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     21.94 Å
  orient_255_pt12__46_pt12__19_a2_t0.1_s5_af2pred       93   178    9   0.0000           0     22.92 Å
  orient_255_pt12__46_pt12__19_a2_t0.1_s6_af2pred       93   178    9   0.6425         789      7.66 Å
  orient_255_pt12__46_pt12__19_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     23.04 Å
  orient_255_pt12__46_pt12__1_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     21.89 Å
  orient_255_pt12__46_pt12__1_a1_t0.1_s4_af2pred        93   178    9   0.3119         300     13.35 Å
  orient_255_pt12__46_pt12__1_a1_t0.1_s7_af2pred        93   178    9   0.7689         804      5.73 Å
  orient_255_pt12__46_pt12__1_a1_t0.1_s8_af2pred        93   178    9   0.4710         569     10.79 Å
  orient_255_pt12__46_pt12__1_a2_t0.1_s4_af2pred        93   178    9   0.1807         159     14.94 Å
  orient_255_pt12__46_pt12__1_a3_t0.1_s1_af2pred        93   178    9   0.7132         804      6.54 Å
  orient_255_pt12__46_pt12__1_a3_t0.1_s2_af2pred        93   178    9   0.1095          99     15.84 Å
  orient_255_pt12__46_pt12__1_a3_t0.1_s3_af2pred        93   178    9   0.6487         744      8.18 Å
  orient_255_pt12__46_pt12__20_a11_t0.15_s4_af2pred      93   178    9   0.1777         160     15.14 Å
  orient_255_pt12__46_pt12__20_a16_t0.15_s8_af2pred      93   178    9   0.0000           0     22.55 Å
  orient_255_pt12__46_pt12__20_a28_t0.2_s3_af2pred      93   178    9   0.0000           0     23.66 Å
  orient_255_pt12__46_pt12__20_a7_t0.1_s7_af2pred       93   178    9   0.0000           0     22.86 Å
  orient_255_pt12__46_pt12__21_a1_t0.1_s1_af2pred       93   178    9   0.6599         748      7.70 Å
  orient_255_pt12__46_pt12__21_a1_t0.1_s3_af2pred       93   178    9   0.6322         720      8.34 Å
  orient_255_pt12__46_pt12__21_a1_t0.1_s4_af2pred       93   178    9   0.7511         807      5.91 Å
  orient_255_pt12__46_pt12__21_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     21.47 Å
  orient_255_pt12__46_pt12__21_a2_t0.1_s1_af2pred       93   178    9   0.0767          74     16.55 Å
  orient_255_pt12__46_pt12__21_a2_t0.1_s3_af2pred       93   178    9   0.7724         805      5.73 Å
  orient_255_pt12__46_pt12__21_a2_t0.1_s4_af2pred       93   178    9   0.3304         335     13.62 Å
  orient_255_pt12__46_pt12__21_a2_t0.1_s5_af2pred       93   178    9   0.0000           0     21.13 Å
  orient_255_pt12__46_pt12__24_a1_t0.1_s3_af2pred       93   178    9   0.7410         805      6.08 Å
  orient_255_pt12__46_pt12__24_a1_t0.1_s7_af2pred       93   178    9   0.7310         803      6.40 Å
  orient_255_pt12__46_pt12__24_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     21.23 Å
  orient_255_pt12__46_pt12__24_a2_t0.1_s4_af2pred       93   178    9   0.7260         810      6.28 Å
  orient_255_pt12__46_pt12__24_a3_t0.1_s4_af2pred       93   178    9   0.4128         461     11.83 Å
  orient_255_pt12__46_pt12__24_a4_t0.1_s8_af2pred       93   178    9   0.7958         800      5.45 Å
  orient_255_pt12__46_pt12__24_a5_t0.1_s4_af2pred       93   178    9   0.0555          59     16.58 Å
  orient_255_pt12__46_pt12__24_a5_t0.1_s8_af2pred       93   178    9   0.0343          44     17.01 Å
  orient_255_pt12__46_pt12__25_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     25.36 Å
  orient_255_pt12__46_pt12__25_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     22.28 Å
  orient_255_pt12__46_pt12__25_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     23.78 Å
  orient_255_pt12__46_pt12__25_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     27.00 Å
  orient_255_pt12__46_pt12__25_a3_t0.1_s5_af2pred       93   178    9   0.0000           0     22.88 Å
  orient_255_pt12__46_pt12__25_a4_t0.1_s4_af2pred       93   178    9   0.0000           0     23.10 Å
  orient_255_pt12__46_pt12__25_a5_t0.1_s8_af2pred       93   178    9   0.0021           4     19.03 Å
  orient_255_pt12__46_pt12__25_a6_t0.1_s1_af2pred       93   178    9   0.0000           0     23.05 Å
  orient_255_pt12__46_pt12__26_a1_t0.1_s2_af2pred       93   178    9   0.8118         820      4.82 Å
  orient_255_pt12__46_pt12__26_a1_t0.1_s3_af2pred       93   178    9   0.4707         527     11.09 Å
  orient_255_pt12__46_pt12__26_a1_t0.1_s4_af2pred       93   178    9   0.4731         563     10.89 Å
  orient_255_pt12__46_pt12__26_a1_t0.1_s7_af2pred       93   178    9   0.7657         806      5.73 Å
  orient_255_pt12__46_pt12__26_a2_t0.1_s1_af2pred       93   178    9   0.5603         650      9.64 Å
  orient_255_pt12__46_pt12__26_a2_t0.1_s2_af2pred       93   178    9   0.0017           1     21.39 Å
  orient_255_pt12__46_pt12__26_a2_t0.1_s3_af2pred       93   178    9   0.0287          40     17.24 Å
  orient_255_pt12__46_pt12__26_a2_t0.1_s4_af2pred       93   178    9   0.6596         780      7.60 Å
  orient_255_pt12__46_pt12__27_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     20.62 Å
  orient_255_pt12__46_pt12__27_a1_t0.1_s2_af2pred       93   178    9   0.8468         821      4.34 Å
  orient_255_pt12__46_pt12__27_a1_t0.1_s4_af2pred       93   178    9   0.6872         763      7.48 Å
  orient_255_pt12__46_pt12__27_a1_t0.1_s5_af2pred       93   178    9   0.0088          27     18.65 Å
  orient_255_pt12__46_pt12__27_a2_t0.1_s4_af2pred       93   178    9   0.0887          87     16.36 Å
  orient_255_pt12__46_pt12__27_a2_t0.1_s8_af2pred       93   178    9   0.6272         724      8.38 Å
  orient_255_pt12__46_pt12__27_a3_t0.1_s3_af2pred       93   178    9   0.7565         779      6.19 Å
  orient_255_pt12__46_pt12__27_a3_t0.1_s5_af2pred       93   178    9   0.0018           1     19.96 Å
  orient_255_pt12__46_pt12__28_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     23.08 Å
  orient_255_pt12__46_pt12__28_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     23.28 Å
  orient_255_pt12__46_pt12__28_a3_t0.1_s8_af2pred       93   178    9   0.0000           0     23.36 Å
  orient_255_pt12__46_pt12__28_a4_t0.1_s4_af2pred       93   178    9   0.0000           0     22.89 Å
  orient_255_pt12__46_pt12__28_a5_t0.1_s3_af2pred       93   178    9   0.0021           4     18.96 Å
  orient_255_pt12__46_pt12__28_a5_t0.1_s8_af2pred       93   178    9   0.6852         731      7.90 Å
  orient_255_pt12__46_pt12__28_a7_t0.1_s6_af2pred       93   178    9   0.0000           0     23.24 Å
  orient_255_pt12__46_pt12__28_a8_t0.1_s1_af2pred       93   178    9   0.0018           1     21.05 Å
  orient_255_pt12__46_pt12__33_a15_t0.15_s8_af2pred      93   178    9   0.0000           0     25.74 Å
  orient_255_pt12__46_pt12__33_a16_t0.15_s1_af2pred      93   178    9   0.5390         681      9.57 Å
  orient_255_pt12__46_pt12__33_a28_t0.2_s1_af2pred      93   178    9   0.4301         500     11.49 Å
  orient_255_pt12__46_pt12__33_a28_t0.2_s6_af2pred      93   178    9   0.0000           0     22.36 Å
  orient_255_pt12__46_pt12__33_a29_t0.2_s4_af2pred      93   178    9   0.0000           0     22.57 Å
  orient_255_pt12__46_pt12__33_a5_t0.1_s5_af2pred       93   178    9   0.0000           0     23.76 Å
  orient_255_pt12__46_pt12__33_a8_t0.1_s5_af2pred       93   178    9   0.0000           0     21.63 Å
  orient_255_pt12__46_pt12__33_a8_t0.1_s7_af2pred       93   178    9   0.6917         789      6.97 Å
  orient_255_pt12__46_pt12__39_a10_t0.1_s4_af2pred      93   178    9   0.0254          38     17.60 Å

  orient_255_pt12__46_pt12__39_a10_t0.1_s7_af2pred      93   178    9   0.0000           0     21.10 Å
  orient_255_pt12__46_pt12__39_a17_t0.15_s2_af2pred      93   178    9   0.3573         360     12.82 Å
  orient_255_pt12__46_pt12__39_a20_t0.15_s6_af2pred      93   178    9   0.0000           0     25.56 Å
  orient_255_pt12__46_pt12__39_a21_t0.2_s2_af2pred      93   178    9   0.0000           0     23.76 Å
  orient_255_pt12__46_pt12__39_a3_t0.1_s3_af2pred       93   178    9   0.4715         514     11.21 Å
  orient_255_pt12__46_pt12__39_a5_t0.1_s8_af2pred       93   178    9   0.0000           0     24.84 Å
  orient_255_pt12__46_pt12__39_a9_t0.1_s2_af2pred       93   178    9   0.0000           0     23.26 Å
  orient_255_pt12__46_pt12__41_a1_t0.1_s2_af2pred       93   178    9   0.6882         792      7.03 Å
  orient_255_pt12__46_pt12__41_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     24.78 Å
  orient_255_pt12__46_pt12__41_a1_t0.1_s4_af2pred       93   178    9   0.7991         803      5.25 Å
  orient_255_pt12__46_pt12__41_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     24.35 Å
  orient_255_pt12__46_pt12__41_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     23.87 Å
  orient_255_pt12__46_pt12__41_a2_t0.1_s2_af2pred       93   178    9   0.7820         791      5.58 Å
  orient_255_pt12__46_pt12__41_a2_t0.1_s4_af2pred       93   178    9   0.8382         819      4.52 Å
  orient_255_pt12__46_pt12__41_a2_t0.1_s5_af2pred       93   178    9   0.0020           3     20.68 Å
  orient_255_pt12__46_pt12__42_a1_t0.1_s4_af2pred       93   178    9   0.7751         820      5.38 Å
  orient_255_pt12__46_pt12__42_a1_t0.1_s5_af2pred       93   178    9   0.8231         822      4.63 Å
  orient_255_pt12__46_pt12__42_a1_t0.1_s7_af2pred       93   178    9   0.6556         767      7.66 Å
  orient_255_pt12__46_pt12__42_a2_t0.1_s5_af2pred       93   178    9   0.8335         828      4.41 Å
  orient_255_pt12__46_pt12__42_a2_t0.1_s8_af2pred       93   178    9   0.8095         819      4.96 Å
  orient_255_pt12__46_pt12__42_a3_t0.1_s5_af2pred       93   178    9   0.7790         828      5.29 Å
  orient_255_pt12__46_pt12__42_a4_t0.1_s5_af2pred       93   178    9   0.6289         773      7.96 Å
  orient_255_pt12__46_pt12__42_a4_t0.1_s8_af2pred       93   178    9   0.0000           0     22.39 Å
  orient_255_pt12__46_pt12__44_a1_t0.1_s1_af2pred       93   178    9   0.5131         608     10.30 Å
  orient_255_pt12__46_pt12__44_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     20.46 Å
  orient_255_pt12__46_pt12__44_a1_t0.1_s3_af2pred       93   178    9   0.7191         807      6.35 Å
  orient_255_pt12__46_pt12__44_a1_t0.1_s4_af2pred       93   178    9   0.6974         789      6.88 Å
  orient_255_pt12__46_pt12__44_a1_t0.1_s5_af2pred       93   178    9   0.8295         819      4.53 Å
  orient_255_pt12__46_pt12__44_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     22.72 Å
  orient_255_pt12__46_pt12__44_a1_t0.1_s7_af2pred       93   178    9   0.8606         828      3.96 Å
  orient_255_pt12__46_pt12__44_a1_t0.1_s8_af2pred       93   178    9   0.7660         824      5.50 Å
  orient_255_pt12__46_pt12__47_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     21.82 Å
  orient_255_pt12__46_pt12__47_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     20.77 Å
  orient_255_pt12__46_pt12__47_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     22.91 Å
  orient_255_pt12__46_pt12__47_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     22.62 Å
  orient_255_pt12__46_pt12__47_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     22.34 Å
  orient_255_pt12__46_pt12__47_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     23.31 Å
  orient_255_pt12__46_pt12__47_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     22.32 Å
  orient_255_pt12__46_pt12__47_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     20.96 Å
  orient_255_pt12__46_pt12__49_a11_t0.15_s2_af2pred      93   178    9   0.0021           5     19.46 Å
  orient_255_pt12__46_pt12__49_a11_t0.15_s5_af2pred      93   178    9   0.0000           0     22.16 Å
  orient_255_pt12__46_pt12__49_a11_t0.15_s6_af2pred      93   178    9   0.3763         418     12.24 Å
  orient_255_pt12__46_pt12__49_a12_t0.15_s2_af2pred      93   178    9   0.0000           0     23.23 Å
  orient_255_pt12__46_pt12__49_a14_t0.15_s1_af2pred      93   178    9   0.0000           0     24.05 Å
  orient_255_pt12__46_pt12__49_a16_t0.15_s5_af2pred      93   178    9   0.0000           0     22.71 Å
  orient_255_pt12__46_pt12__49_a22_t0.2_s1_af2pred      93   178    9   0.6957         790      6.87 Å
  orient_255_pt12__46_pt12__49_a9_t0.1_s2_af2pred       93   178    9   0.0000           0     22.29 Å
  orient_255_pt12__46_pt12__50_a7_t0.1_s8_af2pred       93   178    9   0.0000           0     20.75 Å
  orient_255_pt12__46_pt12__51_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     22.79 Å
  orient_255_pt12__46_pt12__51_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     24.06 Å
  orient_255_pt12__46_pt12__51_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     23.89 Å
  orient_255_pt12__46_pt12__51_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     23.25 Å
  orient_255_pt12__46_pt12__51_a3_t0.1_s2_af2pred       93   178    9   0.0000           0     23.41 Å
  orient_255_pt12__46_pt12__51_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     23.50 Å
  orient_255_pt12__46_pt12__51_a3_t0.1_s4_af2pred       93   178    9   0.0000           0     24.70 Å
  orient_255_pt12__46_pt12__51_a4_t0.1_s1_af2pred       93   178    9   0.0000           0     23.45 Å
  orient_255_pt12__46_pt12__53_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     21.47 Å
  orient_255_pt12__46_pt12__53_a1_t0.1_s2_af2pred       93   178    9   0.0017           1     20.11 Å
  orient_255_pt12__46_pt12__53_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     23.49 Å
  orient_255_pt12__46_pt12__53_a1_t0.1_s4_af2pred       93   178    9   0.7921         828      5.13 Å
  orient_255_pt12__46_pt12__53_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     21.64 Å
  orient_255_pt12__46_pt12__53_a1_t0.1_s8_af2pred       93   178    9   0.7194         798      6.40 Å
  orient_255_pt12__46_pt12__53_a2_t0.1_s1_af2pred       93   178    9   0.1202         108     16.49 Å
  orient_255_pt12__46_pt12__53_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     21.85 Å
  orient_255_pt12__46_pt12__54_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     24.20 Å
  orient_255_pt12__46_pt12__54_a1_t0.1_s3_af2pred       93   178    9   0.6949         782      6.95 Å
  orient_255_pt12__46_pt12__54_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     23.64 Å
  orient_255_pt12__46_pt12__54_a1_t0.1_s5_af2pred       93   178    9   0.0019          14     18.10 Å
  orient_255_pt12__46_pt12__54_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     24.08 Å
  orient_255_pt12__46_pt12__54_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     24.26 Å
  orient_255_pt12__46_pt12__54_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     25.85 Å
  orient_255_pt12__46_pt12__54_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     26.13 Å
  orient_255_pt12__46_pt12__58_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     24.59 Å
  orient_255_pt12__46_pt12__58_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     24.75 Å
  orient_255_pt12__46_pt12__58_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     24.06 Å
  orient_255_pt12__46_pt12__58_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     24.16 Å
  orient_255_pt12__46_pt12__58_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     26.31 Å
  orient_255_pt12__46_pt12__58_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     27.32 Å
  orient_255_pt12__46_pt12__58_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     26.36 Å
  orient_255_pt12__46_pt12__58_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     23.89 Å
  orient_255_pt12__46_pt12__62_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     21.23 Å
  orient_255_pt12__46_pt12__62_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     22.66 Å
  orient_255_pt12__46_pt12__62_a1_t0.1_s7_af2pred       93   178    9   0.6084         719      8.47 Å
  orient_255_pt12__46_pt12__62_a1_t0.1_s8_af2pred       93   178    9   0.5502         667      9.60 Å
  orient_255_pt12__46_pt12__62_a2_t0.1_s1_af2pred       93   178    9   0.5946         713      8.74 Å
  orient_255_pt12__46_pt12__62_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     21.16 Å

  orient_255_pt12__46_pt12__62_a2_t0.1_s4_af2pred       93   178    9   0.6615         771      7.46 Å
  orient_255_pt12__46_pt12__62_a2_t0.1_s7_af2pred       93   178    9   0.3789         384     12.79 Å
  orient_255_pt12__46_pt12__64_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     21.78 Å
  orient_255_pt12__46_pt12__64_a2_t0.1_s8_af2pred       93   178    9   0.0271          39     17.47 Å
  orient_255_pt12__46_pt12__64_a4_t0.1_s2_af2pred       93   178    9   0.0000           0     23.27 Å
  orient_255_pt12__46_pt12__64_a5_t0.1_s5_af2pred       93   178    9   0.0000           0     20.99 Å
  orient_255_pt12__46_pt12__64_a7_t0.1_s2_af2pred       93   178    9   0.0000           0     21.81 Å
  orient_255_pt12__46_pt12__64_a7_t0.1_s3_af2pred       93   178    9   0.0000           0     21.49 Å
  orient_255_pt12__46_pt12__64_a7_t0.1_s7_af2pred       93   178    9   0.0000           0     20.85 Å
  orient_255_pt12__46_pt12__64_a8_t0.1_s5_af2pred       93   178    9   0.0000           0     22.73 Å
  orient_255_pt12__46_pt12__69_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     22.18 Å
  orient_255_pt12__46_pt12__69_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     25.04 Å
  orient_255_pt12__46_pt12__69_a1_t0.1_s4_af2pred       93   178    9   0.1922         175     15.04 Å
  orient_255_pt12__46_pt12__69_a1_t0.1_s6_af2pred       93   178    9   0.0019           1     19.98 Å
  orient_255_pt12__46_pt12__69_a1_t0.1_s7_af2pred       93   178    9   0.7043         793      6.73 Å
  orient_255_pt12__46_pt12__69_a2_t0.1_s1_af2pred       93   178    9   0.5677         666      9.51 Å
  orient_255_pt12__46_pt12__69_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     22.14 Å
  orient_255_pt12__46_pt12__69_a2_t0.1_s4_af2pred       93   178    9   0.6978         781      6.98 Å
  orient_255_pt12__46_pt12__6_a1_t0.1_s2_af2pred        93   178    9   0.0505          56     16.95 Å
  orient_255_pt12__46_pt12__6_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     23.65 Å
  orient_255_pt12__46_pt12__6_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     22.25 Å
  orient_255_pt12__46_pt12__6_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     22.88 Å
  orient_255_pt12__46_pt12__6_a1_t0.1_s7_af2pred        93   178    9   0.0000           0     22.72 Å
  orient_255_pt12__46_pt12__6_a1_t0.1_s8_af2pred        93   178    9   0.0000           0     22.68 Å
  orient_255_pt12__46_pt12__6_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     23.59 Å
  orient_255_pt12__46_pt12__6_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     21.76 Å
  orient_255_pt12__46_pt12__76_a1_t0.1_s3_af2pred       93   178    9   0.2922         290     13.38 Å
  orient_255_pt12__46_pt12__76_a1_t0.1_s4_af2pred       93   178    9   0.6480         716      8.20 Å
  orient_255_pt12__46_pt12__76_a1_t0.1_s6_af2pred       93   178    9   0.4680         552     10.87 Å
  orient_255_pt12__46_pt12__76_a1_t0.1_s7_af2pred       93   178    9   0.0147          31     17.49 Å
  orient_255_pt12__46_pt12__76_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     20.24 Å
  orient_255_pt12__46_pt12__76_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     21.22 Å
  orient_255_pt12__46_pt12__76_a2_t0.1_s6_af2pred       93   178    9   0.6422         771      7.78 Å
  orient_255_pt12__46_pt12__76_a2_t0.1_s7_af2pred       93   178    9   0.0018           1     20.10 Å
  orient_255_pt12__46_pt12__7_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     22.91 Å
  orient_255_pt12__46_pt12__7_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     22.54 Å
  orient_255_pt12__46_pt12__7_a1_t0.1_s6_af2pred        93   178    9   0.0307          42     17.11 Å
  orient_255_pt12__46_pt12__7_a1_t0.1_s8_af2pred        93   178    9   0.0022          12     18.97 Å
  orient_255_pt12__46_pt12__7_a2_t0.1_s2_af2pred        93   178    9   0.0018           1     21.18 Å
  orient_255_pt12__46_pt12__7_a2_t0.1_s4_af2pred        93   178    9   0.0000           0     21.21 Å
  orient_255_pt12__46_pt12__7_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     20.54 Å
  orient_255_pt12__46_pt12__7_a3_t0.1_s1_af2pred        93   178    9   0.0000           0     22.86 Å
  orient_255_pt12__46_pt12__82_a1_t0.1_s3_af2pred       93   178    9   0.0021           3     19.50 Å
  orient_255_pt12__46_pt12__82_a2_t0.1_s7_af2pred       93   178    9   0.3607         375     12.90 Å
  orient_255_pt12__46_pt12__82_a2_t0.1_s8_af2pred       93   178    9   0.8051         802      5.18 Å
  orient_255_pt12__46_pt12__82_a3_t0.1_s2_af2pred       93   178    9   0.8146         815      4.86 Å
  orient_255_pt12__46_pt12__82_a3_t0.1_s3_af2pred       93   178    9   0.8562         828      4.01 Å
  orient_255_pt12__46_pt12__82_a3_t0.1_s4_af2pred       93   178    9   0.5921         682      9.10 Å
  orient_255_pt12__46_pt12__82_a4_t0.1_s1_af2pred       93   178    9   0.7576         779      6.22 Å
  orient_255_pt12__46_pt12__82_a4_t0.1_s3_af2pred       93   178    9   0.7098         790      6.70 Å
  orient_255_pt12__46_pt12__97_a1_t0.1_s2_af2pred       93   178    9   0.0127          30     17.71 Å
  orient_255_pt12__46_pt12__97_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     21.94 Å
  orient_255_pt12__46_pt12__97_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     20.57 Å
  orient_255_pt12__46_pt12__97_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     21.82 Å
  orient_255_pt12__46_pt12__97_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.02 Å
  orient_255_pt12__46_pt12__97_a2_t0.1_s2_af2pred       93   178    9   0.0019           2     20.29 Å
  orient_255_pt12__46_pt12__97_a2_t0.1_s4_af2pred       93   178    9   0.2522         235     14.45 Å
  orient_255_pt12__46_pt12__97_a2_t0.1_s6_af2pred       93   178    9   0.0433          52     17.46 Å
  orient_255_pt12__46_pt12__98_a1_t0.1_s4_af2pred       93   178    9   0.6604         790      7.39 Å
  orient_255_pt12__46_pt12__98_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     20.99 Å
  orient_255_pt12__46_pt12__98_a2_t0.1_s2_af2pred       93   178    9   0.0826          78     16.86 Å
  orient_255_pt12__46_pt12__98_a3_t0.1_s2_af2pred       93   178    9   0.0000           0     22.43 Å
  orient_255_pt12__46_pt12__98_a3_t0.1_s8_af2pred       93   178    9   0.0000           0     21.80 Å
  orient_255_pt12__46_pt12__98_a4_t0.1_s1_af2pred       93   178    9   0.0000           0     21.25 Å
  orient_255_pt12__46_pt12__98_a4_t0.1_s7_af2pred       93   178    9   0.0018           2     20.04 Å
  orient_255_pt12__46_pt12__98_a4_t0.1_s8_af2pred       93   178    9   0.0019           5     19.11 Å
  orient_255_pt12__46_pt12__99_a1_t0.1_s3_af2pred       93   178    9   0.4762         554     11.03 Å
  orient_255_pt12__46_pt12__99_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     22.55 Å
  orient_255_pt12__46_pt12__99_a2_t0.1_s6_af2pred       93   178    9   0.7737         792      5.79 Å
  orient_255_pt12__46_pt12__99_a3_t0.1_s2_af2pred       93   178    9   0.8513         809      4.28 Å
  orient_255_pt12__46_pt12__99_a3_t0.1_s3_af2pred       93   178    9   0.8233         795      5.01 Å
  orient_255_pt12__46_pt12__99_a4_t0.1_s8_af2pred       93   178    9   0.0024           3     20.09 Å
  orient_255_pt12__46_pt12__99_a5_t0.1_s6_af2pred       93   178    9   0.0000           0     22.20 Å
  orient_255_pt12__46_pt12__99_a5_t0.1_s8_af2pred       93   178    9   0.8181         799      5.02 Å
  orient_255_pt12__53_pt25__0_a19_t0.15_s1_af2pred      93   178    9   0.0000           0     23.80 Å
  orient_255_pt12__53_pt25__10_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     23.19 Å
  orient_255_pt12__53_pt25__10_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     20.94 Å
  orient_255_pt12__53_pt25__10_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     21.46 Å
  orient_255_pt12__53_pt25__10_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     22.23 Å
  orient_255_pt12__53_pt25__10_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     22.25 Å
  orient_255_pt12__53_pt25__10_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.59 Å
  orient_255_pt12__53_pt25__10_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     22.50 Å
  orient_255_pt12__53_pt25__10_a2_t0.1_s5_af2pred       93   178    9   0.0000           0     21.45 Å
  orient_255_pt12__53_pt25__11_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     22.56 Å
  orient_255_pt12__53_pt25__11_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     25.18 Å

  orient_255_pt12__53_pt25__11_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     21.77 Å
  orient_255_pt12__53_pt25__11_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     20.54 Å
  orient_255_pt12__53_pt25__11_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.39 Å
  orient_255_pt12__53_pt25__11_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     23.78 Å
  orient_255_pt12__53_pt25__11_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     25.29 Å
  orient_255_pt12__53_pt25__11_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     24.57 Å
  orient_255_pt12__53_pt25__15_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     22.68 Å
  orient_255_pt12__53_pt25__15_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     22.12 Å
  orient_255_pt12__53_pt25__15_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     23.33 Å
  orient_255_pt12__53_pt25__15_a2_t0.1_s8_af2pred       93   178    9   0.0000           0     22.55 Å
  orient_255_pt12__53_pt25__15_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     23.02 Å
  orient_255_pt12__53_pt25__15_a4_t0.1_s4_af2pred       93   178    9   0.0000           0     23.29 Å
  orient_255_pt12__53_pt25__15_a4_t0.1_s6_af2pred       93   178    9   0.0000           0     24.10 Å
  orient_255_pt12__53_pt25__15_a5_t0.1_s1_af2pred       93   178    9   0.0000           0     22.71 Å
  orient_255_pt12__53_pt25__17_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     23.71 Å
  orient_255_pt12__53_pt25__17_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     22.22 Å
  orient_255_pt12__53_pt25__17_a3_t0.1_s7_af2pred       93   178    9   0.0000           0     24.63 Å
  orient_255_pt12__53_pt25__17_a5_t0.1_s5_af2pred       93   178    9   0.0000           0     23.89 Å
  orient_255_pt12__53_pt25__17_a6_t0.1_s4_af2pred       93   178    9   0.0000           0     23.50 Å
  orient_255_pt12__53_pt25__17_a6_t0.1_s7_af2pred       93   178    9   0.0000           0     22.84 Å
  orient_255_pt12__53_pt25__17_a6_t0.1_s8_af2pred       93   178    9   0.0000           0     23.62 Å
  orient_255_pt12__53_pt25__17_a7_t0.1_s8_af2pred       93   178    9   0.0000           0     23.53 Å
  orient_255_pt12__53_pt25__18_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     24.71 Å
  orient_255_pt12__53_pt25__18_a2_t0.1_s2_af2pred       93   178    9   0.0177          33     17.79 Å
  orient_255_pt12__53_pt25__18_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     24.29 Å
  orient_255_pt12__53_pt25__18_a4_t0.1_s4_af2pred       93   178    9   0.0000           0     23.48 Å
  orient_255_pt12__53_pt25__18_a4_t0.1_s5_af2pred       93   178    9   0.0000           0     23.43 Å
  orient_255_pt12__53_pt25__18_a4_t0.1_s6_af2pred       93   178    9   0.0019           2     21.92 Å
  orient_255_pt12__53_pt25__18_a4_t0.1_s7_af2pred       93   178    9   0.0000           0     23.58 Å
  orient_255_pt12__53_pt25__18_a6_t0.1_s7_af2pred       93   178    9   0.0000           0     23.24 Å
  orient_255_pt12__53_pt25__19_a1_t0.1_s7_af2pred       93   178    9   0.8254         791      4.92 Å
  orient_255_pt12__53_pt25__19_a3_t0.1_s1_af2pred       93   178    9   0.6872         750      7.20 Å
  orient_255_pt12__53_pt25__19_a3_t0.1_s3_af2pred       93   178    9   0.8027         789      5.34 Å
  orient_255_pt12__53_pt25__19_a4_t0.1_s7_af2pred       93   178    9   0.8266         822      4.54 Å
  orient_255_pt12__53_pt25__19_a6_t0.1_s1_af2pred       93   178    9   0.0000           0     22.79 Å
  orient_255_pt12__53_pt25__19_a6_t0.1_s4_af2pred       93   178    9   0.6813         812      6.94 Å
  orient_255_pt12__53_pt25__19_a7_t0.1_s2_af2pred       93   178    9   0.8527         789      4.45 Å
  orient_255_pt12__53_pt25__19_a7_t0.1_s7_af2pred       93   178    9   0.7334         778      6.37 Å
  orient_255_pt12__53_pt25__22_a11_t0.15_s4_af2pred      93   178    9   0.0000           0     25.64 Å
  orient_255_pt12__53_pt25__22_a13_t0.15_s6_af2pred      93   178    9   0.0000           0     26.11 Å
  orient_255_pt12__53_pt25__22_a17_t0.15_s1_af2pred      93   178    9   0.0000           0     22.35 Å
  orient_255_pt12__53_pt25__22_a18_t0.15_s3_af2pred      93   178    9   0.0000           0     26.41 Å
  orient_255_pt12__53_pt25__22_a18_t0.15_s6_af2pred      93   178    9   0.0000           0     22.54 Å
  orient_255_pt12__53_pt25__22_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     24.62 Å
  orient_255_pt12__53_pt25__22_a4_t0.1_s4_af2pred       93   178    9   0.0000           0     24.06 Å
  orient_255_pt12__53_pt25__22_a9_t0.1_s2_af2pred       93   178    9   0.0000           0     24.35 Å
  orient_255_pt12__53_pt25__26_a10_t0.1_s1_af2pred      93   178    9   0.0000           0     22.85 Å
  orient_255_pt12__53_pt25__26_a14_t0.15_s4_af2pred      93   178    9   0.0000           0     22.17 Å
  orient_255_pt12__53_pt25__26_a14_t0.15_s7_af2pred      93   178    9   0.0000           0     22.39 Å
  orient_255_pt12__53_pt25__26_a16_t0.15_s7_af2pred      93   178    9   0.0018           3     20.98 Å
  orient_255_pt12__53_pt25__26_a1_t0.1_s3_af2pred       93   178    9   0.7495         790      6.27 Å
  orient_255_pt12__53_pt25__26_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     22.39 Å
  orient_255_pt12__53_pt25__26_a5_t0.1_s6_af2pred       93   178    9   0.0020           7     19.07 Å
  orient_255_pt12__53_pt25__26_a7_t0.1_s6_af2pred       93   178    9   0.0000           0     22.30 Å
  orient_255_pt12__53_pt25__28_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     21.47 Å
  orient_255_pt12__53_pt25__28_a3_t0.1_s4_af2pred       93   178    9   0.0000           0     22.73 Å
  orient_255_pt12__53_pt25__28_a4_t0.1_s4_af2pred       93   178    9   0.0000           0     21.80 Å
  orient_255_pt12__53_pt25__28_a6_t0.1_s3_af2pred       93   178    9   0.0000           0     21.51 Å
  orient_255_pt12__53_pt25__28_a6_t0.1_s7_af2pred       93   178    9   0.0000           0     24.05 Å
  orient_255_pt12__53_pt25__28_a7_t0.1_s1_af2pred       93   178    9   0.0000           0     22.94 Å
  orient_255_pt12__53_pt25__28_a8_t0.1_s5_af2pred       93   178    9   0.0000           0     24.40 Å
  orient_255_pt12__53_pt25__28_a9_t0.1_s2_af2pred       93   178    9   0.0000           0     23.79 Å
  orient_255_pt12__53_pt25__29_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     20.28 Å
  orient_255_pt12__53_pt25__29_a1_t0.1_s4_af2pred       93   178    9   0.0020          18     18.52 Å
  orient_255_pt12__53_pt25__29_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     22.46 Å
  orient_255_pt12__53_pt25__29_a2_t0.1_s1_af2pred       93   178    9   0.0022           6     19.50 Å
  orient_255_pt12__53_pt25__29_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     22.98 Å
  orient_255_pt12__53_pt25__29_a2_t0.1_s8_af2pred       93   178    9   0.4779         540     11.14 Å
  orient_255_pt12__53_pt25__29_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.61 Å
  orient_255_pt12__53_pt25__29_a5_t0.1_s3_af2pred       93   178    9   0.0000           0     22.52 Å
  orient_255_pt12__53_pt25__31_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     23.57 Å
  orient_255_pt12__53_pt25__31_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     22.81 Å
  orient_255_pt12__53_pt25__31_a3_t0.1_s8_af2pred       93   178    9   0.0000           0     25.07 Å
  orient_255_pt12__53_pt25__31_a4_t0.1_s1_af2pred       93   178    9   0.0000           0     23.86 Å
  orient_255_pt12__53_pt25__31_a5_t0.1_s3_af2pred       93   178    9   0.0000           0     24.37 Å
  orient_255_pt12__53_pt25__31_a5_t0.1_s8_af2pred       93   178    9   0.0000           0     22.55 Å
  orient_255_pt12__53_pt25__31_a6_t0.1_s3_af2pred       93   178    9   0.0000           0     22.33 Å
  orient_255_pt12__53_pt25__31_a6_t0.1_s5_af2pred       93   178    9   0.0000           0     26.59 Å
  orient_255_pt12__53_pt25__33_a1_t0.1_s4_af2pred       93   178    9   0.0021           7     19.40 Å
  orient_255_pt12__53_pt25__33_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     21.53 Å
  orient_255_pt12__53_pt25__33_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     23.15 Å
  orient_255_pt12__53_pt25__33_a2_t0.1_s4_af2pred       93   178    9   0.2060         189     14.63 Å
  orient_255_pt12__53_pt25__33_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     21.71 Å
  orient_255_pt12__53_pt25__33_a3_t0.1_s5_af2pred       93   178    9   0.0000           0     22.52 Å
  orient_255_pt12__53_pt25__33_a4_t0.1_s4_af2pred       93   178    9   0.0000           0     25.59 Å

  orient_255_pt12__53_pt25__33_a4_t0.1_s8_af2pred       93   178    9   0.0000           0     22.61 Å
  orient_255_pt12__53_pt25__34_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     23.47 Å
  orient_255_pt12__53_pt25__34_a1_t0.1_s5_af2pred       93   178    9   0.5804         613     10.26 Å
  orient_255_pt12__53_pt25__34_a2_t0.1_s1_af2pred       93   178    9   0.1869         171     15.39 Å
  orient_255_pt12__53_pt25__34_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     22.31 Å
  orient_255_pt12__53_pt25__34_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     27.10 Å
  orient_255_pt12__53_pt25__34_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     23.16 Å
  orient_255_pt12__53_pt25__34_a2_t0.1_s5_af2pred       93   178    9   0.0000           0     23.79 Å
  orient_255_pt12__53_pt25__34_a2_t0.1_s6_af2pred       93   178    9   0.7590         728      7.28 Å
  orient_255_pt12__53_pt25__35_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     23.53 Å
  orient_255_pt12__53_pt25__35_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     23.27 Å
  orient_255_pt12__53_pt25__35_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     24.39 Å
  orient_255_pt12__53_pt25__35_a3_t0.1_s1_af2pred       93   178    9   0.0000           0     24.37 Å
  orient_255_pt12__53_pt25__35_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     23.08 Å
  orient_255_pt12__53_pt25__35_a3_t0.1_s4_af2pred       93   178    9   0.0000           0     24.38 Å
  orient_255_pt12__53_pt25__35_a6_t0.1_s1_af2pred       93   178    9   0.0000           0     23.11 Å
  orient_255_pt12__53_pt25__35_a6_t0.1_s3_af2pred       93   178    9   0.0000           0     22.33 Å
  orient_255_pt12__53_pt25__39_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     25.46 Å
  orient_255_pt12__53_pt25__39_a2_t0.1_s8_af2pred       93   178    9   0.0100          28     18.06 Å
  orient_255_pt12__53_pt25__39_a3_t0.1_s4_af2pred       93   178    9   0.0020           7     19.21 Å
  orient_255_pt12__53_pt25__39_a3_t0.1_s7_af2pred       93   178    9   0.0021          13     19.19 Å
  orient_255_pt12__53_pt25__39_a4_t0.1_s4_af2pred       93   178    9   0.0953          88     16.49 Å
  orient_255_pt12__53_pt25__39_a4_t0.1_s5_af2pred       93   178    9   0.0021          17     18.34 Å
  orient_255_pt12__53_pt25__39_a5_t0.1_s1_af2pred       93   178    9   0.6279         697      8.63 Å
  orient_255_pt12__53_pt25__39_a5_t0.1_s3_af2pred       93   178    9   0.0000           0     20.89 Å
  orient_255_pt12__53_pt25__3_a10_t0.1_s2_af2pred       93   178    9   0.0000           0     23.70 Å
  orient_255_pt12__53_pt25__3_a10_t0.1_s5_af2pred       93   178    9   0.0022           1     20.22 Å
  orient_255_pt12__53_pt25__3_a13_t0.15_s6_af2pred      93   178    9   0.0000           0     23.07 Å
  orient_255_pt12__53_pt25__3_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     22.22 Å
  orient_255_pt12__53_pt25__3_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     23.69 Å
  orient_255_pt12__53_pt25__3_a4_t0.1_s4_af2pred        93   178    9   0.0000           0     23.19 Å
  orient_255_pt12__53_pt25__3_a6_t0.1_s3_af2pred        93   178    9   0.0000           0     22.41 Å
  orient_255_pt12__53_pt25__3_a7_t0.1_s7_af2pred        93   178    9   0.0000           0     22.91 Å
  orient_255_pt12__53_pt25__44_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     21.98 Å
  orient_255_pt12__53_pt25__44_a2_t0.1_s6_af2pred       93   178    9   0.0018           2     20.20 Å
  orient_255_pt12__53_pt25__44_a2_t0.1_s8_af2pred       93   178    9   0.0026           1     22.07 Å
  orient_255_pt12__53_pt25__44_a3_t0.1_s1_af2pred       93   178    9   0.0544          59     16.70 Å
  orient_255_pt12__53_pt25__44_a5_t0.1_s3_af2pred       93   178    9   0.1015          93     16.44 Å
  orient_255_pt12__53_pt25__44_a5_t0.1_s6_af2pred       93   178    9   0.0000           0     21.97 Å
  orient_255_pt12__53_pt25__44_a6_t0.1_s2_af2pred       93   178    9   0.3057         317     13.26 Å
  orient_255_pt12__53_pt25__44_a8_t0.1_s8_af2pred       93   178    9   0.0000           0     25.51 Å
  orient_255_pt12__53_pt25__49_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     21.16 Å
  orient_255_pt12__53_pt25__49_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     23.87 Å
  orient_255_pt12__53_pt25__49_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     21.14 Å
  orient_255_pt12__53_pt25__49_a1_t0.1_s4_af2pred       93   178    9   0.5318         662      9.82 Å
  orient_255_pt12__53_pt25__49_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     21.84 Å
  orient_255_pt12__53_pt25__49_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     23.54 Å
  orient_255_pt12__53_pt25__49_a3_t0.1_s5_af2pred       93   178    9   0.0000           0     21.45 Å
  orient_255_pt12__53_pt25__49_a3_t0.1_s8_af2pred       93   178    9   0.0000           0     22.62 Å
  orient_255_pt12__53_pt25__5_a1_t0.1_s1_af2pred        93   178    9   0.4647         545     11.01 Å
  orient_255_pt12__53_pt25__5_a2_t0.1_s7_af2pred        93   178    9   0.0000           0     21.29 Å
  orient_255_pt12__53_pt25__5_a3_t0.1_s4_af2pred        93   178    9   0.0000           0     23.15 Å
  orient_255_pt12__53_pt25__5_a3_t0.1_s5_af2pred        93   178    9   0.0000           0     23.10 Å
  orient_255_pt12__53_pt25__5_a4_t0.1_s1_af2pred        93   178    9   0.0000           0     23.62 Å
  orient_255_pt12__53_pt25__5_a6_t0.1_s2_af2pred        93   178    9   0.0000           0     21.53 Å
  orient_255_pt12__53_pt25__5_a6_t0.1_s3_af2pred        93   178    9   0.7106         805      6.53 Å
  orient_255_pt12__53_pt25__5_a7_t0.1_s6_af2pred        93   178    9   0.0000           0     23.26 Å
  orient_255_pt12__53_pt25__7_a1_t0.1_s1_af2pred        93   178    9   0.0018           8     17.49 Å
  orient_255_pt12__53_pt25__7_a1_t0.1_s2_af2pred        93   178    9   0.0022          19     17.85 Å
  orient_255_pt12__53_pt25__7_a1_t0.1_s3_af2pred        93   178    9   0.7313         798      6.32 Å
  orient_255_pt12__53_pt25__7_a1_t0.1_s4_af2pred        93   178    9   0.2859         299     13.52 Å
  orient_255_pt12__53_pt25__7_a1_t0.1_s6_af2pred        93   178    9   0.3082         317     13.42 Å
  orient_255_pt12__53_pt25__7_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     21.42 Å
  orient_255_pt12__53_pt25__7_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     22.18 Å
  orient_255_pt12__53_pt25__7_a2_t0.1_s4_af2pred        93   178    9   0.1285         110     15.47 Å
  orient_255_pt12__53_pt25__9_a1_t0.1_s1_af2pred        93   178    9   0.8596         828      3.94 Å
  orient_255_pt12__53_pt25__9_a2_t0.1_s1_af2pred        93   178    9   0.8191         826      4.64 Å
  orient_255_pt12__53_pt25__9_a2_t0.1_s4_af2pred        93   178    9   0.0000           0     22.26 Å
  orient_255_pt12__53_pt25__9_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     21.63 Å
  orient_255_pt12__53_pt25__9_a3_t0.1_s2_af2pred        93   178    9   0.0000           0     23.39 Å
  orient_255_pt12__53_pt25__9_a3_t0.1_s5_af2pred        93   178    9   0.6936         776      6.95 Å
  orient_255_pt12__53_pt25__9_a4_t0.1_s3_af2pred        93   178    9   0.8227         824      4.61 Å
  orient_255_pt12__53_pt25__9_a4_t0.1_s4_af2pred        93   178    9   0.0000           0     22.20 Å
  orient_255_pt12__70_pt12__12_a13_t0.15_s6_af2pred      93   178    9   0.8495         832      4.10 Å
  orient_255_pt12__70_pt12__12_a14_t0.15_s2_af2pred      93   178    9   0.7242         813      6.26 Å
  orient_255_pt12__70_pt12__12_a14_t0.15_s8_af2pred      93   178    9   0.7982         832      4.93 Å
  orient_255_pt12__70_pt12__12_a17_t0.15_s3_af2pred      93   178    9   0.0000           0     24.01 Å
  orient_255_pt12__70_pt12__12_a3_t0.1_s8_af2pred       93   178    9   0.7252         801      6.49 Å
  orient_255_pt12__70_pt12__12_a4_t0.1_s4_af2pred       93   178    9   0.0018           3     21.27 Å
  orient_255_pt12__70_pt12__12_a7_t0.1_s2_af2pred       93   178    9   0.7143         803      6.49 Å
  orient_255_pt12__70_pt12__12_a9_t0.1_s7_af2pred       93   178    9   0.7764         827      5.41 Å
  orient_255_pt12__70_pt12__16_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     23.67 Å
  orient_255_pt12__70_pt12__16_a1_t0.1_s3_af2pred       93   178    9   0.6290         703      8.62 Å
  orient_255_pt12__70_pt12__16_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     21.98 Å
  orient_255_pt12__70_pt12__16_a1_t0.1_s6_af2pred       93   178    9   0.1711         152     15.27 Å

  orient_255_pt12__70_pt12__16_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     26.86 Å
  orient_255_pt12__70_pt12__16_a2_t0.1_s4_af2pred       93   178    9   0.0019           3     20.73 Å
  orient_255_pt12__70_pt12__16_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     27.57 Å
  orient_255_pt12__70_pt12__16_a2_t0.1_s8_af2pred       93   178    9   0.6924         744      7.52 Å
  orient_255_pt12__70_pt12__18_a1_t0.1_s4_af2pred       93   178    9   0.7631         810      5.68 Å
  orient_255_pt12__70_pt12__18_a1_t0.1_s6_af2pred       93   178    9   0.0584          60     16.88 Å
  orient_255_pt12__70_pt12__18_a1_t0.1_s7_af2pred       93   178    9   0.0022          21     18.67 Å
  orient_255_pt12__70_pt12__18_a2_t0.1_s6_af2pred       93   178    9   0.8369         831      4.31 Å
  orient_255_pt12__70_pt12__18_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     20.34 Å
  orient_255_pt12__70_pt12__18_a3_t0.1_s8_af2pred       93   178    9   0.7529         804      5.87 Å
  orient_255_pt12__70_pt12__18_a5_t0.1_s1_af2pred       93   178    9   0.7182         800      6.43 Å
  orient_255_pt12__70_pt12__18_a5_t0.1_s2_af2pred       93   178    9   0.8518         836      4.00 Å
  orient_255_pt12__70_pt12__19_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     21.76 Å
  orient_255_pt12__70_pt12__19_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.26 Å
  orient_255_pt12__70_pt12__19_a2_t0.1_s5_af2pred       93   178    9   0.0000           0     22.61 Å
  orient_255_pt12__70_pt12__19_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     23.62 Å
  orient_255_pt12__70_pt12__19_a3_t0.1_s4_af2pred       93   178    9   0.0000           0     21.63 Å
  orient_255_pt12__70_pt12__19_a3_t0.1_s5_af2pred       93   178    9   0.0000           0     25.19 Å
  orient_255_pt12__70_pt12__19_a4_t0.1_s1_af2pred       93   178    9   0.0000           0     22.57 Å
  orient_255_pt12__70_pt12__19_a5_t0.1_s6_af2pred       93   178    9   0.3778         392     13.19 Å
  orient_255_pt12__70_pt12__1_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     22.82 Å
  orient_255_pt12__70_pt12__1_a1_t0.1_s4_af2pred        93   178    9   0.8074         832      4.78 Å
  orient_255_pt12__70_pt12__1_a1_t0.1_s6_af2pred        93   178    9   0.0000           0     21.67 Å
  orient_255_pt12__70_pt12__1_a1_t0.1_s7_af2pred        93   178    9   0.0000           0     22.83 Å
  orient_255_pt12__70_pt12__1_a2_t0.1_s3_af2pred        93   178    9   0.0000           0     23.85 Å
  orient_255_pt12__70_pt12__1_a2_t0.1_s6_af2pred        93   178    9   0.5580         657      9.60 Å
  orient_255_pt12__70_pt12__1_a2_t0.1_s8_af2pred        93   178    9   0.0000           0     22.09 Å
  orient_255_pt12__70_pt12__1_a3_t0.1_s1_af2pred        93   178    9   0.0000           0     22.27 Å
  orient_255_pt12__70_pt12__21_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     24.49 Å
  orient_255_pt12__70_pt12__21_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     26.89 Å
  orient_255_pt12__70_pt12__21_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     25.21 Å
  orient_255_pt12__70_pt12__21_a3_t0.1_s8_af2pred       93   178    9   0.0000           0     24.80 Å
  orient_255_pt12__70_pt12__21_a4_t0.1_s2_af2pred       93   178    9   0.0000           0     22.75 Å
  orient_255_pt12__70_pt12__21_a4_t0.1_s3_af2pred       93   178    9   0.0000           0     23.52 Å
  orient_255_pt12__70_pt12__21_a4_t0.1_s7_af2pred       93   178    9   0.0020           3     20.06 Å
  orient_255_pt12__70_pt12__21_a5_t0.1_s1_af2pred       93   178    9   0.0000           0     21.92 Å
  orient_255_pt12__70_pt12__24_a1_t0.1_s2_af2pred       93   178    9   0.7696         809      5.63 Å
  orient_255_pt12__70_pt12__24_a1_t0.1_s6_af2pred       93   178    9   0.7432         790      6.22 Å
  orient_255_pt12__70_pt12__24_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     22.35 Å
  orient_255_pt12__70_pt12__24_a2_t0.1_s4_af2pred       93   178    9   0.8503         823      4.17 Å
  orient_255_pt12__70_pt12__24_a2_t0.1_s6_af2pred       93   178    9   0.6147         729      8.40 Å
  orient_255_pt12__70_pt12__24_a3_t0.1_s2_af2pred       93   178    9   0.0000           0     23.55 Å
  orient_255_pt12__70_pt12__24_a3_t0.1_s4_af2pred       93   178    9   0.0000           0     22.84 Å
  orient_255_pt12__70_pt12__24_a4_t0.1_s4_af2pred       93   178    9   0.7963         794      5.46 Å
  orient_255_pt12__70_pt12__2_a1_t0.1_s1_af2pred        93   178    9   0.0022          10     19.15 Å
  orient_255_pt12__70_pt12__2_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     26.18 Å
  orient_255_pt12__70_pt12__2_a1_t0.1_s5_af2pred        93   178    9   0.7600         815      5.69 Å
  orient_255_pt12__70_pt12__2_a2_t0.1_s5_af2pred        93   178    9   0.0245          37     17.62 Å
  orient_255_pt12__70_pt12__2_a2_t0.1_s6_af2pred        93   178    9   0.8623         830      3.87 Å
  orient_255_pt12__70_pt12__2_a3_t0.1_s2_af2pred        93   178    9   0.0000           0     26.78 Å
  orient_255_pt12__70_pt12__2_a3_t0.1_s7_af2pred        93   178    9   0.0000           0     23.34 Å
  orient_255_pt12__70_pt12__2_a4_t0.1_s3_af2pred        93   178    9   0.0000           0     25.24 Å
  orient_255_pt12__70_pt12__32_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     23.95 Å
  orient_255_pt12__70_pt12__32_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     23.19 Å
  orient_255_pt12__70_pt12__32_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     23.73 Å
  orient_255_pt12__70_pt12__32_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     23.43 Å
  orient_255_pt12__70_pt12__32_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.78 Å
  orient_255_pt12__70_pt12__32_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     22.85 Å
  orient_255_pt12__70_pt12__32_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     23.50 Å
  orient_255_pt12__70_pt12__32_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     22.04 Å
  orient_255_pt12__70_pt12__33_a1_t0.1_s3_af2pred       93   178    9   0.6108         656      9.03 Å
  orient_255_pt12__70_pt12__33_a1_t0.1_s4_af2pred       93   178    9   0.2728         250     13.78 Å
  orient_255_pt12__70_pt12__33_a1_t0.1_s5_af2pred       93   178    9   0.6813         757      7.42 Å
  orient_255_pt12__70_pt12__33_a1_t0.1_s8_af2pred       93   178    9   0.0022          10     18.19 Å
  orient_255_pt12__70_pt12__33_a2_t0.1_s1_af2pred       93   178    9   0.3482         332     13.32 Å
  orient_255_pt12__70_pt12__33_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     23.48 Å
  orient_255_pt12__70_pt12__33_a2_t0.1_s3_af2pred       93   178    9   0.0019           2     20.29 Å
  orient_255_pt12__70_pt12__33_a2_t0.1_s8_af2pred       93   178    9   0.0000           0     21.25 Å
  orient_255_pt12__70_pt12__37_a1_t0.1_s2_af2pred       93   178    9   0.6242         712      8.36 Å
  orient_255_pt12__70_pt12__37_a1_t0.1_s3_af2pred       93   178    9   0.4634         532     11.15 Å
  orient_255_pt12__70_pt12__37_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     24.10 Å
  orient_255_pt12__70_pt12__37_a1_t0.1_s7_af2pred       93   178    9   0.8126         832      4.70 Å
  orient_255_pt12__70_pt12__37_a1_t0.1_s8_af2pred       93   178    9   0.8846         837      3.44 Å
  orient_255_pt12__70_pt12__37_a2_t0.1_s1_af2pred       93   178    9   0.8067         827      4.86 Å
  orient_255_pt12__70_pt12__37_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     21.47 Å
  orient_255_pt12__70_pt12__37_a2_t0.1_s4_af2pred       93   178    9   0.8289         832      4.42 Å
  orient_255_pt12__70_pt12__38_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     23.67 Å
  orient_255_pt12__70_pt12__38_a1_t0.1_s2_af2pred       93   178    9   0.7310         790      6.40 Å
  orient_255_pt12__70_pt12__38_a1_t0.1_s3_af2pred       93   178    9   0.4053         428     12.24 Å
  orient_255_pt12__70_pt12__38_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     22.68 Å
  orient_255_pt12__70_pt12__38_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     23.57 Å
  orient_255_pt12__70_pt12__38_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     25.99 Å
  orient_255_pt12__70_pt12__38_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     21.84 Å
  orient_255_pt12__70_pt12__38_a1_t0.1_s8_af2pred       93   178    9   0.1234         112     15.69 Å
  orient_255_pt12__70_pt12__43_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     21.89 Å
  orient_255_pt12__70_pt12__43_a1_t0.1_s4_af2pred       93   178    9   0.0019           1     20.86 Å

  orient_255_pt12__70_pt12__43_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     22.09 Å
  orient_255_pt12__70_pt12__43_a2_t0.1_s4_af2pred       93   178    9   0.5894         705      8.94 Å
  orient_255_pt12__70_pt12__43_a2_t0.1_s8_af2pred       93   178    9   0.0018           1     20.14 Å
  orient_255_pt12__70_pt12__43_a3_t0.1_s5_af2pred       93   178    9   0.8151         825      4.76 Å
  orient_255_pt12__70_pt12__43_a4_t0.1_s6_af2pred       93   178    9   0.0020           7     19.44 Å
  orient_255_pt12__70_pt12__43_a6_t0.1_s8_af2pred       93   178    9   0.0000           0     22.85 Å
  orient_255_pt12__70_pt12__44_a1_t0.1_s8_af2pred       93   178    9   0.6341         755      8.01 Å
  orient_255_pt12__70_pt12__44_a2_t0.1_s1_af2pred       93   178    9   0.0023           2     20.61 Å
  orient_255_pt12__70_pt12__44_a2_t0.1_s2_af2pred       93   178    9   0.0022          13     18.83 Å
  orient_255_pt12__70_pt12__44_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     23.04 Å
  orient_255_pt12__70_pt12__44_a3_t0.1_s4_af2pred       93   178    9   0.4226         455     11.92 Å
  orient_255_pt12__70_pt12__44_a3_t0.1_s5_af2pred       93   178    9   0.4314         444     11.76 Å
  orient_255_pt12__70_pt12__44_a3_t0.1_s8_af2pred       93   178    9   0.1480         126     15.76 Å
  orient_255_pt12__70_pt12__44_a4_t0.1_s8_af2pred       93   178    9   0.0000           0     26.89 Å
  orient_255_pt12__70_pt12__45_a1_t0.1_s7_af2pred       93   178    9   0.3525         319     13.65 Å
  orient_255_pt12__70_pt12__45_a2_t0.1_s4_af2pred       93   178    9   0.8227         818      4.81 Å
  orient_255_pt12__70_pt12__45_a2_t0.1_s6_af2pred       93   178    9   0.1633         138     15.58 Å
  orient_255_pt12__70_pt12__45_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     21.31 Å
  orient_255_pt12__70_pt12__45_a3_t0.1_s3_af2pred       93   178    9   0.4527         485     11.67 Å
  orient_255_pt12__70_pt12__45_a4_t0.1_s1_af2pred       93   178    9   0.3717         379     12.47 Å
  orient_255_pt12__70_pt12__45_a4_t0.1_s4_af2pred       93   178    9   0.0029          22     18.37 Å
  orient_255_pt12__70_pt12__45_a4_t0.1_s6_af2pred       93   178    9   0.0000           0     21.79 Å
  orient_255_pt12__70_pt12__46_a1_t0.1_s1_af2pred       93   178    9   0.7937         816      5.30 Å
  orient_255_pt12__70_pt12__46_a1_t0.1_s2_af2pred       93   178    9   0.8784         816      3.87 Å
  orient_255_pt12__70_pt12__46_a1_t0.1_s3_af2pred       93   178    9   0.8598         821      4.13 Å
  orient_255_pt12__70_pt12__46_a1_t0.1_s7_af2pred       93   178    9   0.8558         819      4.26 Å
  orient_255_pt12__70_pt12__46_a2_t0.1_s1_af2pred       93   178    9   0.0948          89     15.76 Å
  orient_255_pt12__70_pt12__46_a2_t0.1_s4_af2pred       93   178    9   0.5483         681      9.49 Å
  orient_255_pt12__70_pt12__46_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     21.56 Å
  orient_255_pt12__70_pt12__46_a2_t0.1_s7_af2pred       93   178    9   0.8122         825      4.81 Å
  orient_255_pt12__70_pt12__51_a2_t0.1_s2_af2pred       93   178    9   0.8395         836      4.21 Å
  orient_255_pt12__70_pt12__51_a2_t0.1_s6_af2pred       93   178    9   0.6509         773      7.62 Å
  orient_255_pt12__70_pt12__51_a3_t0.1_s1_af2pred       93   178    9   0.8639         835      3.79 Å
  orient_255_pt12__70_pt12__51_a4_t0.1_s2_af2pred       93   178    9   0.1716         158     15.11 Å
  orient_255_pt12__70_pt12__51_a4_t0.1_s7_af2pred       93   178    9   0.8289         835      4.40 Å
  orient_255_pt12__70_pt12__51_a5_t0.1_s3_af2pred       93   178    9   0.0000           0     21.74 Å
  orient_255_pt12__70_pt12__51_a5_t0.1_s8_af2pred       93   178    9   0.8426         829      4.24 Å
  orient_255_pt12__70_pt12__51_a6_t0.1_s5_af2pred       93   178    9   0.8602         837      3.85 Å
  orient_255_pt12__70_pt12__54_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     23.70 Å
  orient_255_pt12__70_pt12__54_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     23.41 Å
  orient_255_pt12__70_pt12__54_a1_t0.1_s3_af2pred       93   178    9   0.0765          70     16.88 Å
  orient_255_pt12__70_pt12__54_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     20.59 Å
  orient_255_pt12__70_pt12__54_a2_t0.1_s2_af2pred       93   178    9   0.1986         178     14.95 Å
  orient_255_pt12__70_pt12__54_a2_t0.1_s4_af2pred       93   178    9   0.4885         550     10.96 Å
  orient_255_pt12__70_pt12__54_a2_t0.1_s6_af2pred       93   178    9   0.0020           7     19.35 Å
  orient_255_pt12__70_pt12__54_a3_t0.1_s4_af2pred       93   178    9   0.0019           5     20.13 Å
  orient_255_pt12__70_pt12__57_a1_t0.1_s4_af2pred       93   178    9   0.4229         456     11.88 Å
  orient_255_pt12__70_pt12__57_a1_t0.1_s6_af2pred       93   178    9   0.6501         775      7.63 Å
  orient_255_pt12__70_pt12__57_a2_t0.1_s1_af2pred       93   178    9   0.7289         818      6.14 Å
  orient_255_pt12__70_pt12__57_a2_t0.1_s2_af2pred       93   178    9   0.6653         776      7.39 Å
  orient_255_pt12__70_pt12__57_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     22.10 Å
  orient_255_pt12__70_pt12__57_a2_t0.1_s4_af2pred       93   178    9   0.6779         781      7.22 Å
  orient_255_pt12__70_pt12__57_a2_t0.1_s6_af2pred       93   178    9   0.6725         773      7.27 Å
  orient_255_pt12__70_pt12__57_a2_t0.1_s7_af2pred       93   178    9   0.0024           1     19.80 Å
  orient_255_pt12__70_pt12__62_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     25.52 Å
  orient_255_pt12__70_pt12__62_a2_t0.1_s1_af2pred       93   178    9   0.0018           1     20.54 Å
  orient_255_pt12__70_pt12__62_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     22.49 Å
  orient_255_pt12__70_pt12__62_a2_t0.1_s8_af2pred       93   178    9   0.0000           0     22.56 Å
  orient_255_pt12__70_pt12__62_a4_t0.1_s3_af2pred       93   178    9   0.0000           0     23.50 Å
  orient_255_pt12__70_pt12__62_a4_t0.1_s4_af2pred       93   178    9   0.0000           0     22.83 Å
  orient_255_pt12__70_pt12__62_a4_t0.1_s7_af2pred       93   178    9   0.0000           0     22.18 Å
  orient_255_pt12__70_pt12__62_a5_t0.1_s2_af2pred       93   178    9   0.0000           0     22.53 Å
  orient_255_pt12__70_pt12__64_a1_t0.1_s2_af2pred       93   178    9   0.0586          60     17.35 Å
  orient_255_pt12__70_pt12__64_a1_t0.1_s4_af2pred       93   178    9   0.6397         752      7.93 Å
  orient_255_pt12__70_pt12__64_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     23.50 Å
  orient_255_pt12__70_pt12__64_a2_t0.1_s7_af2pred       93   178    9   0.6182         716      8.47 Å
  orient_255_pt12__70_pt12__64_a4_t0.1_s5_af2pred       93   178    9   0.0000           0     23.49 Å
  orient_255_pt12__70_pt12__64_a5_t0.1_s8_af2pred       93   178    9   0.5317         632      9.95 Å
  orient_255_pt12__70_pt12__64_a6_t0.1_s3_af2pred       93   178    9   0.6088         696      8.68 Å
  orient_255_pt12__70_pt12__64_a7_t0.1_s5_af2pred       93   178    9   0.0000           0     22.54 Å
  orient_255_pt12__70_pt12__65_a10_t0.1_s5_af2pred      93   178    9   0.0000           0     23.00 Å
  orient_255_pt12__70_pt12__65_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     22.07 Å
  orient_255_pt12__70_pt12__65_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     23.75 Å
  orient_255_pt12__70_pt12__65_a4_t0.1_s1_af2pred       93   178    9   0.6072         740      8.46 Å
  orient_255_pt12__70_pt12__65_a4_t0.1_s6_af2pred       93   178    9   0.0000           0     22.14 Å
  orient_255_pt12__70_pt12__65_a6_t0.1_s3_af2pred       93   178    9   0.0000           0     22.21 Å
  orient_255_pt12__70_pt12__65_a8_t0.1_s3_af2pred       93   178    9   0.0000           0     21.99 Å
  orient_255_pt12__70_pt12__65_a9_t0.1_s8_af2pred       93   178    9   0.0000           0     22.61 Å
  orient_255_pt12__70_pt12__66_a1_t0.1_s2_af2pred       93   178    9   0.4925         569     10.56 Å
  orient_255_pt12__70_pt12__66_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     22.60 Å
  orient_255_pt12__70_pt12__66_a1_t0.1_s6_af2pred       93   178    9   0.8456         836      4.12 Å
  orient_255_pt12__70_pt12__66_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     22.68 Å
  orient_255_pt12__70_pt12__66_a1_t0.1_s8_af2pred       93   178    9   0.7336         810      6.21 Å
  orient_255_pt12__70_pt12__66_a2_t0.1_s2_af2pred       93   178    9   0.7400         828      5.88 Å
  orient_255_pt12__70_pt12__66_a2_t0.1_s6_af2pred       93   178    9   0.8556         834      3.96 Å
  orient_255_pt12__70_pt12__66_a2_t0.1_s7_af2pred       93   178    9   0.8003         831      4.91 Å
  orient_255_pt12__70_pt12__68_a1_t0.1_s3_af2pred       93   178    9   0.8345         821      4.46 Å
  orient_255_pt12__70_pt12__68_a1_t0.1_s4_af2pred       93   178    9   0.8106         817      4.92 Å

  orient_255_pt12__70_pt12__68_a1_t0.1_s8_af2pred       93   178    9   0.7762         815      5.45 Å
  orient_255_pt12__70_pt12__68_a2_t0.1_s1_af2pred       93   178    9   0.0144          31     17.92 Å
  orient_255_pt12__70_pt12__68_a2_t0.1_s5_af2pred       93   178    9   0.5886         707      8.89 Å
  orient_255_pt12__70_pt12__68_a3_t0.1_s3_af2pred       93   178    9   0.7373         792      6.29 Å
  orient_255_pt12__70_pt12__68_a3_t0.1_s4_af2pred       93   178    9   0.8668         822      3.98 Å
  orient_255_pt12__70_pt12__68_a3_t0.1_s7_af2pred       93   178    9   0.7886         780      5.77 Å
  orient_255_pt12__70_pt12__70_a1_t0.1_s1_af2pred       93   178    9   0.0018           1     21.56 Å
  orient_255_pt12__70_pt12__70_a1_t0.1_s2_af2pred       93   178    9   0.0018           4     19.79 Å
  orient_255_pt12__70_pt12__70_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     20.69 Å
  orient_255_pt12__70_pt12__70_a1_t0.1_s5_af2pred       93   178    9   0.5814         680      9.29 Å
  orient_255_pt12__70_pt12__70_a2_t0.1_s1_af2pred       93   178    9   0.0076          26     18.06 Å
  orient_255_pt12__70_pt12__70_a2_t0.1_s2_af2pred       93   178    9   0.0021          11     18.94 Å
  orient_255_pt12__70_pt12__70_a2_t0.1_s4_af2pred       93   178    9   0.0021           4     19.96 Å
  orient_255_pt12__70_pt12__70_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     24.38 Å
  orient_255_pt12__70_pt12__71_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     25.29 Å
  orient_255_pt12__70_pt12__71_a1_t0.1_s2_af2pred       93   178    9   0.0018           1     22.54 Å
  orient_255_pt12__70_pt12__71_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     24.64 Å
  orient_255_pt12__70_pt12__71_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     25.23 Å
  orient_255_pt12__70_pt12__71_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     26.66 Å
  orient_255_pt12__70_pt12__71_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     22.50 Å
  orient_255_pt12__70_pt12__71_a2_t0.1_s4_af2pred       93   178    9   0.0018           3     20.87 Å
  orient_255_pt12__70_pt12__71_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     21.39 Å
  orient_255_pt12__70_pt12__73_a1_t0.1_s1_af2pred       93   178    9   0.0020           8     18.97 Å
  orient_255_pt12__70_pt12__73_a2_t0.1_s1_af2pred       93   178    9   0.7733         821      5.47 Å
  orient_255_pt12__70_pt12__73_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     21.12 Å
  orient_255_pt12__70_pt12__73_a2_t0.1_s6_af2pred       93   178    9   0.2395         209     14.29 Å
  orient_255_pt12__70_pt12__73_a3_t0.1_s3_af2pred       93   178    9   0.0019          12     18.41 Å
  orient_255_pt12__70_pt12__73_a3_t0.1_s8_af2pred       93   178    9   0.8240         833      4.50 Å
  orient_255_pt12__70_pt12__73_a4_t0.1_s1_af2pred       93   178    9   0.0022           6     19.46 Å
  orient_255_pt12__70_pt12__73_a4_t0.1_s2_af2pred       93   178    9   0.0000           0     21.35 Å
  orient_255_pt12__70_pt12__74_a1_t0.1_s3_af2pred       93   178    9   0.7831         792      5.61 Å
  orient_255_pt12__70_pt12__74_a1_t0.1_s4_af2pred       93   178    9   0.0019           1     21.19 Å
  orient_255_pt12__70_pt12__74_a1_t0.1_s6_af2pred       93   178    9   0.7915         793      5.43 Å
  orient_255_pt12__70_pt12__74_a1_t0.1_s8_af2pred       93   178    9   0.0537          54     17.13 Å
  orient_255_pt12__70_pt12__74_a2_t0.1_s1_af2pred       93   178    9   0.0022          10     19.57 Å
  orient_255_pt12__70_pt12__74_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     21.09 Å
  orient_255_pt12__70_pt12__74_a2_t0.1_s3_af2pred       93   178    9   0.6749         767      7.42 Å
  orient_255_pt12__70_pt12__74_a2_t0.1_s4_af2pred       93   178    9   0.7694         808      5.59 Å
  orient_255_pt12__70_pt12__75_a2_t0.1_s1_af2pred       93   178    9   0.0000           0     21.74 Å
  orient_255_pt12__70_pt12__75_a2_t0.1_s6_af2pred       93   178    9   0.8492         835      4.07 Å
  orient_255_pt12__70_pt12__75_a3_t0.1_s6_af2pred       93   178    9   0.8145         837      4.63 Å
  orient_255_pt12__70_pt12__75_a3_t0.1_s8_af2pred       93   178    9   0.0000           0     20.66 Å
  orient_255_pt12__70_pt12__75_a4_t0.1_s4_af2pred       93   178    9   0.0000           0     23.42 Å
  orient_255_pt12__70_pt12__75_a5_t0.1_s3_af2pred       93   178    9   0.7032         816      6.56 Å
  orient_255_pt12__70_pt12__75_a5_t0.1_s6_af2pred       93   178    9   0.0000           0     22.93 Å
  orient_255_pt12__70_pt12__75_a8_t0.1_s5_af2pred       93   178    9   0.8261         837      4.44 Å
  orient_255_pt12__70_pt12__7_a1_t0.1_s2_af2pred        93   178    9   0.0000           0     22.25 Å
  orient_255_pt12__70_pt12__7_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     22.60 Å
  orient_255_pt12__70_pt12__7_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     23.07 Å
  orient_255_pt12__70_pt12__7_a1_t0.1_s6_af2pred        93   178    9   0.0000           0     23.43 Å
  orient_255_pt12__70_pt12__7_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     22.95 Å
  orient_255_pt12__70_pt12__7_a3_t0.1_s3_af2pred        93   178    9   0.0000           0     22.48 Å
  orient_255_pt12__70_pt12__7_a3_t0.1_s7_af2pred        93   178    9   0.0000           0     22.13 Å
  orient_255_pt12__70_pt12__7_a4_t0.1_s1_af2pred        93   178    9   0.0000           0     22.43 Å
  orient_255_pt12__70_pt12__80_a1_t0.1_s4_af2pred       93   178    9   0.0018           4     19.75 Å
  orient_255_pt12__70_pt12__80_a1_t0.1_s5_af2pred       93   178    9   0.0020           1     21.20 Å
  orient_255_pt12__70_pt12__80_a1_t0.1_s7_af2pred       93   178    9   0.5484         674      9.60 Å
  orient_255_pt12__70_pt12__80_a1_t0.1_s8_af2pred       93   178    9   0.8256         836      4.43 Å
  orient_255_pt12__70_pt12__80_a2_t0.1_s1_af2pred       93   178    9   0.7643         819      5.61 Å
  orient_255_pt12__70_pt12__80_a2_t0.1_s2_af2pred       93   178    9   0.5952         725      8.62 Å
  orient_255_pt12__70_pt12__80_a2_t0.1_s4_af2pred       93   178    9   0.7471         816      5.91 Å
  orient_255_pt12__70_pt12__80_a2_t0.1_s5_af2pred       93   178    9   0.0000           0     24.85 Å
  orient_255_pt12__70_pt12__86_a1_t0.1_s4_af2pred       93   178    9   0.8041         809      5.11 Å
  orient_255_pt12__70_pt12__86_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     24.14 Å
  orient_255_pt12__70_pt12__86_a4_t0.1_s6_af2pred       93   178    9   0.0018           1     21.85 Å
  orient_255_pt12__70_pt12__86_a5_t0.1_s6_af2pred       93   178    9   0.0814          77     16.33 Å
  orient_255_pt12__70_pt12__86_a5_t0.1_s8_af2pred       93   178    9   0.0000           0     23.63 Å
  orient_255_pt12__70_pt12__86_a6_t0.1_s2_af2pred       93   178    9   0.8494         837      4.05 Å
  orient_255_pt12__70_pt12__86_a6_t0.1_s7_af2pred       93   178    9   0.3351         359     12.79 Å
  orient_255_pt12__70_pt12__86_a8_t0.1_s5_af2pred       93   178    9   0.8029         823      4.97 Å
  orient_255_pt12__70_pt12__92_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     21.78 Å
  orient_255_pt12__70_pt12__92_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     21.80 Å
  orient_255_pt12__70_pt12__92_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     21.87 Å
  orient_255_pt12__70_pt12__92_a2_t0.1_s5_af2pred       93   178    9   0.0000           0     21.94 Å
  orient_255_pt12__70_pt12__92_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     21.12 Å
  orient_255_pt12__70_pt12__92_a3_t0.1_s1_af2pred       93   178    9   0.0000           0     22.39 Å
  orient_255_pt12__70_pt12__92_a3_t0.1_s2_af2pred       93   178    9   0.0000           0     21.93 Å
  orient_255_pt12__70_pt12__92_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.14 Å
  orient_255_pt12__70_pt12__94_a1_t0.1_s1_af2pred       93   178    9   0.6096         729      8.44 Å
  orient_255_pt12__70_pt12__94_a1_t0.1_s2_af2pred       93   178    9   0.0019           1     22.04 Å
  orient_255_pt12__70_pt12__94_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     21.35 Å
  orient_255_pt12__70_pt12__94_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     21.59 Å
  orient_255_pt12__70_pt12__94_a1_t0.1_s5_af2pred       93   178    9   0.7685         808      5.74 Å
  orient_255_pt12__70_pt12__94_a1_t0.1_s6_af2pred       93   178    9   0.0022          13     19.04 Å
  orient_255_pt12__70_pt12__94_a1_t0.1_s7_af2pred       93   178    9   0.8559         836      3.93 Å
  orient_255_pt12__70_pt12__94_a1_t0.1_s8_af2pred       93   178    9   0.8219         831      4.54 Å

  orient_255_pt12__70_pt12__97_a1_t0.1_s2_af2pred       93   178    9   0.8131         817      4.88 Å
  orient_255_pt12__70_pt12__97_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     21.51 Å
  orient_255_pt12__70_pt12__97_a3_t0.1_s2_af2pred       93   178    9   0.7072         801      6.69 Å
  orient_255_pt12__70_pt12__97_a3_t0.1_s5_af2pred       93   178    9   0.7953         814      5.21 Å
  orient_255_pt12__70_pt12__97_a3_t0.1_s6_af2pred       93   178    9   0.8050         817      5.01 Å
  orient_255_pt12__70_pt12__97_a3_t0.1_s7_af2pred       93   178    9   0.0000           0     22.63 Å
  orient_255_pt12__70_pt12__97_a3_t0.1_s8_af2pred       93   178    9   0.6086         737      8.55 Å
  orient_255_pt12__70_pt12__97_a4_t0.1_s4_af2pred       93   178    9   0.8111         813      5.00 Å
  orient_255_pt12__8_pt25__10_a1_t0.1_s3_af2pred        93   178    9   0.0018           3     20.48 Å
  orient_255_pt12__8_pt25__10_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     25.34 Å
  orient_255_pt12__8_pt25__10_a2_t0.1_s2_af2pred        93   178    9   0.0351          44     17.02 Å
  orient_255_pt12__8_pt25__10_a2_t0.1_s6_af2pred        93   178    9   0.0021          20     18.43 Å
  orient_255_pt12__8_pt25__10_a2_t0.1_s8_af2pred        93   178    9   0.0000           0     23.49 Å
  orient_255_pt12__8_pt25__10_a3_t0.1_s8_af2pred        93   178    9   0.3493         406     12.46 Å
  orient_255_pt12__8_pt25__10_a4_t0.1_s2_af2pred        93   178    9   0.0000           0     23.98 Å
  orient_255_pt12__8_pt25__10_a4_t0.1_s4_af2pred        93   178    9   0.0000           0     24.76 Å
  orient_255_pt12__8_pt25__14_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     22.71 Å
  orient_255_pt12__8_pt25__14_a1_t0.1_s7_af2pred        93   178    9   0.0000           0     23.59 Å
  orient_255_pt12__8_pt25__14_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     24.79 Å
  orient_255_pt12__8_pt25__14_a2_t0.1_s4_af2pred        93   178    9   0.0000           0     24.36 Å
  orient_255_pt12__8_pt25__14_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     23.60 Å
  orient_255_pt12__8_pt25__14_a2_t0.1_s7_af2pred        93   178    9   0.0000           0     22.84 Å
  orient_255_pt12__8_pt25__14_a3_t0.1_s2_af2pred        93   178    9   0.0000           0     24.87 Å
  orient_255_pt12__8_pt25__14_a4_t0.1_s1_af2pred        93   178    9   0.0000           0     24.43 Å
  orient_255_pt12__8_pt25__15_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     23.14 Å
  orient_255_pt12__8_pt25__15_a1_t0.1_s2_af2pred        93   178    9   0.0000           0     22.04 Å
  orient_255_pt12__8_pt25__15_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     24.78 Å
  orient_255_pt12__8_pt25__15_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     21.65 Å
  orient_255_pt12__8_pt25__15_a1_t0.1_s6_af2pred        93   178    9   0.0000           0     25.16 Å
  orient_255_pt12__8_pt25__15_a1_t0.1_s7_af2pred        93   178    9   0.0000           0     24.46 Å
  orient_255_pt12__8_pt25__15_a1_t0.1_s8_af2pred        93   178    9   0.0020          14     19.72 Å
  orient_255_pt12__8_pt25__15_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     23.75 Å
  orient_255_pt12__8_pt25__18_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     23.06 Å
  orient_255_pt12__8_pt25__18_a1_t0.1_s3_af2pred        93   178    9   0.6811         808      6.96 Å
  orient_255_pt12__8_pt25__18_a1_t0.1_s4_af2pred        93   178    9   0.7716         816      5.58 Å
  orient_255_pt12__8_pt25__18_a1_t0.1_s6_af2pred        93   178    9   0.2261         195     14.43 Å
  orient_255_pt12__8_pt25__18_a1_t0.1_s7_af2pred        93   178    9   0.0000           0     22.23 Å
  orient_255_pt12__8_pt25__18_a1_t0.1_s8_af2pred        93   178    9   0.0000           0     22.06 Å
  orient_255_pt12__8_pt25__18_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     23.06 Å
  orient_255_pt12__8_pt25__18_a2_t0.1_s3_af2pred        93   178    9   0.0000           0     21.28 Å
  orient_255_pt12__8_pt25__19_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     24.00 Å
  orient_255_pt12__8_pt25__19_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     22.22 Å
  orient_255_pt12__8_pt25__19_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     22.20 Å
  orient_255_pt12__8_pt25__19_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     23.36 Å
  orient_255_pt12__8_pt25__19_a2_t0.1_s4_af2pred        93   178    9   0.0000           0     21.82 Å
  orient_255_pt12__8_pt25__19_a3_t0.1_s3_af2pred        93   178    9   0.0000           0     23.86 Å
  orient_255_pt12__8_pt25__19_a3_t0.1_s4_af2pred        93   178    9   0.0000           0     22.78 Å
  orient_255_pt12__8_pt25__19_a3_t0.1_s5_af2pred        93   178    9   0.0000           0     21.37 Å
  orient_255_pt12__8_pt25__1_a10_t0.1_s5_af2pred        93   178    9   0.0000           0     22.35 Å
  orient_255_pt12__8_pt25__1_a1_t0.1_s2_af2pred         93   178    9   0.0000           0     22.52 Å
  orient_255_pt12__8_pt25__1_a1_t0.1_s3_af2pred         93   178    9   0.0000           0     22.06 Å
  orient_255_pt12__8_pt25__1_a1_t0.1_s8_af2pred         93   178    9   0.0000           0     22.52 Å
  orient_255_pt12__8_pt25__1_a5_t0.1_s1_af2pred         93   178    9   0.0000           0     22.27 Å
  orient_255_pt12__8_pt25__1_a6_t0.1_s3_af2pred         93   178    9   0.3410         351     12.88 Å
  orient_255_pt12__8_pt25__1_a7_t0.1_s7_af2pred         93   178    9   0.2651         254     13.82 Å
  orient_255_pt12__8_pt25__1_a8_t0.1_s2_af2pred         93   178    9   0.0019           1     23.27 Å
  orient_255_pt12__8_pt25__20_a1_t0.1_s3_af2pred        93   178    9   0.3434         357     12.78 Å
  orient_255_pt12__8_pt25__20_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     21.70 Å
  orient_255_pt12__8_pt25__20_a1_t0.1_s6_af2pred        93   178    9   0.4907         571     10.95 Å
  orient_255_pt12__8_pt25__20_a1_t0.1_s7_af2pred        93   178    9   0.0019           1     20.13 Å
  orient_255_pt12__8_pt25__20_a1_t0.1_s8_af2pred        93   178    9   0.0000           0     22.39 Å
  orient_255_pt12__8_pt25__20_a2_t0.1_s1_af2pred        93   178    9   0.7679         820      5.52 Å
  orient_255_pt12__8_pt25__20_a2_t0.1_s3_af2pred        93   178    9   0.0000           0     24.99 Å
  orient_255_pt12__8_pt25__20_a2_t0.1_s5_af2pred        93   178    9   0.0000           0     23.93 Å
  orient_255_pt12__8_pt25__22_a1_t0.1_s3_af2pred        93   178    9   0.0136          30     18.23 Å
  orient_255_pt12__8_pt25__22_a3_t0.1_s3_af2pred        93   178    9   0.0000           0     21.59 Å
  orient_255_pt12__8_pt25__22_a4_t0.1_s5_af2pred        93   178    9   0.0000           0     24.59 Å
  orient_255_pt12__8_pt25__22_a4_t0.1_s8_af2pred        93   178    9   0.0000           0     23.88 Å
  orient_255_pt12__8_pt25__22_a5_t0.1_s3_af2pred        93   178    9   0.0000           0     22.50 Å
  orient_255_pt12__8_pt25__22_a6_t0.1_s5_af2pred        93   178    9   0.0022           2     20.80 Å
  orient_255_pt12__8_pt25__22_a6_t0.1_s8_af2pred        93   178    9   0.0000           0     25.23 Å
  orient_255_pt12__8_pt25__22_a7_t0.1_s4_af2pred        93   178    9   0.0000           0     22.67 Å
  orient_255_pt12__8_pt25__25_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     20.58 Å
  orient_255_pt12__8_pt25__25_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     22.28 Å
  orient_255_pt12__8_pt25__25_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     22.17 Å
  orient_255_pt12__8_pt25__25_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     24.70 Å
  orient_255_pt12__8_pt25__25_a1_t0.1_s7_af2pred        93   178    9   0.0000           0     22.41 Å
  orient_255_pt12__8_pt25__25_a1_t0.1_s8_af2pred        93   178    9   0.0000           0     23.96 Å
  orient_255_pt12__8_pt25__25_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     21.37 Å
  orient_255_pt12__8_pt25__25_a2_t0.1_s5_af2pred        93   178    9   0.0000           0     22.51 Å
  orient_255_pt12__8_pt25__27_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     22.05 Å
  orient_255_pt12__8_pt25__27_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     22.82 Å
  orient_255_pt12__8_pt25__27_a1_t0.1_s6_af2pred        93   178    9   0.0000           0     21.73 Å
  orient_255_pt12__8_pt25__27_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     21.31 Å
  orient_255_pt12__8_pt25__27_a2_t0.1_s3_af2pred        93   178    9   0.0019           4     19.53 Å
  orient_255_pt12__8_pt25__27_a2_t0.1_s4_af2pred        93   178    9   0.0023           7     19.11 Å
  orient_255_pt12__8_pt25__27_a2_t0.1_s7_af2pred        93   178    9   0.0020           3     19.51 Å

  orient_255_pt12__8_pt25__27_a3_t0.1_s2_af2pred        93   178    9   0.0000           0     22.02 Å
  orient_255_pt12__8_pt25__29_a10_t0.1_s1_af2pred       93   178    9   0.0000           0     22.70 Å
  orient_255_pt12__8_pt25__29_a10_t0.1_s2_af2pred       93   178    9   0.0000           0     22.28 Å
  orient_255_pt12__8_pt25__29_a11_t0.15_s8_af2pred      93   178    9   0.0000           0     22.28 Å
  orient_255_pt12__8_pt25__29_a13_t0.15_s7_af2pred      93   178    9   0.0000           0     22.70 Å
  orient_255_pt12__8_pt25__29_a2_t0.1_s7_af2pred        93   178    9   0.0000           0     21.74 Å
  orient_255_pt12__8_pt25__29_a4_t0.1_s1_af2pred        93   178    9   0.0000           0     22.45 Å
  orient_255_pt12__8_pt25__29_a6_t0.1_s8_af2pred        93   178    9   0.0353          47     16.49 Å
  orient_255_pt12__8_pt25__29_a9_t0.1_s3_af2pred        93   178    9   0.0345          46     16.67 Å
  orient_255_pt12__8_pt25__30_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     27.87 Å
  orient_255_pt12__8_pt25__30_a3_t0.1_s3_af2pred        93   178    9   0.0020           4     19.10 Å
  orient_255_pt12__8_pt25__30_a5_t0.1_s4_af2pred        93   178    9   0.0000           0     26.76 Å
  orient_255_pt12__8_pt25__30_a5_t0.1_s5_af2pred        93   178    9   0.0000           0     24.11 Å
  orient_255_pt12__8_pt25__30_a6_t0.1_s8_af2pred        93   178    9   0.0000           0     23.35 Å
  orient_255_pt12__8_pt25__30_a7_t0.1_s5_af2pred        93   178    9   0.7306         794      6.34 Å
  orient_255_pt12__8_pt25__30_a8_t0.1_s1_af2pred        93   178    9   0.0000           0     22.88 Å
  orient_255_pt12__8_pt25__30_a9_t0.1_s3_af2pred        93   178    9   0.7397         795      6.18 Å
  orient_255_pt12__8_pt25__31_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     24.26 Å
  orient_255_pt12__8_pt25__31_a1_t0.1_s2_af2pred        93   178    9   0.0065          25     17.71 Å
  orient_255_pt12__8_pt25__31_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     23.07 Å
  orient_255_pt12__8_pt25__31_a1_t0.1_s7_af2pred        93   178    9   0.0000           0     23.29 Å
  orient_255_pt12__8_pt25__31_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     23.14 Å
  orient_255_pt12__8_pt25__31_a2_t0.1_s3_af2pred        93   178    9   0.0000           0     23.62 Å
  orient_255_pt12__8_pt25__31_a2_t0.1_s8_af2pred        93   178    9   0.0021           2     20.61 Å
  orient_255_pt12__8_pt25__31_a3_t0.1_s2_af2pred        93   178    9   0.0000           0     23.82 Å
  orient_255_pt12__8_pt25__32_a10_t0.1_s2_af2pred       93   178    9   0.0000           0     22.65 Å
  orient_255_pt12__8_pt25__32_a11_t0.15_s3_af2pred      93   178    9   0.0000           0     22.62 Å
  orient_255_pt12__8_pt25__32_a11_t0.15_s4_af2pred      93   178    9   0.7025         809      6.61 Å
  orient_255_pt12__8_pt25__32_a5_t0.1_s5_af2pred        93   178    9   0.7531         824      5.76 Å
  orient_255_pt12__8_pt25__32_a5_t0.1_s8_af2pred        93   178    9   0.0000           0     25.54 Å
  orient_255_pt12__8_pt25__32_a7_t0.1_s8_af2pred        93   178    9   0.7753         827      5.39 Å
  orient_255_pt12__8_pt25__32_a8_t0.1_s1_af2pred        93   178    9   0.0000           0     22.61 Å
  orient_255_pt12__8_pt25__32_a8_t0.1_s7_af2pred        93   178    9   0.1835         158     14.94 Å
  orient_255_pt12__8_pt25__34_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     21.82 Å
  orient_255_pt12__8_pt25__34_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     22.49 Å
  orient_255_pt12__8_pt25__34_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     23.54 Å
  orient_255_pt12__8_pt25__34_a1_t0.1_s7_af2pred        93   178    9   0.0373          46     17.18 Å
  orient_255_pt12__8_pt25__34_a1_t0.1_s8_af2pred        93   178    9   0.6639         766      7.52 Å
  orient_255_pt12__8_pt25__34_a2_t0.1_s3_af2pred        93   178    9   0.0392          46     17.90 Å
  orient_255_pt12__8_pt25__34_a2_t0.1_s4_af2pred        93   178    9   0.0019           2     20.90 Å
  orient_255_pt12__8_pt25__34_a2_t0.1_s7_af2pred        93   178    9   0.0000           0     26.22 Å
  orient_255_pt12__8_pt25__36_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     23.63 Å
  orient_255_pt12__8_pt25__36_a1_t0.1_s2_af2pred        93   178    9   0.0000           0     20.72 Å
  orient_255_pt12__8_pt25__36_a1_t0.1_s3_af2pred        93   178    9   0.0018           1     20.39 Å
  orient_255_pt12__8_pt25__36_a1_t0.1_s4_af2pred        93   178    9   0.2786         266     13.86 Å
  orient_255_pt12__8_pt25__36_a1_t0.1_s6_af2pred        93   178    9   0.4416         489     11.46 Å
  orient_255_pt12__8_pt25__36_a1_t0.1_s7_af2pred        93   178    9   0.0021           3     19.41 Å
  orient_255_pt12__8_pt25__36_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     23.16 Å
  orient_255_pt12__8_pt25__36_a2_t0.1_s2_af2pred        93   178    9   0.1978         193     14.71 Å
  orient_255_pt12__8_pt25__37_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     23.53 Å
  orient_255_pt12__8_pt25__37_a2_t0.1_s3_af2pred        93   178    9   0.3482         366     12.93 Å
  orient_255_pt12__8_pt25__37_a2_t0.1_s4_af2pred        93   178    9   0.0000           0     21.66 Å
  orient_255_pt12__8_pt25__37_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     22.13 Å
  orient_255_pt12__8_pt25__37_a3_t0.1_s3_af2pred        93   178    9   0.0018           2     21.21 Å
  orient_255_pt12__8_pt25__37_a6_t0.1_s3_af2pred        93   178    9   0.0000           0     25.53 Å
  orient_255_pt12__8_pt25__37_a6_t0.1_s8_af2pred        93   178    9   0.0000           0     25.41 Å
  orient_255_pt12__8_pt25__37_a7_t0.1_s4_af2pred        93   178    9   0.0000           0     25.33 Å
  orient_255_pt12__8_pt25__38_a11_t0.15_s4_af2pred      93   178    9   0.0000           0     23.08 Å
  orient_255_pt12__8_pt25__38_a11_t0.15_s7_af2pred      93   178    9   0.0000           0     23.52 Å
  orient_255_pt12__8_pt25__38_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     23.17 Å
  orient_255_pt12__8_pt25__38_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     23.22 Å
  orient_255_pt12__8_pt25__38_a2_t0.1_s7_af2pred        93   178    9   0.0000           0     23.07 Å
  orient_255_pt12__8_pt25__38_a5_t0.1_s3_af2pred        93   178    9   0.0000           0     22.58 Å
  orient_255_pt12__8_pt25__38_a7_t0.1_s1_af2pred        93   178    9   0.0000           0     23.00 Å
  orient_255_pt12__8_pt25__38_a7_t0.1_s7_af2pred        93   178    9   0.0000           0     22.53 Å
  orient_255_pt12__8_pt25__3_a11_t0.15_s7_af2pred       93   178    9   0.0000           0     20.71 Å
  orient_255_pt12__8_pt25__3_a22_t0.2_s2_af2pred        93   178    9   0.0021           2     20.24 Å
  orient_255_pt12__8_pt25__3_a23_t0.2_s7_af2pred        93   178    9   0.0000           0     23.59 Å
  orient_255_pt12__8_pt25__3_a25_t0.2_s1_af2pred        93   178    9   0.0000           0     21.52 Å
  orient_255_pt12__8_pt25__3_a2_t0.1_s6_af2pred         93   178    9   0.0000           0     24.99 Å
  orient_255_pt12__8_pt25__3_a3_t0.1_s3_af2pred         93   178    9   0.0000           0     23.59 Å
  orient_255_pt12__8_pt25__3_a4_t0.1_s1_af2pred         93   178    9   0.0000           0     23.08 Å
  orient_255_pt12__8_pt25__3_a5_t0.1_s8_af2pred         93   178    9   0.0000           0     23.30 Å
  orient_255_pt12__8_pt25__44_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     22.77 Å
  orient_255_pt12__8_pt25__44_a1_t0.1_s6_af2pred        93   178    9   0.0000           0     23.14 Å
  orient_255_pt12__8_pt25__44_a1_t0.1_s7_af2pred        93   178    9   0.0000           0     21.79 Å
  orient_255_pt12__8_pt25__44_a1_t0.1_s8_af2pred        93   178    9   0.0000           0     23.27 Å
  orient_255_pt12__8_pt25__44_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     22.96 Å
  orient_255_pt12__8_pt25__44_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     22.66 Å
  orient_255_pt12__8_pt25__44_a2_t0.1_s4_af2pred        93   178    9   0.0000           0     23.18 Å
  orient_255_pt12__8_pt25__44_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     22.41 Å
  orient_255_pt12__8_pt25__45_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     22.68 Å
  orient_255_pt12__8_pt25__45_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     22.19 Å
  orient_255_pt12__8_pt25__45_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     21.80 Å
  orient_255_pt12__8_pt25__45_a2_t0.1_s3_af2pred        93   178    9   0.0000           0     21.61 Å
  orient_255_pt12__8_pt25__45_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     23.72 Å

  orient_255_pt12__8_pt25__45_a2_t0.1_s7_af2pred        93   178    9   0.0000           0     22.66 Å
  orient_255_pt12__8_pt25__45_a2_t0.1_s8_af2pred        93   178    9   0.0000           0     23.11 Å
  orient_255_pt12__8_pt25__45_a3_t0.1_s1_af2pred        93   178    9   0.0000           0     21.30 Å
  orient_255_pt12__8_pt25__46_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     22.60 Å
  orient_255_pt12__8_pt25__46_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     22.80 Å
  orient_255_pt12__8_pt25__46_a2_t0.1_s1_af2pred        93   178    9   0.0323          43     17.36 Å
  orient_255_pt12__8_pt25__46_a2_t0.1_s2_af2pred        93   178    9   0.0000           0     22.95 Å
  orient_255_pt12__8_pt25__46_a2_t0.1_s3_af2pred        93   178    9   0.1471         138     15.20 Å
  orient_255_pt12__8_pt25__46_a2_t0.1_s5_af2pred        93   178    9   0.0000           0     21.32 Å
  orient_255_pt12__8_pt25__46_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     21.36 Å
  orient_255_pt12__8_pt25__46_a2_t0.1_s7_af2pred        93   178    9   0.0036          23     18.27 Å
  orient_255_pt12__8_pt25__47_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     22.42 Å
  orient_255_pt12__8_pt25__47_a1_t0.1_s3_af2pred        93   178    9   0.0024           1     19.65 Å
  orient_255_pt12__8_pt25__47_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     23.49 Å
  orient_255_pt12__8_pt25__47_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     22.83 Å
  orient_255_pt12__8_pt25__47_a3_t0.1_s5_af2pred        93   178    9   0.0478          55     16.93 Å
  orient_255_pt12__8_pt25__47_a4_t0.1_s1_af2pred        93   178    9   0.0000           0     22.82 Å
  orient_255_pt12__8_pt25__47_a4_t0.1_s3_af2pred        93   178    9   0.0000           0     23.90 Å
  orient_255_pt12__8_pt25__47_a4_t0.1_s4_af2pred        93   178    9   0.0000           0     24.38 Å
  orient_255_pt12__8_pt25__49_a1_t0.1_s1_af2pred        93   178    9   0.0100          28     17.85 Å
  orient_255_pt12__8_pt25__49_a1_t0.1_s4_af2pred        93   178    9   0.0000           0     22.45 Å
  orient_255_pt12__8_pt25__49_a2_t0.1_s1_af2pred        93   178    9   0.0355          44     16.45 Å
  orient_255_pt12__8_pt25__49_a2_t0.1_s2_af2pred        93   178    9   0.3386         331     12.90 Å
  orient_255_pt12__8_pt25__49_a2_t0.1_s3_af2pred        93   178    9   0.0000           0     23.25 Å
  orient_255_pt12__8_pt25__49_a2_t0.1_s4_af2pred        93   178    9   0.0000           0     23.76 Å
  orient_255_pt12__8_pt25__49_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     22.44 Å
  orient_255_pt12__8_pt25__49_a2_t0.1_s7_af2pred        93   178    9   0.0000           0     22.70 Å
  orient_255_pt12__8_pt25__4_a15_t0.15_s4_af2pred       93   178    9   0.5638         693      9.40 Å
  orient_255_pt12__8_pt25__4_a16_t0.15_s3_af2pred       93   178    9   0.0020           1     21.67 Å
  orient_255_pt12__8_pt25__4_a17_t0.15_s1_af2pred       93   178    9   0.6940         789      6.99 Å
  orient_255_pt12__8_pt25__4_a18_t0.15_s7_af2pred       93   178    9   0.1372         124     15.57 Å
  orient_255_pt12__8_pt25__4_a22_t0.2_s2_af2pred        93   178    9   0.7242         796      6.46 Å
  orient_255_pt12__8_pt25__4_a2_t0.1_s7_af2pred         93   178    9   0.6819         776      7.16 Å
  orient_255_pt12__8_pt25__4_a6_t0.1_s2_af2pred         93   178    9   0.7391         808      6.12 Å
  orient_255_pt12__8_pt25__4_a7_t0.1_s8_af2pred         93   178    9   0.1885         176     14.87 Å
  orient_255_pt12__8_pt25__6_a1_t0.1_s2_af2pred         93   178    9   0.0000           0     22.54 Å
  orient_255_pt12__8_pt25__6_a1_t0.1_s3_af2pred         93   178    9   0.0000           0     23.73 Å
  orient_255_pt12__8_pt25__6_a1_t0.1_s5_af2pred         93   178    9   0.0000           0     23.24 Å
  orient_255_pt12__8_pt25__6_a1_t0.1_s7_af2pred         93   178    9   0.0000           0     22.48 Å
  orient_255_pt12__8_pt25__6_a2_t0.1_s4_af2pred         93   178    9   0.0000           0     22.38 Å
  orient_255_pt12__8_pt25__6_a2_t0.1_s5_af2pred         93   178    9   0.0000           0     22.34 Å
  orient_255_pt12__8_pt25__6_a2_t0.1_s6_af2pred         93   178    9   0.0000           0     22.28 Å
  orient_255_pt12__8_pt25__6_a2_t0.1_s7_af2pred         93   178    9   0.0430          50     16.62 Å
  orient_255_pt12__8_pt25__7_a1_t0.1_s1_af2pred         93   178    9   0.0000           0     22.20 Å
  orient_255_pt12__8_pt25__7_a1_t0.1_s3_af2pred         93   178    9   0.0000           0     23.29 Å
  orient_255_pt12__8_pt25__7_a1_t0.1_s4_af2pred         93   178    9   0.0000           0     24.04 Å
  orient_255_pt12__8_pt25__7_a2_t0.1_s2_af2pred         93   178    9   0.0542          62     16.08 Å
  orient_255_pt12__8_pt25__7_a2_t0.1_s6_af2pred         93   178    9   0.0022           1     20.07 Å
  orient_255_pt12__8_pt25__7_a2_t0.1_s7_af2pred         93   178    9   0.0000           0     23.75 Å
  orient_255_pt12__8_pt25__7_a2_t0.1_s8_af2pred         93   178    9   0.0000           0     24.20 Å
  orient_255_pt12__8_pt25__7_a3_t0.1_s2_af2pred         93   178    9   0.0000           0     23.92 Å
  orient_255_pt12__8_pt25__9_a1_t0.1_s5_af2pred         93   178    9   0.0020          12     17.90 Å
  orient_255_pt12__8_pt25__9_a1_t0.1_s8_af2pred         93   178    9   0.0000           0     21.37 Å
  orient_255_pt12__8_pt25__9_a2_t0.1_s8_af2pred         93   178    9   0.0000           0     23.17 Å
  orient_255_pt12__8_pt25__9_a5_t0.1_s2_af2pred         93   178    9   0.0000           0     23.42 Å
  orient_255_pt12__8_pt25__9_a5_t0.1_s3_af2pred         93   178    9   0.0019           1     20.65 Å
  orient_255_pt12__8_pt25__9_a5_t0.1_s4_af2pred         93   178    9   0.0000           0     22.23 Å
  orient_255_pt12__8_pt25__9_a6_t0.1_s2_af2pred         93   178    9   0.0000           0     23.44 Å
  orient_255_pt12__8_pt25__9_a6_t0.1_s4_af2pred         93   178    9   0.0000           0     22.84 Å
  orient_255_pt12__91_pt25__11_a14_t0.15_s4_af2pred      93   178    9   0.0000           0     23.59 Å
  orient_255_pt12__91_pt25__11_a25_t0.2_s1_af2pred      93   178    9   0.0000           0     21.77 Å
  orient_255_pt12__91_pt25__14_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     22.93 Å
  orient_255_pt12__91_pt25__14_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     22.04 Å
  orient_255_pt12__91_pt25__14_a2_t0.1_s8_af2pred       93   178    9   0.0000           0     26.61 Å
  orient_255_pt12__91_pt25__14_a3_t0.1_s1_af2pred       93   178    9   0.0000           0     24.22 Å
  orient_255_pt12__91_pt25__14_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.02 Å
  orient_255_pt12__91_pt25__14_a3_t0.1_s7_af2pred       93   178    9   0.0020           5     19.22 Å
  orient_255_pt12__91_pt25__14_a3_t0.1_s8_af2pred       93   178    9   0.0000           0     22.50 Å
  orient_255_pt12__91_pt25__14_a4_t0.1_s1_af2pred       93   178    9   0.0000           0     23.78 Å
  orient_255_pt12__91_pt25__15_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     23.02 Å
  orient_255_pt12__91_pt25__15_a1_t0.1_s6_af2pred       93   178    9   0.0019           9     19.15 Å
  orient_255_pt12__91_pt25__15_a2_t0.1_s1_af2pred       93   178    9   0.0020           6     19.87 Å
  orient_255_pt12__91_pt25__15_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     22.93 Å
  orient_255_pt12__91_pt25__15_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     23.41 Å
  orient_255_pt12__91_pt25__15_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     22.01 Å
  orient_255_pt12__91_pt25__15_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     21.74 Å
  orient_255_pt12__91_pt25__15_a3_t0.1_s6_af2pred       93   178    9   0.0000           0     24.18 Å
  orient_255_pt12__91_pt25__16_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     23.73 Å
  orient_255_pt12__91_pt25__16_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     24.66 Å
  orient_255_pt12__91_pt25__16_a1_t0.1_s5_af2pred       93   178    9   0.0019           1     21.10 Å
  orient_255_pt12__91_pt25__16_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     23.74 Å
  orient_255_pt12__91_pt25__16_a3_t0.1_s6_af2pred       93   178    9   0.0000           0     23.42 Å
  orient_255_pt12__91_pt25__16_a3_t0.1_s7_af2pred       93   178    9   0.0000           0     27.17 Å
  orient_255_pt12__91_pt25__16_a3_t0.1_s8_af2pred       93   178    9   0.0000           0     25.38 Å
  orient_255_pt12__91_pt25__16_a4_t0.1_s3_af2pred       93   178    9   0.0000           0     23.00 Å

  orient_255_pt12__91_pt25__21_a21_t0.2_s2_af2pred      93   178    9   0.0020          13     18.47 Å
  orient_255_pt12__91_pt25__21_a23_t0.2_s2_af2pred      93   178    9   0.0000           0     23.16 Å
  orient_255_pt12__91_pt25__25_a1_t0.1_s2_af2pred       93   178    9   0.0019           5     19.09 Å
  orient_255_pt12__91_pt25__25_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     23.62 Å
  orient_255_pt12__91_pt25__25_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     21.51 Å
  orient_255_pt12__91_pt25__25_a1_t0.1_s6_af2pred       93   178    9   0.0021           7     19.15 Å
  orient_255_pt12__91_pt25__25_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     21.79 Å
  orient_255_pt12__91_pt25__25_a1_t0.1_s8_af2pred       93   178    9   0.0018          12     17.91 Å
  orient_255_pt12__91_pt25__25_a2_t0.1_s7_af2pred       93   178    9   0.0000           0     22.32 Å
  orient_255_pt12__91_pt25__25_a2_t0.1_s8_af2pred       93   178    9   0.0000           0     21.50 Å
  orient_255_pt12__91_pt25__29_a10_t0.1_s2_af2pred      93   178    9   0.0000           0     22.64 Å
  orient_255_pt12__91_pt25__29_a13_t0.15_s5_af2pred      93   178    9   0.0000           0     24.24 Å
  orient_255_pt12__91_pt25__29_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     24.06 Å
  orient_255_pt12__91_pt25__29_a5_t0.1_s1_af2pred       93   178    9   0.0000           0     23.90 Å
  orient_255_pt12__91_pt25__29_a5_t0.1_s3_af2pred       93   178    9   0.0000           0     22.70 Å
  orient_255_pt12__91_pt25__29_a7_t0.1_s8_af2pred       93   178    9   0.0000           0     22.97 Å
  orient_255_pt12__91_pt25__29_a9_t0.1_s2_af2pred       93   178    9   0.0000           0     23.41 Å
  orient_255_pt12__91_pt25__29_a9_t0.1_s3_af2pred       93   178    9   0.0000           0     22.05 Å
  orient_255_pt12__91_pt25__33_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     25.09 Å
  orient_255_pt12__91_pt25__33_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.60 Å
  orient_255_pt12__91_pt25__33_a3_t0.1_s4_af2pred       93   178    9   0.0000           0     23.03 Å
  orient_255_pt12__91_pt25__33_a3_t0.1_s7_af2pred       93   178    9   0.0020          11     18.45 Å
  orient_255_pt12__91_pt25__33_a4_t0.1_s2_af2pred       93   178    9   0.0000           0     25.34 Å
  orient_255_pt12__91_pt25__33_a4_t0.1_s6_af2pred       93   178    9   0.0000           0     24.05 Å
  orient_255_pt12__91_pt25__33_a5_t0.1_s1_af2pred       93   178    9   0.0000           0     23.23 Å
  orient_255_pt12__91_pt25__33_a5_t0.1_s3_af2pred       93   178    9   0.0000           0     22.05 Å
  orient_255_pt12__91_pt25__37_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     23.00 Å
  orient_255_pt12__91_pt25__37_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     22.24 Å
  orient_255_pt12__91_pt25__37_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     23.03 Å
  orient_255_pt12__91_pt25__37_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     23.21 Å
  orient_255_pt12__91_pt25__37_a1_t0.1_s6_af2pred       93   178    9   0.0146          31     18.07 Å
  orient_255_pt12__91_pt25__37_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     23.22 Å
  orient_255_pt12__91_pt25__37_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     23.75 Å
  orient_255_pt12__91_pt25__37_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.49 Å
  orient_255_pt12__91_pt25__38_a11_t0.15_s2_af2pred      93   178    9   0.0020           6     19.25 Å
  orient_255_pt12__91_pt25__38_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     24.06 Å
  orient_255_pt12__91_pt25__38_a3_t0.1_s4_af2pred       93   178    9   0.3353         394     12.63 Å
  orient_255_pt12__91_pt25__38_a4_t0.1_s4_af2pred       93   178    9   0.0000           0     21.68 Å
  orient_255_pt12__91_pt25__38_a4_t0.1_s6_af2pred       93   178    9   0.0000           0     23.00 Å
  orient_255_pt12__91_pt25__38_a5_t0.1_s2_af2pred       93   178    9   0.0018           3     18.58 Å
  orient_255_pt12__91_pt25__38_a5_t0.1_s3_af2pred       93   178    9   0.0000           0     24.11 Å
  orient_255_pt12__91_pt25__38_a7_t0.1_s2_af2pred       93   178    9   0.7334         813      6.12 Å
  orient_255_pt12__91_pt25__3_a1_t0.1_s1_af2pred        93   178    9   0.0000           0     23.55 Å
  orient_255_pt12__91_pt25__3_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     22.04 Å
  orient_255_pt12__91_pt25__3_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     23.21 Å
  orient_255_pt12__91_pt25__3_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     23.17 Å
  orient_255_pt12__91_pt25__3_a2_t0.1_s5_af2pred        93   178    9   0.0000           0     23.11 Å
  orient_255_pt12__91_pt25__3_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     22.61 Å
  orient_255_pt12__91_pt25__3_a2_t0.1_s8_af2pred        93   178    9   0.0000           0     23.11 Å
  orient_255_pt12__91_pt25__3_a3_t0.1_s1_af2pred        93   178    9   0.0000           0     23.33 Å
  orient_255_pt12__91_pt25__42_a10_t0.1_s2_af2pred      93   178    9   0.0000           0     21.71 Å
  orient_255_pt12__91_pt25__42_a11_t0.15_s5_af2pred      93   178    9   0.0000           0     22.07 Å
  orient_255_pt12__91_pt25__42_a11_t0.15_s6_af2pred      93   178    9   0.0000           0     22.00 Å
  orient_255_pt12__91_pt25__42_a16_t0.15_s3_af2pred      93   178    9   0.0000           0     21.48 Å
  orient_255_pt12__91_pt25__42_a18_t0.15_s2_af2pred      93   178    9   0.0000           0     21.21 Å
  orient_255_pt12__91_pt25__42_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.76 Å
  orient_255_pt12__91_pt25__42_a4_t0.1_s2_af2pred       93   178    9   0.0000           0     23.16 Å
  orient_255_pt12__91_pt25__42_a7_t0.1_s7_af2pred       93   178    9   0.0266          39     17.05 Å
  orient_255_pt12__91_pt25__43_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     22.02 Å
  orient_255_pt12__91_pt25__43_a3_t0.1_s1_af2pred       93   178    9   0.5537         665      9.58 Å
  orient_255_pt12__91_pt25__43_a3_t0.1_s3_af2pred       93   178    9   0.0018           1     20.85 Å
  orient_255_pt12__91_pt25__43_a3_t0.1_s4_af2pred       93   178    9   0.1727         158     14.91 Å
  orient_255_pt12__91_pt25__43_a3_t0.1_s5_af2pred       93   178    9   0.0019           5     19.97 Å
  orient_255_pt12__91_pt25__43_a6_t0.1_s2_af2pred       93   178    9   0.0000           0     22.02 Å
  orient_255_pt12__91_pt25__43_a6_t0.1_s3_af2pred       93   178    9   0.0000           0     22.74 Å
  orient_255_pt12__91_pt25__43_a6_t0.1_s6_af2pred       93   178    9   0.0000           0     21.97 Å
  orient_255_pt12__91_pt25__45_a1_t0.1_s2_af2pred       93   178    9   0.0000           0     22.89 Å
  orient_255_pt12__91_pt25__45_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     22.90 Å
  orient_255_pt12__91_pt25__45_a1_t0.1_s8_af2pred       93   178    9   0.0000           0     23.28 Å
  orient_255_pt12__91_pt25__45_a2_t0.1_s4_af2pred       93   178    9   0.0000           0     25.37 Å
  orient_255_pt12__91_pt25__45_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     25.93 Å
  orient_255_pt12__91_pt25__45_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     21.69 Å
  orient_255_pt12__91_pt25__45_a4_t0.1_s1_af2pred       93   178    9   0.0000           0     23.80 Å
  orient_255_pt12__91_pt25__45_a4_t0.1_s7_af2pred       93   178    9   0.0000           0     22.77 Å
  orient_255_pt12__91_pt25__46_a1_t0.1_s5_af2pred       93   178    9   0.0028          22     18.64 Å
  orient_255_pt12__91_pt25__46_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     22.64 Å
  orient_255_pt12__91_pt25__46_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     21.78 Å
  orient_255_pt12__91_pt25__46_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     22.95 Å
  orient_255_pt12__91_pt25__46_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     22.12 Å
  orient_255_pt12__91_pt25__46_a2_t0.1_s7_af2pred       93   178    9   0.4552         546     11.38 Å
  orient_255_pt12__91_pt25__46_a3_t0.1_s7_af2pred       93   178    9   0.0000           0     24.06 Å
  orient_255_pt12__91_pt25__46_a3_t0.1_s8_af2pred       93   178    9   0.0022          14     18.80 Å
  orient_255_pt12__91_pt25__47_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     25.44 Å
  orient_255_pt12__91_pt25__47_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     24.46 Å
  orient_255_pt12__91_pt25__47_a2_t0.1_s1_af2pred       93   178    9   0.7274         780      6.53 Å
  orient_255_pt12__91_pt25__47_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     27.50 Å

  orient_255_pt12__91_pt25__47_a2_t0.1_s5_af2pred       93   178    9   0.0000           0     21.28 Å
  orient_255_pt12__91_pt25__47_a2_t0.1_s6_af2pred       93   178    9   0.0000           0     22.99 Å
  orient_255_pt12__91_pt25__47_a3_t0.1_s1_af2pred       93   178    9   0.0020           3     21.03 Å
  orient_255_pt12__91_pt25__47_a3_t0.1_s3_af2pred       93   178    9   0.0000           0     22.43 Å
  orient_255_pt12__91_pt25__49_a1_t0.1_s1_af2pred       93   178    9   0.0000           0     22.23 Å
  orient_255_pt12__91_pt25__49_a1_t0.1_s3_af2pred       93   178    9   0.0000           0     22.97 Å
  orient_255_pt12__91_pt25__49_a1_t0.1_s4_af2pred       93   178    9   0.0000           0     22.75 Å
  orient_255_pt12__91_pt25__49_a1_t0.1_s5_af2pred       93   178    9   0.0000           0     23.55 Å
  orient_255_pt12__91_pt25__49_a1_t0.1_s6_af2pred       93   178    9   0.0000           0     21.94 Å
  orient_255_pt12__91_pt25__49_a1_t0.1_s7_af2pred       93   178    9   0.0000           0     23.20 Å
  orient_255_pt12__91_pt25__49_a2_t0.1_s2_af2pred       93   178    9   0.0000           0     23.16 Å
  orient_255_pt12__91_pt25__49_a2_t0.1_s3_af2pred       93   178    9   0.0000           0     22.85 Å
  orient_255_pt12__91_pt25__8_a11_t0.15_s4_af2pred      93   178    9   0.0000           0     22.39 Å
  orient_255_pt12__91_pt25__8_a22_t0.2_s3_af2pred       93   178    9   0.0020           3     20.06 Å
  orient_255_pt12__91_pt25__8_a23_t0.2_s2_af2pred       93   178    9   0.0000           0     22.32 Å
  orient_255_pt12__91_pt25__8_a24_t0.2_s5_af2pred       93   178    9   0.0000           0     22.62 Å
  orient_255_pt12__91_pt25__8_a25_t0.2_s6_af2pred       93   178    9   0.0017           1     21.11 Å
  orient_255_pt12__91_pt25__8_a26_t0.2_s2_af2pred       93   178    9   0.0000           0     21.96 Å
  orient_255_pt12__91_pt25__8_a28_t0.2_s3_af2pred       93   178    9   0.0000           0     21.56 Å
  orient_255_pt12__91_pt25__8_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     21.61 Å
  orient_34_pt12__67_pt12__0_a1_t0.1_s3_af2pred         93   178    9   0.0000           0     23.71 Å
  orient_34_pt12__67_pt12__0_a1_t0.1_s4_af2pred         93   178    9   0.0000           0     24.47 Å
  orient_34_pt12__67_pt12__0_a1_t0.1_s7_af2pred         93   178    9   0.5521         690      9.52 Å
  orient_34_pt12__67_pt12__0_a2_t0.1_s1_af2pred         93   178    9   0.0000           0     23.96 Å
  orient_34_pt12__67_pt12__0_a2_t0.1_s3_af2pred         93   178    9   0.0000           0     23.74 Å
  orient_34_pt12__67_pt12__0_a2_t0.1_s5_af2pred         93   178    9   0.0000           0     24.56 Å
  orient_34_pt12__67_pt12__0_a2_t0.1_s6_af2pred         93   178    9   0.0000           0     24.76 Å
  orient_34_pt12__67_pt12__0_a3_t0.1_s6_af2pred         93   178    9   0.0000           0     23.73 Å
  orient_34_pt12__67_pt12__15_a27_t0.2_s5_af2pred       93   178    9   0.0000           0     26.35 Å
  orient_34_pt12__67_pt12__15_a28_t0.2_s8_af2pred       93   178    9   0.0000           0     23.66 Å
  orient_34_pt12__67_pt12__15_a3_t0.1_s6_af2pred        93   178    9   0.0000           0     24.83 Å
  orient_34_pt12__67_pt12__24_a10_t0.1_s5_af2pred       93   178    9   0.0000           0     23.94 Å
  orient_34_pt12__67_pt12__24_a11_t0.15_s3_af2pred      93   178    9   0.0021           5     19.78 Å
  orient_34_pt12__67_pt12__24_a15_t0.15_s8_af2pred      93   178    9   0.0000           0     22.99 Å
  orient_34_pt12__67_pt12__24_a17_t0.15_s3_af2pred      93   178    9   0.6994         748      7.15 Å
  orient_34_pt12__67_pt12__24_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     23.93 Å
  orient_34_pt12__67_pt12__24_a3_t0.1_s7_af2pred        93   178    9   0.0038          23     17.81 Å
  orient_34_pt12__67_pt12__24_a5_t0.1_s6_af2pred        93   178    9   0.7552         809      5.79 Å
  orient_34_pt12__67_pt12__24_a6_t0.1_s6_af2pred        93   178    9   0.0000           0     21.35 Å
  orient_34_pt12__67_pt12__30_a10_t0.1_s1_af2pred       93   178    9   0.0000           0     24.46 Å
  orient_34_pt12__67_pt12__30_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     26.90 Å
  orient_34_pt12__67_pt12__30_a3_t0.1_s6_af2pred        93   178    9   0.0021          14     18.70 Å
  orient_34_pt12__67_pt12__30_a4_t0.1_s2_af2pred        93   178    9   0.0000           0     26.11 Å
  orient_34_pt12__67_pt12__30_a4_t0.1_s3_af2pred        93   178    9   0.0051          24     18.06 Å
  orient_34_pt12__67_pt12__30_a5_t0.1_s2_af2pred        93   178    9   0.0000           0     24.98 Å
  orient_34_pt12__67_pt12__30_a5_t0.1_s3_af2pred        93   178    9   0.7006         790      6.80 Å
  orient_34_pt12__67_pt12__30_a5_t0.1_s4_af2pred        93   178    9   0.8221         814      4.75 Å
  orient_34_pt12__67_pt12__33_a1_t0.1_s2_af2pred        93   178    9   0.0000           0     23.95 Å
  orient_34_pt12__67_pt12__33_a3_t0.1_s8_af2pred        93   178    9   0.0000           0     25.41 Å
  orient_34_pt12__67_pt12__33_a4_t0.1_s4_af2pred        93   178    9   0.0000           0     25.18 Å
  orient_34_pt12__67_pt12__33_a4_t0.1_s8_af2pred        93   178    9   0.0000           0     24.13 Å
  orient_34_pt12__67_pt12__33_a6_t0.1_s4_af2pred        93   178    9   0.0000           0     24.09 Å
  orient_34_pt12__67_pt12__33_a6_t0.1_s7_af2pred        93   178    9   0.0000           0     25.10 Å
  orient_34_pt12__67_pt12__33_a6_t0.1_s8_af2pred        93   178    9   0.0000           0     23.64 Å
  orient_34_pt12__67_pt12__33_a7_t0.1_s8_af2pred        93   178    9   0.0000           0     24.18 Å
  orient_34_pt12__67_pt12__37_a10_t0.1_s2_af2pred       93   178    9   0.0000           0     23.63 Å
  orient_34_pt12__67_pt12__37_a16_t0.15_s2_af2pred      93   178    9   0.0809          81     16.24 Å
  orient_34_pt12__67_pt12__37_a16_t0.15_s3_af2pred      93   178    9   0.6405         744      8.01 Å
  orient_34_pt12__67_pt12__37_a18_t0.15_s7_af2pred      93   178    9   0.0000           0     23.65 Å
  orient_34_pt12__67_pt12__37_a21_t0.2_s8_af2pred       93   178    9   0.0080          26     17.64 Å
  orient_34_pt12__67_pt12__37_a23_t0.2_s1_af2pred       93   178    9   0.7503         820      5.80 Å
  orient_34_pt12__67_pt12__37_a28_t0.2_s2_af2pred       93   178    9   0.0000           0     23.02 Å
  orient_34_pt12__67_pt12__37_a3_t0.1_s8_af2pred        93   178    9   0.0000           0     22.95 Å
  orient_34_pt12__67_pt12__38_a11_t0.15_s3_af2pred      93   178    9   0.0000           0     23.45 Å
  orient_34_pt12__67_pt12__38_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     24.39 Å
  orient_34_pt12__67_pt12__38_a2_t0.1_s6_af2pred        93   178    9   0.0000           0     24.01 Å
  orient_34_pt12__67_pt12__38_a4_t0.1_s2_af2pred        93   178    9   0.0000           0     24.18 Å
  orient_34_pt12__67_pt12__38_a4_t0.1_s4_af2pred        93   178    9   0.0000           0     24.55 Å
  orient_34_pt12__67_pt12__38_a4_t0.1_s5_af2pred        93   178    9   0.0000           0     24.27 Å
  orient_34_pt12__67_pt12__38_a5_t0.1_s1_af2pred        93   178    9   0.0000           0     23.91 Å
  orient_34_pt12__67_pt12__38_a7_t0.1_s4_af2pred        93   178    9   0.0000           0     23.13 Å
  orient_34_pt12__67_pt12__46_a1_t0.1_s3_af2pred        93   178    9   0.0504          54     17.19 Å
  orient_34_pt12__67_pt12__46_a1_t0.1_s8_af2pred        93   178    9   0.8133         827      4.75 Å
  orient_34_pt12__67_pt12__46_a3_t0.1_s2_af2pred        93   178    9   0.1687         149     15.37 Å
  orient_34_pt12__67_pt12__46_a3_t0.1_s8_af2pred        93   178    9   0.0000           0     20.11 Å
  orient_34_pt12__67_pt12__46_a4_t0.1_s2_af2pred        93   178    9   0.0019           6     19.16 Å
  orient_34_pt12__67_pt12__46_a4_t0.1_s8_af2pred        93   178    9   0.6469         752      7.86 Å
  orient_34_pt12__67_pt12__46_a5_t0.1_s1_af2pred        93   178    9   0.6668         776      7.41 Å
  orient_34_pt12__67_pt12__46_a5_t0.1_s2_af2pred        93   178    9   0.0000           0     23.48 Å
  orient_34_pt12__67_pt12__52_a1_t0.1_s3_af2pred        93   178    9   0.5065         579     10.42 Å
  orient_34_pt12__67_pt12__52_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     22.95 Å
  orient_34_pt12__67_pt12__52_a3_t0.1_s8_af2pred        93   178    9   0.0018           1     20.98 Å
  orient_34_pt12__67_pt12__52_a4_t0.1_s2_af2pred        93   178    9   0.7776         810      5.52 Å
  orient_34_pt12__67_pt12__52_a4_t0.1_s5_af2pred        93   178    9   0.0000           0     23.93 Å

  orient_34_pt12__67_pt12__52_a5_t0.1_s5_af2pred        93   178    9   0.0000           0     22.43 Å
  orient_34_pt12__67_pt12__52_a6_t0.1_s6_af2pred        93   178    9   0.0020           5     20.49 Å
  orient_34_pt12__67_pt12__52_a9_t0.1_s1_af2pred        93   178    9   0.0000           0     24.26 Å
  orient_34_pt12__67_pt12__57_a11_t0.15_s4_af2pred      93   178    9   0.0000           0     27.32 Å
  orient_34_pt12__67_pt12__57_a18_t0.15_s5_af2pred      93   178    9   0.0000           0     25.46 Å
  orient_34_pt12__67_pt12__57_a22_t0.2_s2_af2pred       93   178    9   0.0000           0     26.70 Å
  orient_34_pt12__67_pt12__57_a22_t0.2_s8_af2pred       93   178    9   0.0000           0     23.35 Å
  orient_34_pt12__67_pt12__57_a23_t0.2_s5_af2pred       93   178    9   0.0000           0     27.40 Å
  orient_34_pt12__67_pt12__57_a25_t0.2_s4_af2pred       93   178    9   0.0000           0     26.55 Å
  orient_34_pt12__67_pt12__57_a8_t0.1_s4_af2pred        93   178    9   0.0000           0     23.81 Å
  orient_34_pt12__67_pt12__60_a10_t0.1_s2_af2pred       93   178    9   0.0000           0     23.88 Å
  orient_34_pt12__67_pt12__60_a10_t0.1_s5_af2pred       93   178    9   0.0000           0     23.54 Å
  orient_34_pt12__67_pt12__60_a11_t0.15_s4_af2pred      93   178    9   0.0000           0     24.69 Å
  orient_34_pt12__67_pt12__60_a5_t0.1_s6_af2pred        93   178    9   0.0000           0     23.62 Å
  orient_34_pt12__67_pt12__60_a5_t0.1_s8_af2pred        93   178    9   0.0000           0     23.14 Å
  orient_34_pt12__67_pt12__60_a6_t0.1_s1_af2pred        93   178    9   0.0000           0     24.19 Å
  orient_34_pt12__67_pt12__60_a6_t0.1_s2_af2pred        93   178    9   0.0018           1     20.59 Å
  orient_34_pt12__67_pt12__60_a9_t0.1_s4_af2pred        93   178    9   0.0020          10     19.67 Å
  orient_34_pt12__67_pt12__64_a10_t0.1_s1_af2pred       93   178    9   0.0000           0     23.69 Å
  orient_34_pt12__67_pt12__64_a11_t0.15_s4_af2pred      93   178    9   0.7587         817      5.72 Å
  orient_34_pt12__67_pt12__64_a11_t0.15_s7_af2pred      93   178    9   0.0000           0     23.82 Å
  orient_34_pt12__67_pt12__64_a14_t0.15_s3_af2pred      93   178    9   0.0000           0     23.53 Å
  orient_34_pt12__67_pt12__64_a16_t0.15_s4_af2pred      93   178    9   0.0018           1     22.21 Å
  orient_34_pt12__67_pt12__64_a19_t0.15_s6_af2pred      93   178    9   0.0000           0     23.32 Å
  orient_34_pt12__67_pt12__64_a4_t0.1_s2_af2pred        93   178    9   0.0000           0     23.10 Å
  orient_34_pt12__67_pt12__64_a8_t0.1_s4_af2pred        93   178    9   0.0000           0     23.99 Å
  orient_34_pt12__67_pt12__65_a11_t0.15_s2_af2pred      93   178    9   0.0000           0     23.74 Å
  orient_34_pt12__67_pt12__65_a12_t0.15_s1_af2pred      93   178    9   0.0000           0     24.75 Å
  orient_34_pt12__67_pt12__65_a18_t0.15_s1_af2pred      93   178    9   0.3408         350     13.35 Å
  orient_34_pt12__67_pt12__65_a2_t0.1_s3_af2pred        93   178    9   0.0000           0     23.82 Å
  orient_34_pt12__67_pt12__65_a2_t0.1_s4_af2pred        93   178    9   0.0000           0     23.63 Å
  orient_34_pt12__67_pt12__65_a4_t0.1_s2_af2pred        93   178    9   0.0000           0     23.57 Å
  orient_34_pt12__67_pt12__65_a4_t0.1_s8_af2pred        93   178    9   0.0000           0     21.98 Å
  orient_34_pt12__67_pt12__65_a5_t0.1_s5_af2pred        93   178    9   0.0000           0     23.26 Å
  orient_34_pt12__67_pt12__69_a1_t0.1_s3_af2pred        93   178    9   0.0000           0     22.77 Å
  orient_34_pt12__67_pt12__69_a1_t0.1_s8_af2pred        93   178    9   0.2299         214     14.18 Å
  orient_34_pt12__67_pt12__69_a2_t0.1_s1_af2pred        93   178    9   0.0000           0     23.74 Å
  orient_34_pt12__67_pt12__69_a3_t0.1_s8_af2pred        93   178    9   0.7869         810      5.34 Å
  orient_34_pt12__67_pt12__69_a4_t0.1_s8_af2pred        93   178    9   0.0000           0     26.71 Å
  orient_34_pt12__67_pt12__69_a5_t0.1_s6_af2pred        93   178    9   0.0000           0     24.37 Å
  orient_34_pt12__67_pt12__69_a8_t0.1_s5_af2pred        93   178    9   0.0019           4     18.62 Å
  orient_34_pt12__67_pt12__69_a9_t0.1_s6_af2pred        93   178    9   0.5483         688      9.42 Å
  orient_34_pt12__67_pt12__81_a1_t0.1_s2_af2pred        93   178    9   0.0000           0     24.85 Å
  orient_34_pt12__67_pt12__81_a1_t0.1_s5_af2pred        93   178    9   0.0000           0     24.29 Å
  orient_34_pt12__67_pt12__81_a1_t0.1_s8_af2pred        93   178    9   0.0000           0     23.54 Å
  orient_34_pt12__67_pt12__81_a2_t0.1_s3_af2pred        93   178    9   0.0000           0     23.94 Å
  orient_34_pt12__67_pt12__81_a3_t0.1_s4_af2pred        93   178    9   0.0000           0     23.73 Å
  orient_34_pt12__67_pt12__81_a3_t0.1_s5_af2pred        93   178    9   0.0000           0     23.32 Å
  orient_34_pt12__67_pt12__81_a3_t0.1_s6_af2pred        93   178    9   0.0000           0     24.34 Å
  orient_34_pt12__67_pt12__81_a3_t0.1_s7_af2pred        93   178    9   0.0000           0     23.07 Å
  orient_34_pt12__67_pt12__85_a11_t0.15_s2_af2pred      93   178    9   0.0000           0     24.72 Å
  orient_34_pt12__67_pt12__85_a11_t0.15_s3_af2pred      93   178    9   0.0000           0     23.17 Å
  orient_34_pt12__67_pt12__85_a1_t0.1_s3_af2pred        93   178    9   0.4030         441     11.87 Å
  orient_34_pt12__67_pt12__85_a2_t0.1_s3_af2pred        93   178    9   0.0000           0     23.23 Å
  orient_34_pt12__67_pt12__85_a2_t0.1_s8_af2pred        93   178    9   0.0000           0     22.32 Å
  orient_34_pt12__67_pt12__85_a4_t0.1_s2_af2pred        93   178    9   0.0000           0     25.98 Å
  orient_34_pt12__67_pt12__85_a4_t0.1_s5_af2pred        93   178    9   0.0000           0     23.50 Å
  orient_34_pt12__67_pt12__85_a8_t0.1_s4_af2pred        93   178    9   0.0000           0     23.76 Å
  orient_34_pt12__67_pt12__8_a11_t0.15_s4_af2pred       93   178    9   0.0000           0     21.97 Å
  orient_34_pt12__67_pt12__8_a11_t0.15_s6_af2pred       93   178    9   0.3849         403     12.28 Å
  orient_34_pt12__67_pt12__8_a11_t0.15_s7_af2pred       93   178    9   0.0000           0     23.58 Å
  orient_34_pt12__67_pt12__8_a15_t0.15_s5_af2pred       93   178    9   0.8056         824      4.90 Å
  orient_34_pt12__67_pt12__8_a16_t0.15_s2_af2pred       93   178    9   0.0090          27     18.03 Å
  orient_34_pt12__67_pt12__8_a4_t0.1_s3_af2pred         93   178    9   0.0000           0     23.21 Å
  orient_34_pt12__67_pt12__8_a4_t0.1_s7_af2pred         93   178    9   0.0000           0     25.57 Å
  orient_34_pt12__67_pt12__8_a8_t0.1_s4_af2pred         93   178    9   0.0000           0     22.87 Å

Scored 2701 designs at PAE cutoff = 12.0 Å

In [5]:
results_df[results_df['n_contacts']>0].sort_values(by='ipsae_binder_peptide', ascending=False)

,label,chain_lengths,ipsae_binder_peptide,ipsae_bp,ipsae_pb,n_contacts,d0,mean_pae_bp,mean_pae_contact
1431,orient_255_pt12__33_pt12__81_a4_t0.1_s5_af2pred,"{'binder': 93, 'MHC': 178, 'peptide': 9}",0.8959,0.8959,0.6658,824,9.754,3.421,3.204
1414,orient_255_pt12__33_pt12__7_a4_t0.1_s4_af2pred,"{'binder': 93, 'MHC': 178, 'peptide': 9}",0.8940,0.8940,0.7512,820,9.735,3.523,3.207
28,orient_252_pt20__31_pt12__27_a7_t0.1_s4_af2pred,"{'binder': 97, 'MHC': 178, 'peptide': 9}",0.8846,0.8846,0.6154,860,9.923,3.645,3.471
2019,orient_255_pt12__70_pt12__37_a1_t0.1_s8_af2pred,"{'binder': 93, 'MHC': 178, 'peptide': 9}",0.8846,0.8846,0.6648,837,9.816,3.435,3.435
1256,orient_255_pt12__33_pt12__26_a28_t0.2_s6_af2pred,"{'binder': 93, 'MHC': 178, 'peptide': 9}",0.8833,0.8833,0.6840,826,9.764,3.575,3.431
...,...,...,...,...,...,...,...,...,...
1133,orient_255_pt12__31_pt12__65_a1_t0.1_s7_af2pred,"{'binder': 93, 'MHC': 178, 'peptide': 9}",0.0017,0.0017,0.0000,1,0.500,20.466,11.945
192,orient_255_pt12__18_pt12__29_a28_t0.2_s3_af2pred,"{'binder': 93, 'MHC': 178, 'peptide': 9}",0.0017,0.0017,0.0000,1,0.500,21.376,11.969
1452,orient_255_pt12__33_pt12__88_a3_t0.1_s5_af2pred,"{'binder': 93, 'MHC': 178, 'peptide': 9}",0.0017,0.0017,0.0000,1,0.500,21.491,11.963
1578,orient_255_pt12__46_pt12__26_a2_t0.1_s2_af2pred,"{'binder': 93, 'MHC': 178, 'peptide': 9}",0.0017,0.0017,0.0000,1,0.500,21.393,11.944
2567,orient_255_pt12__91_pt25__8_a25_t0.2_s6_af2pred,"{'binder': 93, 'MHC': 178, 'peptide': 9}",0.0017,0.0017,0.0000,1,0.500,21.106,11.959

In [6]:
len(results_df[results_df['n_contacts']>0].sort_values(by='ipsae_binder_peptide', ascending=False))

1281

In [7]:
ipae_df = pd.read_csv('/n/groups/marks/users/aaron/pmhc_cp/af_init_guess/outputs/r3/af2_kras_all_scores.csv')
merged_df = pd.merge(results_df[results_df['n_contacts']>0], ipae_df, how='left', left_on='label', right_on='description')
merged_df = merged_df[['label', 'ipsae_binder_peptide', 'ipsae_bp', 'ipsae_pb', 'n_contacts', 'd0', 'mean_pae_bp', 'mean_pae_contact', 'binder_aligned_rmsd', 'target_aligned_rmsd', 'pae_interaction', 'plddt_binder', 'plddt_target']]
pd.set_option('display.max_rows', None)
merged_df[merged_df['pae_interaction']<5].sort_values(by='ipsae_binder_peptide', ascending=False)

,label,ipsae_binder_peptide,ipsae_bp,ipsae_pb,n_contacts,d0,mean_pae_bp,mean_pae_contact,binder_aligned_rmsd,target_aligned_rmsd,pae_interaction,plddt_binder,plddt_target
770,orient_255_pt12__33_pt12__81_a4_t0.1_s5_af2pred,0.8959,0.8959,0.6658,824,9.754,3.421,3.204,0.357,1.511,3.859,95.889,95.594
755,orient_255_pt12__33_pt12__7_a4_t0.1_s4_af2pred,0.8940,0.8940,0.7512,820,9.735,3.523,3.207,0.700,1.556,4.085,94.430,95.992
15,orient_252_pt20__31_pt12__27_a7_t0.1_s4_af2pred,0.8846,0.8846,0.6154,860,9.923,3.645,3.471,0.602,0.782,3.982,95.205,95.177
1035,orient_255_pt12__70_pt12__37_a1_t0.1_s8_af2pred,0.8846,0.8846,0.6648,837,9.816,3.435,3.435,0.511,1.480,4.026,95.579,95.413
660,orient_255_pt12__33_pt12__26_a28_t0.2_s6_af2pred,0.8833,0.8833,0.6840,826,9.764,3.575,3.431,0.555,2.287,4.255,94.835,95.378
753,orient_255_pt12__33_pt12__7_a2_t0.1_s1_af2pred,0.8831,0.8831,0.6908,836,9.811,3.452,3.442,0.689,1.596,4.168,95.332,95.631
732,orient_255_pt12__33_pt12__67_a3_t0.1_s8_af2pred,0.8818,0.8818,0.6824,834,9.802,3.517,3.484,0.631,1.339,4.150,94.830,95.453
13,orient_252_pt20__31_pt12__27_a2_t0.1_s1_af2pred,0.8813,0.8813,0.6475,870,9.969,3.592,3.558,0.562,1.230,4.212,94.756,95.167
32,orient_252_pt20__31_pt12__97_a1_t0.1_s1_af2pred,0.8802,0.8802,0.6231,873,9.983,3.569,3.569,0.494,0.835,4.073,94.890,94.950
1059,orient_255_pt12__70_pt12__46_a1_t0.1_s2_af2pred,0.8784,0.8784,0.6938,816,9.716,3.869,3.501,0.753,1.214,4.436,94.216,95.369
754,orient_255_pt12__33_pt12__7_a3_t0.1_s5_af2pred,0.8765,0.8765,0.7041,832,9.792,3.619,3.558,0.511,1.193,4.281,93.882,95.535
22,orient_252_pt20__31_pt12__53_a2_t0.1_s8_af2pred,0.8753,0.8753,0.5965,873,9.983,3.658,3.658,0.615,1.074,4.174,95.091,94.659
752,orient_255_pt12__33_pt12__7_a1_t0.1_s8_af2pred,0.8723,0.8723,0.6989,774,9.511,4.782,3.527,1.165,1.668,4.969,91.330,95.470
1,orient_252_pt20__31_pt12__0_a3_t0.1_s3_af2pred,0.8721,0.8721,0.6397,868,9.960,3.759,3.708,0.752,1.109,4.546,95.135,94.920
731,orient_255_pt12__33_pt12__67_a2_t0.1_s1_af2pred,0.8700,0.8700,0.6511,826,9.764,3.805,3.661,0.525,2.140,4.779,94.328,95.048
276,orient_255_pt12__2_pt12__13_a2_t0.1_s3_af2pred,0.8693,0.8693,0.6217,837,9.816,3.696,3.696,0.618,2.022,4.059,95.723,95.264
767,orient_255_pt12__33_pt12__81_a1_t0.1_s7_af2pred,0.8669,0.8669,0.6581,832,9.792,3.777,3.721,0.537,1.746,4.177,94.753,95.483
1103,orient_255_pt12__70_pt12__68_a3_t0.1_s4_af2pred,0.8668,0.8668,0.6455,822,9.745,3.976,3.701,0.536,0.872,4.445,94.533,95.177
629,orient_255_pt12__31_pt12__93_a1_t0.1_s4_af2pred,0.8657,0.8657,0.6636,828,9.773,3.849,3.733,0.494,0.948,4.412,94.917,95.224
27,orient_252_pt20__31_pt12__72_a5_t0.1_s3_af2pred,0.8652,0.8652,0.6080,870,9.969,3.851,3.819,0.594,0.882,3.970,94.540,94.902
635,orient_255_pt12__33_pt12__10_a1_t0.1_s5_af2pred,0.8648,0.8648,0.6634,826,9.764,3.899,3.739,0.885,2.205,4.308,93.966,95.472
35,orient_252_pt20__31_pt12__97_a3_t0.1_s5_af2pred,0.8648,0.8648,0.6331,873,9.983,3.822,3.822,0.626,1.141,4.285,93.892,94.929
19,orient_252_pt20__31_pt12__53_a1_t0.1_s3_af2pred,0.8643,0.8643,0.5964,861,9.928,4.024,3.829,0.572,1.140,4.516,94.456,94.607
7,orient_252_pt20__31_pt12__16_a1_t0.1_s5_af2pred,0.8641,0.8641,0.5422,864,9.942,3.969,3.843,0.462,0.723,4.243,95.018,94.377
461,orient_255_pt12__2_pt12__99_a10_t0.1_s6_af2pred,0.8640,0.8640,0.7284,837,9.816,3.771,3.771,1.016,2.267,4.463,93.498,95.685
1067,orient_255_pt12__70_pt12__51_a3_t0.1_s1_af2pred,0.8639,0.8639,0.6973,835,9.806,3.788,3.767,0.674,1.253,4.326,94.634,95.418
371,orient_255_pt12__2_pt12__3_a1_t0.1_s7_af2pred,0.8639,0.8639,0.6439,819,9.730,4.167,3.759,0.780,2.055,4.517,93.922,95.300
815,orient_255_pt12__46_pt12__12_a1_t0.1_s7_af2pred,0.8633,0.8633,0.6341,827,9.768,3.990,3.780,0.549,2.539,4.519,94.671,95.120
659,orient_255_pt12__33_pt12__26_a27_t0.2_s2_af2pred,0.8628,0.8628,0.6726,827,9.768,3.929,3.797,0.680,2.327,4.463,93.772,95.375
1025,orient_255_pt12__70_pt12__2_a2_t0.1_s6_af2pred,0.8623,0.8623,0.6748,830,9.783,3.868,3.788,0.350,0.995,4.506,94.014,95.231
681,orient_255_pt12__33_pt12__37_a1_t0.1_s8_af2pred,0.8609,0.8609,0.6456,835,9.806,3.845,3.825,0.416,1.296,4.033,94.936,95.410
0,orient_252_pt20__31_pt12__0_a14_t0.15_s8_af2pred,0.8607,0.8607,0.6506,853,9.891,4.204,3.871,0.572,1.540,4.784,92.467,94.924
264,orient_255_pt12__2_pt12__12_a1_t0.1_s7_af2pred,0.8607,0.8607,0.7104,824,9.754,3.972,3.786,0.664,1.898,4.617,94.089,95.404
896,orient_255_pt12__46_pt12__44_a1_t0.1_s7_af2pred,0.8606,0.8606,0.6241,828,9.773,3.956,3.821,0.821,2.506,4.421,95.247,95.108
1071,orient_255_pt12__70_pt12__51_a6_t0.1_s5_af2pred,0.8602,0.8602,0.6273,837,9.816,3.855,3.855,0.475,1.201,4.301,95.601,95.219
1060,orient_255_pt12__70_pt12__46_a1_t0.1_s3_af2pred,0.8598,0.8598,0.6265,821,9.740,4.131,3.843,0.698,1.114,4.908,94.029,94.925
991,orient_255_pt12__53_pt25__9_a1_t0.1_s1_af2pred,0.8596,0.8596,0.6416,828,9.773,3.944,3.838,0.630,0.733,4.888,94.465,94.972
693,orient_255_pt12__33_pt12__43_a2_t0.1_s2_af2pred,0.8593,0.8593,0.6447,830,9.783,3.922,3.837,0.513,2.087,4.632,94.246,95.193
771,orient_255_pt12__33_pt12__81_a7_t0.1_s2_af2pred,0.8584,0.8584,0.6333,826,9.764,4.032,3.855,0.687,2.476,4.711,93.879,95.085
417,orient_255_pt12__2_pt12__5_a1_t0.1_s1_af2pred,0.8573,0.8573,0.7262,827,9.768,3.983,3.860,0.576,1.010,4.743,93.501,95.279
198,orient_255_pt12__18_pt12__90_a9_t0.1_s8_af2pred,0.8572,0.8572,0.7201,806,9.668,4.276,3.837,0.660,1.795,4.932,91.965,95.351
703,orient_255_pt12__33_pt12__56_a4_t0.1_s4_af2pred,0.8565,0.8565,0.6722,832,9.792,3.946,3.887,0.640,1.284,4.340,93.242,95.463
684,orient_255_pt12__33_pt12__37_a2_t0.1_s7_af2pred,0.8565,0.8565,0.6340,837,9.816,3.921,3.921,0.447,1.244,4.280,94.611,95.221
932,orient_255_pt12__46_pt12__82_a3_t0.1_s3_af2pred,0.8562,0.8562,0.6864,828,9.773,4.013,3.891,0.728,3.659,4.976,93.300,95.156
1147,orient_255_pt12__70_pt12__94_a1_t0.1_s7_af2pred,0.8559,0.8559,0.6368,836,9.811,3.933,3.923,0.638,1.552,4.853,94.522,94.921
1061,orient_255_pt12__70_pt12__46_a1_t0.1_s7_af2pred,0.8558,0.8558,0.6514,819,9.730,4.258,3.896,0.920,1.591,4.844,94.361,95.093
1095,orient_255_pt12__70_pt12__66_a2_t0.1_s6_af2pred,0.8556,0.8556,0.6450,834,9.802,3.958,3.928,0.614,1.934,4.444,94.012,95.099
423,orient_255_pt12__2_pt12__5_a2_t0.1_s1_af2pred,0.8553,0.8553,0.6726,836,9.811,3.938,3.928,0.515,1.649,4.609,93.542,95.115
671,orient_255_pt12__33_pt12__31_a1_t0.1_s7_af2pred,0.8547,0.8547,0.6175,834,9.802,3.984,3.948,0.733,2.008,4.411,94.613,95.294
274,orient_255_pt12__2_pt12__13_a2_t0.1_s1_af2pred,0.8541,0.8541,0.6111,837,9.816,3.949,3.949,0.448,1.826,4.143,94.191,95.233
1012,orient_255_pt12__70_pt12__18_a5_t0.1_s2_af2pred,0.8518,0.8518,0.6975,836,9.811,4.004,3.995,0.435,1.695,4.508,93.016,95.377
586,orient_255_pt12__31_pt12__67_a1_t0.1_s6_af2pred,0.8515,0.8515,0.6144,819,9.730,4.269,3.963,0.578,3.974,4.692,94.415,94.986
946,orient_255_pt12__46_pt12__99_a3_t0.1_s2_af2pred,0.8513,0.8513,0.6588,809,9.682,4.276,3.940,0.382,2.252,4.900,93.960,95.197
404,orient_255_pt12__2_pt12__53_a2_t0.1_s2_af2pred,0.8506,0.8506,0.6985,837,9.816,3.989,3.989,0.557,0.919,4.801,92.422,95.145
1019,orient_255_pt12__70_pt12__24_a2_t0.1_s4_af2pred,0.8503,0.8503,0.6775,823,9.749,4.175,3.992,1.076,1.769,4.428,93.305,95.468
995,orient_255_pt12__70_pt12__12_a13_t0.15_s6_af2pred,0.8495,0.8495,0.6504,832,9.792,4.099,4.042,0.599,1.338,4.799,93.827,95.176
816,orient_255_pt12__46_pt12__12_a1_t0.1_s8_af2pred,0.8495,0.8495,0.5999,836,9.811,4.042,4.032,0.599,1.829,4.770,94.882,94.922
1140,orient_255_pt12__70_pt12__86_a6_t0.1_s2_af2pred,0.8494,0.8494,0.6183,837,9.816,4.053,4.053,0.592,1.935,4.732,94.457,95.166
479,orient_255_pt12__31_pt12__15_a3_t0.1_s5_af2pred,0.8493,0.8493,0.6228,829,9.778,4.111,4.016,0.470,1.977,4.861,94.721,95.081
1126,orient_255_pt12__70_pt12__75_a2_t0.1_s6_af2pred,0.8492,0.8492,0.6170,835,9.806,4.071,4.051,0.476,0.738,4.908,93.998,95.154
195,orient_255_pt12__18_pt12__90_a20_t0.15_s3_af2pred,0.8491,0.8491,0.6331,804,9.658,4.388,3.977,0.461,1.742,4.604,93.044,95.220
751,orient_255_pt12__33_pt12__7_a10_t0.1_s2_af2pred,0.8484,0.8484,0.6307,805,9.663,4.440,3.979,0.998,1.567,4.658,91.980,95.050
680,orient_255_pt12__33_pt12__37_a1_t0.1_s2_af2pred,0.8481,0.8481,0.5862,835,9.806,4.082,4.062,0.359,1.519,4.633,95.256,95.037
380,orient_255_pt12__2_pt12__43_a10_t0.1_s1_af2pred,0.8479,0.8479,0.6837,834,9.802,4.086,4.055,0.547,1.055,4.691,94.046,95.284
864,orient_255_pt12__46_pt12__27_a1_t0.1_s2_af2pred,0.8468,0.8468,0.6580,821,9.740,4.339,4.042,0.844,1.675,4.721,93.779,95.297
37,orient_252_pt20__31_pt12__97_a7_t0.1_s2_af2pred,0.8464,0.8464,0.5763,868,9.960,4.199,4.150,0.555,1.253,4.817,92.739,94.348
757,orient_255_pt12__33_pt12__7_a9_t0.1_s7_af2pred,0.8459,0.8459,0.6490,819,9.730,4.373,4.053,0.832,1.448,4.956,91.856,95.107
1092,orient_255_pt12__70_pt12__66_a1_t0.1_s6_af2pred,0.8456,0.8456,0.6181,836,9.811,4.115,4.104,0.430,1.467,4.838,93.601,94.846
811,orient_255_pt12__46_pt12__11_a3_t0.1_s3_af2pred,0.8453,0.8453,0.6442,833,9.797,4.166,4.119,0.747,1.107,4.913,92.740,95.164
275,orient_255_pt12__2_pt12__13_a2_t0.1_s2_af2pred,0.8450,0.8450,0.6239,837,9.816,4.100,4.100,0.547,2.040,4.865,94.781,94.890
1070,orient_255_pt12__70_pt12__51_a5_t0.1_s8_af2pred,0.8426,0.8426,0.6403,829,9.778,4.236,4.121,0.485,1.107,4.692,93.504,95.089
622,orient_255_pt12__31_pt12__90_a1_t0.1_s5_af2pred,0.8412,0.8412,0.6468,835,9.806,4.182,4.161,0.541,2.712,4.927,94.233,94.988
146,orient_255_pt12__18_pt12__66_a1_t0.1_s4_af2pred,0.8407,0.8407,0.5888,827,9.768,4.292,4.160,1.134,1.548,4.931,93.461,94.529
416,orient_255_pt12__2_pt12__57_a2_t0.1_s4_af2pred,0.8406,0.8406,0.5834,829,9.778,4.279,4.171,0.658,1.906,4.866,94.115,94.871
711,orient_255_pt12__33_pt12__60_a1_t0.1_s5_af2pred,0.8404,0.8404,0.6273,799,9.634,4.685,4.105,0.854,1.583,4.907,92.916,95.132
1065,orient_255_pt12__70_pt12__51_a2_t0.1_s2_af2pred,0.8395,0.8395,0.6121,836,9.811,4.210,4.201,0.466,1.496,4.880,93.849,94.903
548,orient_255_pt12__31_pt12__53_a2_t0.1_s6_af2pred,0.8391,0.8391,0.6333,827,9.768,4.291,4.184,0.693,2.565,4.984,93.102,95.048
628,orient_255_pt12__31_pt12__93_a1_t0.1_s3_af2pred,0.8386,0.8386,0.6319,826,9.764,4.351,4.192,0.556,0.984,4.955,92.619,95.002
370,orient_255_pt12__2_pt12__3_a1_t0.1_s5_af2pred,0.8383,0.8383,0.6105,828,9.773,4.305,4.212,0.570,1.333,4.998,93.380,94.950
761,orient_255_pt12__33_pt12__80_a4_t0.1_s5_af2pred,0.8374,0.8374,0.5896,835,9.806,4.255,4.235,0.577,1.503,4.556,94.919,94.928
34,orient_252_pt20__31_pt12__97_a3_t0.1_s1_af2pred,0.8366,0.8366,0.6052,869,9.965,4.349,4.312,0.627,1.262,4.755,93.016,94.686
21,orient_252_pt20__31_pt12__53_a1_t0.1_s6_af2pred,0.8339,0.8339,0.4995,866,9.951,4.434,4.362,0.538,0.878,4.803,94.545,94.155
395,orient_255_pt12__2_pt12__49_a1_t0.1_s3_af2pred,0.8336,0.8336,0.5933,820,9.735,4.562,4.277,0.657,1.245,4.768,93.570,94.855
745,orient_255_pt12__33_pt12__76_a2_t0.1_s6_af2pred,0.8317,0.8317,0.5710,830,9.783,4.377,4.304,0.547,2.599,4.619,93.710,95.044
394,orient_255_pt12__2_pt12__49_a15_t0.15_s4_af2pred,0.8303,0.8303,0.6146,819,9.730,4.649,4.323,0.876,1.462,4.928,91.753,94.817
1069,orient_255_pt12__70_pt12__51_a4_t0.1_s7_af2pred,0.8289,0.8289,0.5602,835,9.806,4.400,4.380,0.439,1.339,4.767,94.792,94.771
1037,orient_255_pt12__70_pt12__37_a2_t0.1_s4_af2pred,0.8289,0.8289,0.6103,832,9.792,4.422,4.372,0.439,1.077,4.946,92.893,94.865
768,orient_255_pt12__33_pt12__81_a2_t0.1_s6_af2pred,0.8270,0.8270,0.5456,837,9.816,4.409,4.409,0.760,2.174,4.643,93.643,94.851
726,orient_255_pt12__33_pt12__66_a1_t0.1_s6_af2pred,0.8266,0.8266,0.5891,828,9.773,4.522,4.404,0.561,1.924,4.969,94.132,94.969
1129,orient_255_pt12__70_pt12__75_a8_t0.1_s5_af2pred,0.8261,0.8261,0.5529,837,9.816,4.442,4.442,0.491,0.893,4.817,94.228,94.906
502,orient_255_pt12__31_pt12__31_a9_t0.1_s3_af2pred,0.8258,0.8258,0.5853,837,9.816,4.452,4.452,0.529,1.040,4.881,94.033,94.930
698,orient_255_pt12__33_pt12__54_a1_t0.1_s5_af2pred,0.8244,0.8244,0.6059,825,9.759,4.591,4.436,0.765,1.859,4.757,92.471,95.104
25,orient_252_pt20__31_pt12__72_a10_t0.1_s2_af2pred,0.8210,0.8210,0.4780,864,9.942,4.668,4.574,0.668,0.840,4.780,93.612,94.036
666,orient_255_pt12__33_pt12__27_a2_t0.1_s7_af2pred,0.8152,0.8152,0.6370,829,9.778,4.691,4.589,0.780,1.901,4.978,92.338,95.096
28,orient_252_pt20__31_pt12__72_a7_t0.1_s7_af2pred,0.8139,0.8139,0.5262,867,9.955,4.746,4.688,0.586,0.873,4.999,93.076,94.044
1034,orient_255_pt12__70_pt12__37_a1_t0.1_s7_af2pred,0.8126,0.8126,0.5801,832,9.792,4.695,4.644,0.574,1.941,4.988,93.621,94.866
11,orient_252_pt20__31_pt12__16_a5_t0.1_s2_af2pred,0.8099,0.8099,0.4650,869,9.965,4.800,4.765,0.489,0.986,4.981,94.807,94.051
26,orient_252_pt20__31_pt12__72_a1_t0.1_s5_af2pred,0.8067,0.8067,0.5395,858,9.914,4.944,4.782,0.716,1.215,4.989,92.268,93.862

In [8]:
merged_df.to_csv('/n/groups/marks/users/aaron/pmhc_cp/af_init_guess/outputs/r3/af2_ipae_ipsae_scores.csv')